package me.noci.challenges.challenge.modifiers.allitem;

import lombok.Getter;
import me.noci.challenges.ResourcePack;
import net.kyori.adventure.text.Component;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.PotionType;
import org.jetbrains.annotations.Nullable;

public enum AllItem {

    ACACIA_BOAT("Akazienboot", Material.ACACIA_BOAT, false),
    ACACIA_BUTTON("Akazienknopf", Material.ACACIA_BUTTON, true),
    ACACIA_CHEST_BOAT("Akazientruhenboot", Material.ACACIA_CHEST_BOAT, false),
    ACACIA_DOOR("Akazientür", Material.ACACIA_DOOR, false),
    ACACIA_FENCE("Akazienzaun", Material.ACACIA_FENCE, true),
    ACACIA_FENCE_GATE("Akazienzauntor", Material.ACACIA_FENCE_GATE, true),
    ACACIA_HANGING_SIGN("Akazienhängeschild", Material.ACACIA_HANGING_SIGN, false),
    ACACIA_LEAVES("Akazienlaub", Material.ACACIA_LEAVES, true),
    ACACIA_LOG("Akazienstamm", Material.ACACIA_LOG, true),
    ACACIA_LOG_STRIPPED("Entrindeter Akazienstamm", Material.STRIPPED_ACACIA_LOG, true),
    ACACIA_PLANKS("Akazienbretter", Material.ACACIA_PLANKS, true),
    ACACIA_PRESSURE_PLATE("Akaziendruckplatte", Material.ACACIA_PRESSURE_PLATE, true),
    ACACIA_SAPLING("Akaziensetzling", Material.ACACIA_SAPLING, false),
    ACACIA_SIGN("Akazienschild", Material.ACACIA_SIGN, false),
    ACACIA_SLAB("Akazienstufe", Material.ACACIA_SLAB, true),
    ACACIA_STAIRS("Akazientreppe", Material.ACACIA_STAIRS, true),
    ACACIA_TRAPDOOR("Akazienfalltür", Material.ACACIA_TRAPDOOR, true),
    ACACIA_WOOD("Akazienholz", Material.ACACIA_WOOD, true),
    ACACIA_WOOD_STRIPPED("Entrindetes Akazienholz", Material.STRIPPED_ACACIA_WOOD, true),
    ALLIUM("Zierlauch", Material.ALLIUM, false),
    AMETHYST_BLOCK("Amethystblock", Material.AMETHYST_BLOCK, true),
    AMETHYST_BUD_LARGE("Große Amethystknospe", Material.LARGE_AMETHYST_BUD, false),
    AMETHYST_BUD_MEDIUM("Mittlere Amethystknospe", Material.MEDIUM_AMETHYST_BUD, false),
    AMETHYST_BUD_SMALL("", Material.SMALL_AMETHYST_BUD, false),
    AMETHYST_CLUSTER("Amethysthaufen", Material.AMETHYST_CLUSTER, false),
    AMETHYST_SHARD("Amethystscherbe", Material.AMETHYST_SHARD, false),
    ANCIENT_DEBRIS("Antiker Schrott", Material.ANCIENT_DEBRIS, true),
    ANDESITE("Andesit", Material.ANDESITE, true),
    ANDESITE_SLAB("Andesitstufe", Material.ANDESITE_SLAB, true),
    ANDESITE_STAIRS("Andesittreppe", Material.ANDESITE_STAIRS, true),
    ANDESITE_WALL("Andesitmauer", Material.ANDESITE_WALL, true),
    ANVIL("Amboss", Material.ANVIL, true),
    ANVIL_CHIPPED("Angeschlagener Amboss", Material.CHIPPED_ANVIL, true),
    ANVIL_DAMAGED("Beschädigter Amboss", Material.DAMAGED_ANVIL, true),
    APPLE("Apfel", Material.APPLE, false),
    APPLE_GOLDEN("Goldener Apfel", Material.GOLDEN_APPLE, false),
    APPLE_GOLDEN_ENCHANTED("Verzauberter goldener Apfel", Material.ENCHANTED_GOLDEN_APPLE, true),
    ARMOR_STAND("Rüstungsständer", Material.ARMOR_STAND, false),
    ARROW("Pfeil", Material.ARROW, false),
    AZALEA("Azalee", Material.AZALEA, true),
    AZALEA_LEAVES("Azaleenlaub", Material.AZALEA_LEAVES, true),
    AZURE_BLUET("Porzellansternchen", Material.AZURE_BLUET, false),
    BAMBOO("Bambus", Material.BAMBOO, false),
    BAMBOO_BLOCK("Bambusblock", Material.BAMBOO_BLOCK, true),
    BAMBOO_BUTTON("Bambusknopf", Material.BAMBOO_BUTTON, true),
    BAMBOO_CHEST_RAFT("Bambus-Truhenfloß", Material.BAMBOO_CHEST_RAFT, false),
    BAMBOO_DOOR("Bambustür", Material.BAMBOO_DOOR, false),
    BAMBOO_FENCE("Bambuszaun", Material.BAMBOO_FENCE, true),
    BAMBOO_FENCE_GATE("Bambuszauntor", Material.BAMBOO_FENCE_GATE, true),
    BAMBOO_HANGING_SIGN("Bambushängeschild", Material.BAMBOO_HANGING_SIGN, false),
    BAMBOO_MOSAIC("Bambusmosaik", Material.BAMBOO_MOSAIC, true),
    BAMBOO_MOSAIC_SLAB("Bambusmosaikstufe", Material.BAMBOO_MOSAIC_SLAB, true),
    BAMBOO_MOSAIC_STAIRS("Bambusmosaiktreppe", Material.BAMBOO_MOSAIC_STAIRS, true),
    BAMBOO_PLANKS("Bambusbretter", Material.BAMBOO_PLANKS, true),
    BAMBOO_PRESSURE_PLATE("Bambusdruckplatte", Material.BAMBOO_PRESSURE_PLATE, true),
    BAMBOO_RAFT("Bambusfloß", Material.BAMBOO_RAFT, false),
    BAMBOO_SIGN("Bambusschild", Material.BAMBOO_SIGN, false),
    BAMBOO_SLAB("Bambusstufe", Material.BAMBOO_SLAB, true),
    BAMBOO_STAIRS("Bambustreppe", Material.BAMBOO_STAIRS, true),
    BAMBOO_TRAPDOOR("Bambusfallltür", Material.BAMBOO_TRAPDOOR, true),
    BANNER_BLACK("Schwarzes Banner", Material.BLACK_BANNER, true),
    BANNER_BLUE("Blaues Banner", Material.BLUE_BANNER, true),
    BANNER_BROWN("Braunes Banner", Material.BROWN_BANNER, true),
    BANNER_CYAN("Türkises Banner", Material.CYAN_BANNER, true),
    BANNER_GRAY("Graues Banner", Material.GRAY_BANNER, true),
    BANNER_GREEN("Grünes Banner", Material.GREEN_BANNER, true),
    BANNER_LIGHT_BLUE("Hellblaues Banner", Material.LIGHT_BLUE_BANNER, true),
    BANNER_LIGHT_GRAY("Hellgraues Banner", Material.LIGHT_GRAY_BANNER, true),
    BANNER_LIME("Hellgrünes Banner", Material.LIME_BANNER, true),
    BANNER_MAGENTA("Magenta Banner", Material.MAGENTA_BANNER, true),
    BANNER_OMINOUS("Unheilvolles Banner", Material.WHITE_BANNER, true, CustomMatcher.translation("block.minecraft.ominous_banner")),
    BANNER_ORANGE("Oranges Banner", Material.ORANGE_BANNER, true),
    BANNER_PATTERN_CREPPER("Bannervorlage (Creeper)", Material.CREEPER_BANNER_PATTERN, false),
    BANNER_PATTERN_FLOWER("Bannervorlage (Blume)", Material.FLOWER_BANNER_PATTERN, false),
    BANNER_PATTERN_GLOBE("Bannervorlage (Globus)", Material.GLOBE_BANNER_PATTERN, false),
    BANNER_PATTERN_SKULL_CHARGE("Bannervorlage (Schädel)", Material.SKULL_BANNER_PATTERN, false),
    BANNER_PATTERN_SNOUT("Bannervorlage (Schnauze)", Material.PIGLIN_BANNER_PATTERN, false),
    BANNER_PATTERN_THING("Bannervorlage (Mojang-Logo)", Material.MOJANG_BANNER_PATTERN, false),
    BANNER_PINK("Rosa Banner", Material.PINK_BANNER, true),
    BANNER_PURPLE("Violettes Banner", Material.PURPLE_BANNER, true),
    BANNER_RED("", Material.RED_BANNER, true),
    BANNER_WHITE("Weißes Banner", Material.WHITE_BANNER, true),
    BANNER_YELLOW("Gelbes Banner", Material.YELLOW_BANNER, true),
    BARREL("Fass", Material.BARREL, true),
    BASALT("Basalt", Material.BASALT, true),
    BEACON("Leuchtfeuer", Material.BEACON, true),
    BED_BLACK("Schwarzes Bett", Material.BLACK_BED, true),
    BED_BLUE("Blaues Bett", Material.BLUE_BED, true),
    BED_BROWN("Braunes Bett", Material.BROWN_BED, true),
    BED_CYAN("Türkises Bett", Material.CYAN_BED, true),
    BED_GRAY("Graues Bett", Material.GRAY_BED, true),
    BED_GREEN("Grünes Bett", Material.GREEN_BED, true),
    BED_LIGHT_BLUE("Hellblaues Bett", Material.LIGHT_BLUE_BED, true),
    BED_LIGHT_GRAY("Hellgraues Bett", Material.LIGHT_GRAY_BED, true),
    BED_LIME("Hellgrünes Bett", Material.LIME_BED, true),
    BED_MAGENTA("Magenta Bett", Material.MAGENTA_BED, true),
    BED_ORANGE("Oranges Bett", Material.ORANGE_BED, true),
    BED_PINK("Rosa Bett", Material.PINK_BED, true),
    BED_PURPLE("Violettes Bett", Material.PURPLE_BED, true),
    BED_RED("", Material.RED_BED, true),
    BED_WHITE("Weißes Bett", Material.WHITE_BED, true),
    BED_YELLOW("Gelbes Bett", Material.YELLOW_BED, true),
    BEE_NEST("Bienennest", Material.BEE_NEST, true),
    BEEF("Rohes Rindfleisch", Material.BEEF, false),
    BEEF_COOKED("Steak", Material.COOKED_BEEF, false),
    BEEHIVE("Bienenstock", Material.BEEHIVE, true),
    BEETROOT("Rote Bete", Material.BEETROOT, false),
    BEETROOT_SEEDS("Rote Bete Samen", Material.BEETROOT_SEEDS, false),
    BEETROOT_SOUP("Borschtsch", Material.BEETROOT_SOUP, false),
    BELL("Glocke", Material.BELL, false),
    BIRCH_BOAT("Birkenboot", Material.BIRCH_BOAT, false),
    BIRCH_BUTTON("Birkenknopf", Material.BIRCH_BUTTON, true),
    BIRCH_CHEST_BOAT("Birkentruhenboot", Material.BIRCH_CHEST_BOAT, false),
    BIRCH_DOOR("Birkentür", Material.BIRCH_DOOR, false),
    BIRCH_FENCE("Birkenzaun", Material.BIRCH_FENCE, true),
    BIRCH_FENCE_GATE("Birkenzauntor", Material.BIRCH_FENCE_GATE, true),
    BIRCH_HANGING_SIGN("Birkenhängeschild", Material.BIRCH_HANGING_SIGN, false),
    BIRCH_LEAVES("Birkenlaub", Material.BIRCH_LEAVES, true),
    BIRCH_LOG("Birkenstamm", Material.BIRCH_LOG, true),
    BIRCH_LOG_STRIPPED("Entrindeter Birkenstamm", Material.STRIPPED_BIRCH_LOG, true),
    BIRCH_PLANKS("Birkenbretter", Material.BIRCH_PLANKS, true),
    BIRCH_PRESSURE_PLATE("Birkendruckplatte", Material.BIRCH_PRESSURE_PLATE, true),
    BIRCH_SAPLING("Birkensetzling", Material.BIRCH_SAPLING, false),
    BIRCH_SIGN("Birkenschild", Material.BIRCH_SIGN, false),
    BIRCH_SLAB("Birkenstufe", Material.BIRCH_SLAB, true),
    BIRCH_STAIRS("Birkentreppe", Material.BIRCH_STAIRS, true),
    BIRCH_TRAPDOOR("Birkenfalltür", Material.BIRCH_TRAPDOOR, true),
    BIRCH_WOOD("Birkenholz", Material.BIRCH_WOOD, true),
    BIRCH_WOOD_STRIPPED("Entrindetes Birkenholz", Material.STRIPPED_BIRCH_WOOD, true),
    BLACKSTONE("Schwarzstein", Material.BLACKSTONE, true),
    BLACKSTONE_SLAB("Schwarzsteinstufe", Material.BLACKSTONE_SLAB, true),
    BLACKSTONE_STAIRS("Schwarzsteintreppe", Material.BLACKSTONE_STAIRS, true),
    BLACKSTONE_WALL("Schwarzsteinmauer", Material.BLACKSTONE_WALL, true),
    BLAST_FURNACE("Schmelzofen", Material.BLAST_FURNACE, true),
    BLAZE_POWDER("Lohenstaub", Material.BLAZE_POWDER, false),
    BLAZE_ROD("Lohenrute", Material.BLAZE_ROD, false),
    BONE("Knochen", Material.BONE, false),
    BONE_BLOCK("Knochenblock", Material.BONE_BLOCK, true),
    BONE_MEAL("Knochenmehl", Material.BONE_MEAL, false),
    BOOK("Buch", Material.BOOK, false),
    BOOK_AND_QUIL("Buch und Feder", Material.WRITABLE_BOOK, false),
    BOOK_ENCHANTED("Verzaubertes Buch", Material.ENCHANTED_BOOK, true),
    BOOK_WRITTEN("Beschriebenes Buch", Material.WRITTEN_BOOK, false),
    BOOKSHELF("Bücherregal", Material.BOOKSHELF, true),
    BOW("Bogen", Material.BOW, false),
    BOWL("Schüssel", Material.BOWL, false),
    BREAD("Brot", Material.BREAD, false),
    BREWING_STAND("Braustand", Material.BREWING_STAND, false),
    BRICK("Ziegel", Material.BRICK, false),
    BRICK_SLAB("Ziegelstufe", Material.BRICK_SLAB, true),
    BRICK_STAIRS("Ziegeltreppe", Material.BRICK_STAIRS, true),
    BRICK_WALL("Ziegelsteinmauer", Material.BRICK_WALL, true),
    BRICKS("Ziegelsteine", Material.BRICKS, true),
    BRUSH("Pinsel", Material.BRUSH, false),
    BUCKET("Eimer", Material.BUCKET, false),
    BUCKET_AXOLOTL("Axolotleimer", Material.AXOLOTL_BUCKET, false),
    BUCKET_COD("Kabeljaueimer", Material.COD_BUCKET, false),
    BUCKET_LAVA("Lavaeimer", Material.LAVA_BUCKET, false),
    BUCKET_MILK("Milcheimer", Material.MILK_BUCKET, false),
    BUCKET_POWDER_SNOW("Pulverschneeeimer", Material.POWDER_SNOW_BUCKET, false),
    BUCKET_PUFFERFISH("Kugelfischeimer", Material.PUFFERFISH_BUCKET, false),
    BUCKET_SALMON("Lachseimer", Material.SALMON_BUCKET, false),
    BUCKET_TADPOLE("Kaulquappeneimer", Material.TADPOLE_BUCKET, false),
    BUCKET_TROPICAL_FISH("Tropenfischeimer", Material.TROPICAL_FISH_BUCKET, false),
    BUCKET_WATER("Wassereimer", Material.WATER_BUCKET, false),
    CACTUS("Kaktus", Material.CACTUS, true),
    CAKE("Kuchen", Material.CAKE, false),
    CALCITE("Kalzit", Material.CALCITE, true),
    CALIBRATED_SCULK_SENSOR("Kalibrierter Sculk-Sensor", Material.CALIBRATED_SCULK_SENSOR, true),
    CAMPFIRE("Lagerfeuer", Material.CAMPFIRE, false),
    CANDLE("Kerze", Material.CANDLE, false),
    CANDLE_BLACK("Schwarze Kerze", Material.BLACK_CANDLE, false),
    CANDLE_BLUE("Blaue Kerze", Material.BLUE_CANDLE, false),
    CANDLE_BROWN("Braune Kerze", Material.BROWN_CANDLE, false),
    CANDLE_CYAN("Türkise Kerze", Material.CYAN_CANDLE, false),
    CANDLE_GRAY("Graue Kerze", Material.GRAY_CANDLE, false),
    CANDLE_GREEN("Grüne Kerze", Material.GREEN_CANDLE, false),
    CANDLE_LIGHT_BLUE("Hellblaue Kerze", Material.LIGHT_BLUE_CANDLE, false),
    CANDLE_LIGHT_GRAY("Hellgraue Kerze", Material.LIGHT_GRAY_CANDLE, false),
    CANDLE_LIME("Hellgrüne Kerze", Material.LIME_CANDLE, false),
    CANDLE_MAGENTA("Magenta Kerze", Material.MAGENTA_CANDLE, false),
    CANDLE_ORANGE("Orange Kerze", Material.ORANGE_CANDLE, false),
    CANDLE_PINK("Rosa Kerze", Material.PINK_CANDLE, false),
    CANDLE_PURPLE("Violette Kerze", Material.PURPLE_CANDLE, false),
    CANDLE_RED("", Material.RED_CANDLE, false),
    CANDLE_YELLOW("Gelbe Kerze", Material.YELLOW_CANDLE, false),
    CARPET_BLACK("Schwarzer Teppich", Material.BLACK_CARPET, true),
    CARPET_BLUE("Blauer Teppich", Material.BLUE_CARPET, true),
    CARPET_BROWN("Brauner Teppich", Material.BROWN_CARPET, true),
    CARPET_CYAN("Türkiser Teppich", Material.CYAN_CARPET, true),
    CARPET_GRAY("Grauer Teppich", Material.GRAY_CARPET, true),
    CARPET_GREEN("Grüner Teppich", Material.GREEN_CARPET, true),
    CARPET_LIGHT_BLUE("Hellblauer Teppich", Material.LIGHT_BLUE_CARPET, true),
    CARPET_LIGHT_GRAY("Hellgrauer Teppich", Material.LIGHT_GRAY_CARPET, true),
    CARPET_LIME("Hellgrüner Teppich", Material.LIME_CARPET, true),
    CARPET_MAGENTA("Magenta Teppich", Material.MAGENTA_CARPET, true),
    CARPET_ORANGE("Oranger Teppich", Material.ORANGE_CARPET, true),
    CARPET_PINK("Rosa Teppich", Material.PINK_CARPET, true),
    CARPET_PURPLE("Violetter Teppich", Material.PURPLE_CARPET, true),
    CARPET_RED("", Material.RED_CARPET, true),
    CARPET_WHITE("Weißer Teppich", Material.WHITE_CARPET, true),
    CARPET_YELLOW("Gelber Teppich", Material.YELLOW_CARPET, true),
    CARROT("Karotte", Material.CARROT, false),
    CARROT_GOLDEN("Goldene Karotte", Material.GOLDEN_CARROT, false),
    CARROT_ON_A_STICK("Karottenrute", Material.CARROT_ON_A_STICK, false),
    CARTOGRAPHY_TABLE("Kartentisch", Material.CARTOGRAPHY_TABLE, true),
    CARVED_PUMPKIN("Geschnitzter Kürbis", Material.CARVED_PUMPKIN, true),
    CAULDRON("Kessel", Material.CAULDRON, false),
    CHAIN("Kette", Material.CHAIN, false),
    CHAINMAIL_BOOTS("Kettenstiefel", Material.CHAINMAIL_BOOTS, false),
    CHAINMAIL_CHESTPLATE("Kettenhemd", Material.CHAINMAIL_CHESTPLATE, false),
    CHAINMAIL_HELMET("Kettenhaube", Material.CHAINMAIL_HELMET, false),
    CHAINMAIL_LEGGINGS("Kettenhose", Material.CHAINMAIL_LEGGINGS, false),
    CHARCOAL("Holzkohle", Material.CHARCOAL, false),
    CHERRY_BOAT("Kirschholzboot", Material.CHERRY_BOAT, false),
    CHERRY_BUTTON("Kirschholzknopf", Material.CHERRY_BUTTON, true),
    CHERRY_CHEST_BOAT("Kirschholztruhenboot", Material.CHERRY_CHEST_BOAT, false),
    CHERRY_DOOR("Kirschholztür", Material.CHERRY_DOOR, false),
    CHERRY_FENCE("Kirschholzzaun", Material.CHERRY_FENCE, true),
    CHERRY_FENCE_GATE("Kirschholzzauntor", Material.CHERRY_FENCE_GATE, true),
    CHERRY_HANGING_SIGN("Kirschholzhängeschild", Material.CHERRY_HANGING_SIGN, false),
    CHERRY_LEAVES("Kirschlaub", Material.CHERRY_LEAVES, true),
    CHERRY_LOG("Kirschstamm", Material.CHERRY_LOG, true),
    CHERRY_LOG_STRIPPED("Entrindeter Kirschstamm", Material.STRIPPED_CHERRY_LOG, true),
    CHERRY_PLANKS("Kirschholzbretter", Material.CHERRY_PLANKS, true),
    CHERRY_PRESSURE_PLATE("Kirschholzdruckplatte", Material.CHERRY_PRESSURE_PLATE, true),
    CHERRY_SAPLING("Kirschsetzling", Material.CHERRY_SAPLING, false),
    CHERRY_SIGN("Kirschholzschild", Material.CHERRY_SIGN, false),
    CHERRY_SLAB("Kirschholzstufe", Material.CHERRY_SLAB, true),
    CHERRY_STAIRS("Kirschholztreppe", Material.CHERRY_STAIRS, true),
    CHERRY_TRAPDOOR("Kirschholzfalltür", Material.CHERRY_TRAPDOOR, true),
    CHERRY_WOOD("Kirschholz", Material.CHERRY_WOOD, true),
    CHERRY_WOOD_STRIPPED("Entrindetes Kirschholz", Material.STRIPPED_CHERRY_WOOD, true),
    CHEST("Truhe", Material.CHEST, true),
    CHICKEN("Rohes Hühnchen", Material.CHICKEN, false),
    CHICKEN_COOKED("Gebratenes Hühnchen", Material.COOKED_CHICKEN, false),
    CHISELED_BOOKSHELF("Gearbeitetes Bücherregal", Material.CHISELED_BOOKSHELF, true),
    CHISELED_DEEPSLATE("Gemeißelter Tiefenschiefer", Material.CHISELED_DEEPSLATE, true),
    CHISELED_NETHER_BRICKS("Gemeißelte Netherziegel", Material.CHISELED_NETHER_BRICKS, true),
    CHISELED_POLISHED_BLACKSTONE("Gemeißelter polierter Schwarzstein", Material.CHISELED_POLISHED_BLACKSTONE, true),
    CHISELED_QUARTZ_BLOCK("Gemeißelter Quarzblock", Material.CHISELED_QUARTZ_BLOCK, true),
    CHISELED_RED_SANDSTONE("Gemeißelter roter Sandstein", Material.CHISELED_RED_SANDSTONE, true),
    CHISELED_SANDSTONE("Gemeißelter Sandstein", Material.CHISELED_SANDSTONE, true),
    CHISELED_STONE_BRICKS("Gemeißelte Steinziegel", Material.CHISELED_STONE_BRICKS, true),
    CHORUS_FLOWER("Chorusblüte", Material.CHORUS_FLOWER, true),
    CHORUS_FRUIT("Chorusfrucht", Material.CHORUS_FRUIT, false),
    CLAY("Ton", Material.CLAY, true),
    CLAY_BALL("Tonklumpen", Material.CLAY_BALL, false),
    CLOCK("Uhr", Material.CLOCK, false),
    COAL("Kohleblock", Material.COAL, false),
    COAL_BLOCK("Kohleblock", Material.COAL_BLOCK, true),
    COAL_ORE("Steinkohle", Material.COAL_ORE, true),
    COAL_ORE_DEEPSLATE("Tiefenschiefer-Steinkohle", Material.DEEPSLATE_COAL_ORE, true),
    COARSE_DIRT("Grobe Erde", Material.COARSE_DIRT, true),
    COBBLED_DEEPSLATE("Bruchtiefenschiefer", Material.COBBLED_DEEPSLATE, true),
    COBBLED_DEEPSLATE_SLAB("Bruchtiefenschieferstufe", Material.COBBLED_DEEPSLATE_SLAB, true),
    COBBLED_DEEPSLATE_STAIRS("Bruchtiefenschiefertreppe", Material.COBBLED_DEEPSLATE_STAIRS, true),
    COBBLED_DEEPSLATE_WALL("Bruchtiefenschiefermauer", Material.COBBLED_DEEPSLATE_WALL, true),
    COBBLESTONE("Bruchstein", Material.COBBLESTONE, true),
    COBBLESTONE_SLAB("Bruchsteinstufe", Material.COBBLESTONE_SLAB, true),
    COBBLESTONE_STAIRS("Bruchsteintreppe", Material.COBBLESTONE_STAIRS, true),
    COBBLESTONE_WALL("Bruchsteinmauer", Material.COBBLESTONE_WALL, true),
    COBWEB("Spinnennetz", Material.COBWEB, false),
    COCOA_BEANS("Kakaobohnen", Material.COCOA_BEANS, false),
    COD("Roher Kabeljau", Material.COD, false),
    COD_COOKED("Gebratener Kabeljau", Material.COOKED_COD, false),
    COMPARATOR("Redstone-Komparator", Material.COMPARATOR, false),
    COMPASS("Kompass", Material.COMPASS, false),
    COMPOSTER("Komposter", Material.COMPOSTER, true),
    CONCRETE_BLACK("Schwarzer Beton", Material.BLACK_CONCRETE, true),
    CONCRETE_BLUE("Blauer Beton", Material.BLUE_CONCRETE, true),
    CONCRETE_BROWN("Brauner Beton", Material.BROWN_CONCRETE, true),
    CONCRETE_CYAN("Türkiser Beton", Material.CYAN_CONCRETE, true),
    CONCRETE_GRAY("Grauer Beton", Material.GRAY_CONCRETE, true),
    CONCRETE_GREEN("Grüner Beton", Material.GREEN_CONCRETE, true),
    CONCRETE_LIGHT_BLUE("Hellblauer Beton", Material.LIGHT_BLUE_CONCRETE, true),
    CONCRETE_LIGHT_GRAY("Hellgrauer Beton", Material.LIGHT_GRAY_CONCRETE, true),
    CONCRETE_LIME("Hellgrüner Beton", Material.LIME_CONCRETE, true),
    CONCRETE_MAGENTA("Magenta Beton", Material.MAGENTA_CONCRETE, true),
    CONCRETE_ORANGE("Oranger Beton", Material.ORANGE_CONCRETE, true),
    CONCRETE_PINK("Rosa Beton", Material.PINK_CONCRETE, true),
    CONCRETE_POWDER_BLACK("Schwarzer Trockenbeton", Material.BLACK_CONCRETE_POWDER, true),
    CONCRETE_POWDER_BLUE("Blauer Trockenbeton", Material.BLUE_CONCRETE_POWDER, true),
    CONCRETE_POWDER_BROWN("Brauner Trockenbeton", Material.BROWN_CONCRETE_POWDER, true),
    CONCRETE_POWDER_CYAN("Türkiser Trockenbeton", Material.CYAN_CONCRETE_POWDER, true),
    CONCRETE_POWDER_GRAY("Grauer Trockenbeton", Material.GRAY_CONCRETE_POWDER, true),
    CONCRETE_POWDER_GREEN("Grüner Trockenbeton", Material.GREEN_CONCRETE_POWDER, true),
    CONCRETE_POWDER_LIGHT_BLUE("Hellblauer Trockenbeton", Material.LIGHT_BLUE_CONCRETE_POWDER, true),
    CONCRETE_POWDER_LIGHT_GRAY("Hellgrauer Trockenbeton", Material.LIGHT_GRAY_CONCRETE_POWDER, true),
    CONCRETE_POWDER_LIME("Hellgrüner Trockenbeton", Material.LIME_CONCRETE_POWDER, true),
    CONCRETE_POWDER_MAGENTA("Magenta Trockenbeton", Material.MAGENTA_CONCRETE_POWDER, true),
    CONCRETE_POWDER_ORANGE("Oranger Trockenbeton", Material.ORANGE_CONCRETE_POWDER, true),
    CONCRETE_POWDER_PINK("Rosa Trockenbeton", Material.PINK_CONCRETE_POWDER, true),
    CONCRETE_POWDER_PURPLE("Violetter Trockenbeton", Material.PURPLE_CONCRETE_POWDER, true),
    CONCRETE_POWDER_RED("", Material.RED_CONCRETE_POWDER, true),
    CONCRETE_POWDER_WHITE("Weißer Trockenbeton", Material.WHITE_CONCRETE_POWDER, true),
    CONCRETE_POWDER_YELLOW("Gelber Trockenbeton", Material.YELLOW_CONCRETE_POWDER, true),
    CONCRETE_PURPLE("Violetter Beton", Material.PURPLE_CONCRETE, true),
    CONCRETE_RED("", Material.RED_CONCRETE, true),
    CONCRETE_WHITE("Weißer Beton", Material.WHITE_CONCRETE, true),
    CONCRETE_YELLOW("Gelber Beton", Material.YELLOW_CONCRETE, true),
    CONDUIT("Aquisator", Material.CONDUIT, true),
    COOKIE("Keks", Material.COOKIE, false),
    COPPER_BLOCK("Kupferblock", Material.COPPER_BLOCK, true),
    COPPER_BLOCK_RAW("Rohkupferblock", Material.RAW_COPPER_BLOCK, true),
    COPPER_BLOCK_WAXED("Gewachster Kupferblock", Material.WAXED_COPPER_BLOCK, true),
    COPPER_CUT("Geschnittener Kupferblock", Material.CUT_COPPER, true),
    COPPER_CUT_EXPOSED("Angelaufener geschnittener Kupferblock", Material.EXPOSED_CUT_COPPER, true),
    COPPER_CUT_EXPOSED_WAXED("Gewachster angelaufener geschnittener Kupferblock", Material.WAXED_EXPOSED_CUT_COPPER, true),
    COPPER_CUT_SLAB("Geschnittene Kupferstufe", Material.CUT_COPPER_SLAB, true),
    COPPER_CUT_SLAB_EXPOSED("Angelaufene geschnittene Kupferstufe", Material.EXPOSED_CUT_COPPER_SLAB, true),
    COPPER_CUT_SLAB_EXPOSED_WAXED("Gewachste angelaufene geschnittene Kupferstufe", Material.WAXED_EXPOSED_CUT_COPPER_SLAB, true),
    COPPER_CUT_SLAB_WAXED("Gewachste geschnittene Kupferstufe", Material.WAXED_CUT_COPPER_SLAB, true),
    COPPER_CUT_SLAB_WEATHERED("Verwitterte geschnittene Kupferstufe", Material.WEATHERED_CUT_COPPER_SLAB, true),
    COPPER_CUT_SLAB_WEATHERED_WAXED("Gewachste verwitterte geschnittene Kupferstufe", Material.WAXED_WEATHERED_CUT_COPPER_SLAB, true),
    COPPER_CUT_STAIRS("Geschnittene Kupfertreppe", Material.CUT_COPPER_STAIRS, true),
    COPPER_CUT_STAIRS_EXPOSED("Angelaufene geschnittene Kupfertreppe", Material.EXPOSED_CUT_COPPER_STAIRS, true),
    COPPER_CUT_STAIRS_EXPOSED_WAXED("Gewachste angelaufene geschnittene Kupfertreppe", Material.WAXED_EXPOSED_CUT_COPPER_STAIRS, true),
    COPPER_CUT_STAIRS_WAXED("Gewachste geschnittene Kupfertreppe", Material.WAXED_CUT_COPPER_STAIRS, true),
    COPPER_CUT_STAIRS_WEATHERED("Verwitterte geschnittene Kupfertreppe", Material.WEATHERED_CUT_COPPER_STAIRS, true),
    COPPER_CUT_STAIRS_WEATHERED_WAXED("Gewachste verwitterte geschnittene Kupfertreppe", Material.WAXED_WEATHERED_CUT_COPPER_STAIRS, true),
    COPPER_CUT_WAXED("Gewachster geschnittener Kupferblock", Material.WAXED_CUT_COPPER, true),
    COPPER_CUT_WEATHERED("Verwitterter geschnittener Kupferblock", Material.WEATHERED_CUT_COPPER, true),
    COPPER_CUT_WEATHERED_WAXED("Gewachster verwitterter geschnittener Kupferblock", Material.WAXED_WEATHERED_CUT_COPPER, true),
    COPPER_EXPOSED("Angelaufener Kupferblock", Material.EXPOSED_COPPER, true),
    COPPER_EXPOSED_WAXED("Gewachster angelaufener Kupferblock", Material.WAXED_EXPOSED_COPPER, true),
    COPPER_INGOT("Kupferbarren", Material.COPPER_INGOT, false),
    COPPER_ORE("Kupfererz", Material.COPPER_ORE, true),
    COPPER_ORE_DEEPSLATE("Tiefenschiefer-Kupfererz", Material.DEEPSLATE_COPPER_ORE, true),
    COPPER_OXIDIZED("Oxidierter Kupferblock", Material.OXIDIZED_COPPER, true),
    COPPER_OXIDIZED_WAXED("Gewachster oxidierter Kupferblock", Material.WAXED_OXIDIZED_COPPER, true),
    COPPER_RAW("Rohkupfer", Material.RAW_COPPER, false),
    COPPER_WEATHERED("Verwitterter Kupferblock", Material.WEATHERED_COPPER, true),
    COPPER_WEATHERED_WAXED("Gewachster verwitterter Kupferblock", Material.WAXED_WEATHERED_COPPER, true),
    CORAL_BRAIN("Hirnkoralle", Material.BRAIN_CORAL, false),
    CORAL_BRAIN_BLOCK("Hirnkorallenblock", Material.BRAIN_CORAL_BLOCK, true),
    CORAL_BRAIN_BLOCK_DEAD("Abgestorbener Hirnkorallenblock", Material.DEAD_BRAIN_CORAL_BLOCK, true),
    CORAL_BRAIN_DEAD("Abgestorbene Hirnkoralle", Material.DEAD_BRAIN_CORAL, false),
    CORAL_BRAIN_FAN("Hirnkorallenfächer", Material.BRAIN_CORAL_FAN, false),
    CORAL_BRAIN_FAN_DEAD("Abgestorbener Hirnkorallenfächer", Material.DEAD_BRAIN_CORAL_FAN, false),
    CORAL_BUBBLE("Blasenkoralle", Material.BUBBLE_CORAL, false),
    CORAL_BUBBLE_BLOCK("Blasenkorallenblock", Material.BUBBLE_CORAL_BLOCK, true),
    CORAL_BUBBLE_BLOCK_DEAD("Abgestorbener Blasenkorallenblock", Material.DEAD_BUBBLE_CORAL_BLOCK, true),
    CORAL_BUBBLE_DEAD("Abgestorbene Blasenkoralle", Material.DEAD_BUBBLE_CORAL, false),
    CORAL_BUBBLE_FAN("Blasenkorallenfächer", Material.BUBBLE_CORAL_FAN, false),
    CORAL_BUBBLE_FAN_DEAD("Abgestorbener Blasenkorallenfächer", Material.DEAD_BUBBLE_CORAL_FAN, false),
    CORAL_FIRE("Feuerkoralle", Material.FIRE_CORAL, false),
    CORAL_FIRE_BLOCK("Feuerkorallenblock", Material.FIRE_CORAL_BLOCK, true),
    CORAL_FIRE_BLOCK_DEAD("Abgestorbener Feuerkorallenblock", Material.DEAD_FIRE_CORAL_BLOCK, true),
    CORAL_FIRE_DEAD("Abgestorbene Feuerkoralle", Material.DEAD_FIRE_CORAL, false),
    CORAL_FIRE_FAN("Feuerkorallenfächer", Material.FIRE_CORAL_FAN, false),
    CORAL_FIRE_FAN_DEAD("Abgestorbener Feuerkorallenfächer", Material.DEAD_FIRE_CORAL_FAN, false),
    CORAL_HORN("Geweihkoralle", Material.HORN_CORAL, false),
    CORAL_HORN_BLOCK("Geweihkorallenblock", Material.HORN_CORAL_BLOCK, true),
    CORAL_HORN_BLOCK_DEAD("Abgestorbener Geweihkorallenblock", Material.DEAD_HORN_CORAL_BLOCK, true),
    CORAL_HORN_DEAD("Abgestorbene Geweihkoralle", Material.DEAD_HORN_CORAL, false),
    CORAL_HORN_FAN("Geweihkorallenfächer", Material.HORN_CORAL_FAN, false),
    CORAL_HORN_FAN_DEAD("Abgestorbener Geweihkorallenfächer", Material.DEAD_HORN_CORAL_FAN, false),
    CORAL_TUBE("Orgelkoralle", Material.TUBE_CORAL, false),
    CORAL_TUBE_BLOCK("Orgelkorallenblock", Material.TUBE_CORAL_BLOCK, true),
    CORAL_TUBE_BLOCK_DEAD("Abgestorbener Orgelkorallenblock", Material.DEAD_TUBE_CORAL_BLOCK, true),
    CORAL_TUBE_DEAD("Abgestorbene Orgelkoralle", Material.DEAD_TUBE_CORAL, false),
    CORAL_TUBE_FAN("Orgelkorallenfächer", Material.TUBE_CORAL_FAN, false),
    CORAL_TUBE_FAN_DEAD("Abgestorbener Orgelkorallenfächer", Material.DEAD_TUBE_CORAL_FAN, false),
    CORNFLOWER("Kornblume", Material.CORNFLOWER, false),
    CRACKED_DEEPSLATE_BRICKS("Rissige Tiefenschieferziegel", Material.CRACKED_DEEPSLATE_BRICKS, true),
    CRACKED_DEEPSLATE_TILES("Rissige Tiefenschieferfliesen", Material.CRACKED_DEEPSLATE_TILES, true),
    CRACKED_NETHER_BRICKS("Rissige Netherziegel", Material.CRACKED_NETHER_BRICKS, true),
    CRACKED_POLISHED_BLACKSTONE_BRICKS("Rissige polierte Schwarzsteinziegel", Material.CRACKED_POLISHED_BLACKSTONE_BRICKS, true),
    CRACKED_STONE_BRICKS("Rissige Steinziegel", Material.CRACKED_STONE_BRICKS, true),
    CRAFTING_TABLE("Werkbank", Material.CRAFTING_TABLE, true),
    CRIMSON_BUTTON("Karmesinknopf", Material.CRIMSON_BUTTON, true),
    CRIMSON_DOOR("Karmesintür", Material.CRIMSON_DOOR, false),
    CRIMSON_FENCE("Karmesinzaun", Material.CRIMSON_FENCE, true),
    CRIMSON_FENCE_GATE("Karmesinzauntor", Material.CRIMSON_FENCE_GATE, true),
    CRIMSON_FUNGUS("Karmesinpilz", Material.CRIMSON_FUNGUS, false),
    CRIMSON_HANGING_SIGN("Karmesinhängeschild", Material.CRIMSON_HANGING_SIGN, false),
    CRIMSON_HYPHAE("Karmesinhyphen", Material.CRIMSON_HYPHAE, true),
    CRIMSON_HYPHAE_STRIPPED("Geschälte Karmesinhyphen", Material.STRIPPED_CRIMSON_HYPHAE, true),
    CRIMSON_NYLIUM("Karmesin-Nezel", Material.CRIMSON_NYLIUM, true),
    CRIMSON_PLANKS("Karmesinbretter", Material.CRIMSON_PLANKS, true),
    CRIMSON_PRESSURE_PLATE("Karmesindruckplatte", Material.CRIMSON_PRESSURE_PLATE, true),
    CRIMSON_ROOTS("Karmesinwurzeln", Material.CRIMSON_ROOTS, false),
    CRIMSON_SIGN("Karmesinschild", Material.CRIMSON_SIGN, false),
    CRIMSON_SLAB("Karmesinstufe", Material.CRIMSON_SLAB, true),
    CRIMSON_STAIRS("Karmesintreppe", Material.CRIMSON_STAIRS, true),
    CRIMSON_STEM("Karmesinstiel", Material.CRIMSON_STEM, true),
    CRIMSON_STEM_STRIPPED("Geschälter Karmesinstiel", Material.STRIPPED_CRIMSON_STEM, true),
    CRIMSON_TRAPDOOR("Karmesinfalltür", Material.CRIMSON_TRAPDOOR, true),
    CROSSBOW("Armbrust", Material.CROSSBOW, false),
    CRYING_OBSIDIAN("Weinender Obsidian", Material.CRYING_OBSIDIAN, true),
    CUPPER_CUT_OXIDIZED("Oxidierter geschnittener Kupferblock", Material.OXIDIZED_CUT_COPPER, true),
    CUPPER_CUT_OXIDIZED_WAXED("Gewachster oxidierter geschnittener Kupferblock", Material.WAXED_OXIDIZED_CUT_COPPER, true),
    CUPPER_CUT_SLAB_OXIDIZED("Oxidierte geschnittene Kupferstufe", Material.OXIDIZED_CUT_COPPER_SLAB, true),
    CUPPER_CUT_SLAB_OXIDIZED_WAXED("Gewachste oxidierte geschnittene Kupferstufe", Material.WAXED_OXIDIZED_CUT_COPPER_SLAB, true),
    CUPPER_CUT_STAIRS_OXIDIZED("Oxidierte geschnittene Kupfertreppe", Material.OXIDIZED_CUT_COPPER_STAIRS, true),
    CUPPER_CUT_STAIRS_OXIDIZED_WAXED("Gewachste oxidierte geschnittene Kupfertreppe", Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS, true),
    CUT_RED_SANDSTONE("Geschnittener roter Sandstein", Material.CUT_RED_SANDSTONE, true),
    CUT_RED_SANDSTONE_SLAB("Geschnittene rote Sandsteinstufe", Material.CUT_RED_SANDSTONE_SLAB, true),
    CUT_SANDSTONE("Geschnittener Sandstein", Material.CUT_SANDSTONE, true),
    CUT_SANDSTONE_SLAB("Geschnittene Sandsteinstufe", Material.CUT_SANDSTONE_SLAB, true),
    DANDELION("Löwenzahn", Material.DANDELION, false),
    DARK_OAK_BOAT("Schwarzeichenboot", Material.DARK_OAK_BOAT, false),
    DARK_OAK_BUTTON("Schwarzeichenknopf", Material.DARK_OAK_BUTTON, true),
    DARK_OAK_CHEST_BOAT("Schwarzeichentruhenboot", Material.DARK_OAK_CHEST_BOAT, false),
    DARK_OAK_DOOR("Schwarzeichentür", Material.DARK_OAK_DOOR, false),
    DARK_OAK_FENCE("Schwarzeichenzaun", Material.DARK_OAK_FENCE, true),
    DARK_OAK_FENCE_GATE("Schwarzeichenzauntor", Material.DARK_OAK_FENCE_GATE, true),
    DARK_OAK_HANGING_SIGN("Schwarzeichenhängeschild", Material.DARK_OAK_HANGING_SIGN, false),
    DARK_OAK_LEAVES("Schwarzeichenlaub", Material.DARK_OAK_LEAVES, true),
    DARK_OAK_LOG("Schwarzeichenstamm", Material.DARK_OAK_LOG, true),
    DARK_OAK_LOG_STRIPPED("Entrindeter Schwarzeichenstamm", Material.STRIPPED_DARK_OAK_LOG, true),
    DARK_OAK_PLANKS("Schwarzeichenbretter", Material.DARK_OAK_PLANKS, true),
    DARK_OAK_PRESSURE_PLATE("Schwarzeichendruckplatte", Material.DARK_OAK_PRESSURE_PLATE, true),
    DARK_OAK_SAPLING("Schwarzeichensetzling", Material.DARK_OAK_SAPLING, false),
    DARK_OAK_SIGN("Schwarzeichenschild", Material.DARK_OAK_SIGN, false),
    DARK_OAK_SLAB("Schwarzeichenstufe", Material.DARK_OAK_SLAB, true),
    DARK_OAK_STAIRS("Schwarzeichentreppe", Material.DARK_OAK_STAIRS, true),
    DARK_OAK_TRAPDOOR("Schwarzeichenfalltür", Material.DARK_OAK_TRAPDOOR, true),
    DARK_OAK_WOOD("Schwarzeichenholz", Material.DARK_OAK_WOOD, true),
    DARK_OAK_WOOD_STRIPPED("Entrindetes Schwazeichenholz", Material.STRIPPED_DARK_OAK_WOOD, true),
    DARK_PRISMARINE("Dunkler Prismarin", Material.DARK_PRISMARINE, true),
    DARK_PRISMARINE_SLAB("Dunkle Prismarinstufe", Material.DARK_PRISMARINE_SLAB, true),
    DARK_PRISMARINE_STAIRS("Dunkle Prismarintreppe", Material.DARK_PRISMARINE_STAIRS, true),
    DAYLIGHT_DETECTOR("Tageslichtsensor", Material.DAYLIGHT_DETECTOR, true),
    DEAD_BUSH("Toter Busch", Material.DEAD_BUSH, false),
    DECORATED_POT("Verzierter Krug", Material.DECORATED_POT, true),
    DEEPSLATE("Tiefenschiefer", Material.DEEPSLATE, true),
    DEEPSLATE_BRICK_SLAB("Tiefenschieferziegelstufe", Material.DEEPSLATE_BRICK_SLAB, true),
    DEEPSLATE_BRICK_STAIRS("Tiefenschieferziegeltreppe", Material.DEEPSLATE_BRICK_STAIRS, true),
    DEEPSLATE_BRICK_WALL("Tiefenschieferziegelmauer", Material.DEEPSLATE_BRICK_WALL, true),
    DEEPSLATE_BRICKS("Tiefenschieferziegel", Material.DEEPSLATE_BRICKS, true),
    DEEPSLATE_TILE_SLAB("Tiefenschieferfliesenstufe", Material.DEEPSLATE_TILE_SLAB, true),
    DEEPSLATE_TILE_STAIRS("Tiefenschieferfliesentreppe", Material.DEEPSLATE_TILE_STAIRS, true),
    DEEPSLATE_TILE_WALL(" Tiefenschieferfliesenmauer", Material.DEEPSLATE_TILE_WALL, true),
    DEEPSLATE_TILES("Tiefenschieferfliesen", Material.DEEPSLATE_TILES, true),
    DIAMOND("Diamant", Material.DIAMOND, false),
    DIAMOND_AXE("Diamantaxt", Material.DIAMOND_AXE, false),
    DIAMOND_BLOCK("Diamantblock", Material.DIAMOND_BLOCK, true),
    DIAMOND_BOOTS("Diamantstiefel", Material.DIAMOND_BOOTS, false),
    DIAMOND_CHESTPLATE("Diamantharnisch", Material.DIAMOND_CHESTPLATE, false),
    DIAMOND_HELMET("Diamanthelm", Material.DIAMOND_HELMET, false),
    DIAMOND_HOE("Diamanthacke", Material.DIAMOND_HOE, false),
    DIAMOND_HORSE_ARMOR("Diamantener Rossharnisch", Material.DIAMOND_HORSE_ARMOR, false),
    DIAMOND_LEGGINGS("Diamantbeinschutz", Material.DIAMOND_LEGGINGS, false),
    DIAMOND_ORE("Diamanterz", Material.DIAMOND_ORE, true),
    DIAMOND_ORE_DEEPSLATE("Tiefenschiefer-Diamanterz", Material.DEEPSLATE_DIAMOND_ORE, true),
    DIAMOND_PICKAXE("Diamantspitzhacke", Material.DIAMOND_PICKAXE, false),
    DIAMOND_SHOVEL("Diamantschaufel", Material.DIAMOND_SHOVEL, false),
    DIAMOND_SWORD("Diamantschwert", Material.DIAMOND_SWORD, false),
    DIORITE("Diorit", Material.DIORITE, true),
    DIORITE_SLAB("Dioritstufe", Material.DIORITE_SLAB, true),
    DIORITE_STAIRS("Diorittreppe", Material.DIORITE_STAIRS, true),
    DIORITE_WALL("Dioritmauer", Material.DIORITE_WALL, true),
    DIRT("Erde", Material.DIRT, true),
    DIRT_PATH("Trampelpfad", Material.DIRT_PATH, true),
    DISC_11("Schallplatte - 11", Material.MUSIC_DISC_11, false),
    DISC_13("Schallplatte - 13", Material.MUSIC_DISC_13, false),
    DISC_5("Schallplatte - Samuel Aberg - 5", Material.MUSIC_DISC_5, false),
    DISC_BLOCKS("Schallplatte - blocks", Material.MUSIC_DISC_BLOCKS, false),
    DISC_CAT("Schallplatte - cat", Material.MUSIC_DISC_CAT, false),
    DISC_CHIRP("Schallplatte - chirp", Material.MUSIC_DISC_CHIRP, false),
    DISC_FAR("Schallplatte - far", Material.MUSIC_DISC_FAR, false),
    DISC_FRAGMENT("Plattenbruchstück", Material.DISC_FRAGMENT_5, false),
    DISC_MALL("Schallplatte - mall", Material.MUSIC_DISC_MALL, false),
    DISC_MELLOHI("Schallplatte - mellohi", Material.MUSIC_DISC_MELLOHI, false),
    DISC_OTHERSIDE("Schallplatte - Lena Raine - otherside", Material.MUSIC_DISC_OTHERSIDE, false),
    DISC_PIGSTEP("Schallplatte - Lena Raine - Pigstep", Material.MUSIC_DISC_PIGSTEP, false),
    DISC_RELIC("Schallplatte - Aaron Cherof - Relic", Material.MUSIC_DISC_RELIC, false),
    DISC_STAL("Schallplatte - stal", Material.MUSIC_DISC_STAL, false),
    DISC_STRAD("Schallplatte - strad", Material.MUSIC_DISC_STRAD, false),
    DISC_WAIT("Schallplatte - wait", Material.MUSIC_DISC_WAIT, false),
    DISC_WARD("Schallplatte - ward", Material.MUSIC_DISC_WARD, false),
    DISPENSER("Werfer", Material.DISPENSER, true),
    DRAGON_BREATH("Drachenatem", Material.DRAGON_BREATH, false),
    DRAGON_EGG("Drachenei", Material.DRAGON_EGG, true),
    DRAGON_HEAD("Drachenkopf", Material.DRAGON_HEAD, true),
    DRIED_KELP("Getrockneter Seetang", Material.DRIED_KELP, false),
    DRIED_KELP_BLOCK("Getrockneter Seetangblock", Material.DRIED_KELP_BLOCK, true),
    DRIPLEAF_BIG("Großes Tropfblatt", Material.BIG_DRIPLEAF, true),
    DRIPLEAF_SMALL("", Material.SMALL_DRIPLEAF, true),
    DRIPSTONE_BLOCK("Tropfsteinblock", Material.DRIPSTONE_BLOCK, true),
    DROPPER("Spender", Material.DROPPER, true),
    DYE_BLACK("Schwarzer Farbstoff", Material.BLACK_DYE, false),
    DYE_BLUE("Blauer Farbstoff", Material.BLUE_DYE, false),
    DYE_BROWN("Brauner Farbstoff", Material.BROWN_DYE, false),
    DYE_CYAN("Türkiser Farbstoff", Material.CYAN_DYE, false),
    DYE_GRAY("Grauer Farbstoff", Material.GRAY_DYE, false),
    DYE_GREEN("Grüner Farbstoff", Material.GREEN_DYE, false),
    DYE_LIGHT_BLUE("Hellblauer Farbstoff", Material.LIGHT_BLUE_DYE, false),
    DYE_LIGHT_GRAY("Hellgrauer Farbstoff", Material.LIGHT_GRAY_DYE, false),
    DYE_LIME("Hellgrüner Farbstoff", Material.LIME_DYE, false),
    DYE_MAGNETA("Magenta Farbstoff", Material.MAGENTA_DYE, false),
    DYE_ORANGE("Oranger Farbstoff", Material.ORANGE_DYE, false),
    DYE_PINK("Rosa Farbstoff", Material.PINK_DYE, false),
    DYE_PURPLE("Violetter Farbstoff", Material.PURPLE_DYE, false),
    DYE_RED("", Material.RED_DYE, false),
    DYE_WHITE("Weißer Farbstoff", Material.WHITE_DYE, false),
    DYE_YELLOW("Gelber Farbstoff", Material.YELLOW_DYE, false),
    ECHO_SHARD("Echoscherbe", Material.ECHO_SHARD, false),
    EGG("Ei", Material.EGG, false),
    ELYTRA("Elytren", Material.ELYTRA, false),
    EMERALD("Smaragd", Material.EMERALD, false),
    EMERALD_BLOCK("Smaragdblock", Material.EMERALD_BLOCK, true),
    EMERALD_ORE("Smaragderz", Material.EMERALD_ORE, true),
    EMERALD_ORE_DEEPSLATE("Tiefenschiefer-Smaragderz", Material.DEEPSLATE_EMERALD_ORE, true),
    ENCHANTING_TABLE("Zaubertisch", Material.ENCHANTING_TABLE, true),
    END_CRYSTAL("Enderkristall", Material.END_CRYSTAL, false),
    END_ROD("Endstab", Material.END_ROD, true),
    END_STONE("Endstein", Material.END_STONE, true),
    END_STONE_BRICK_SLAB("Endsteinziegelstufe", Material.END_STONE_BRICK_SLAB, true),
    END_STONE_BRICK_STAIRS("Endsteinziegeltreppe", Material.END_STONE_BRICK_STAIRS, true),
    END_STONE_BRICK_WALL("Endsteinziegelmauer", Material.END_STONE_BRICK_WALL, true),
    END_STONE_BRICKS("Endsteinziegel", Material.END_STONE_BRICKS, true),
    ENDER_CHEST("Endertruhe", Material.ENDER_CHEST, true),
    ENDER_EYE("Enderauge", Material.ENDER_EYE, false),
    ENDER_PEARL("Enderperle", Material.ENDER_PEARL, false),
    EXPERIENCE_BOTTLE("Erfahrungsfläschchen", Material.EXPERIENCE_BOTTLE, false),
    FEATHER("Feder", Material.FEATHER, false),
    FERMENTED_SPIDER_EYE("Fermentiertes Spinnenauge", Material.FERMENTED_SPIDER_EYE, false),
    FERN("Farn", Material.FERN, true),
    FERN_LARGE("Großer Farn", Material.LARGE_FERN, true),
    FIRE_CHARGE("Feuerkugel", Material.FIRE_CHARGE, false),
    FIREWORK_ROCKET("Feuerwerksrakete", Material.FIREWORK_ROCKET, false),
    FIREWORK_STAR("Feuerwerksstern", Material.FIREWORK_STAR, true),
    FISHING_ROD("Angel", Material.FISHING_ROD, false),
    FLETCHING_TABLE("Bognertisch", Material.FLETCHING_TABLE, true),
    FLINT("Feuerstein", Material.FLINT, false),
    FLINT_AND_STEEL("Feuerzeug", Material.FLINT_AND_STEEL, false),
    FLOWER_POT("Blumentopf", Material.FLOWER_POT, false),
    FLOWERING_AZALEA("Blühende Azalee", Material.FLOWERING_AZALEA, true),
    FLOWERING_AZALEA_LEAVES("Blühendes Azaleenlaub", Material.FLOWERING_AZALEA_LEAVES, true),
    FROGLIGHT_OCHRE("Ockernes Froschlicht", Material.OCHRE_FROGLIGHT, true),
    FROGLIGHT_PEARLESCENT("Perlmutternes Froschlicht", Material.PEARLESCENT_FROGLIGHT, true),
    FROGLIGHT_VERDANT("Junggrünes Froschlicht", Material.VERDANT_FROGLIGHT, true),
    FURNACE("Ofen", Material.FURNACE, true),
    GHAST_TEAR("Ghast-Träne", Material.GHAST_TEAR, false),
    GILDED_BLACKSTONE("Golddurchzogener Schwarzstein", Material.GILDED_BLACKSTONE, true),
    GLASS("Glas", Material.GLASS, true),
    GLASS_BOTTLE("Glasflasche", Material.GLASS_BOTTLE, false),
    GLASS_PANE("Glasscheibe", Material.GLASS_PANE, false),
    GLISTERING_MELON_SLICE("Glitzernde Melonenscheibe", Material.GLISTERING_MELON_SLICE, false),
    GLOW_BERRIES("Leuchtbeeren", Material.GLOW_BERRIES, false),
    GLOW_ITEM_FRAME("Leuchtrahmen", Material.GLOW_ITEM_FRAME, false),
    GLOW_LICHEN("Leuchtflechte", Material.GLOW_LICHEN, false),
    GLOWSTONE("Leuchtstein", Material.GLOWSTONE, true),
    GLOWSTONE_DUST("Leuchtsteinstaub", Material.GLOWSTONE_DUST, false),
    GOAT_HORN("Bockshorn", Material.GOAT_HORN, false),
    GOLD_BLOCK("Goldblock", Material.GOLD_BLOCK, true),
    GOLD_BLOCK_RAW("Rohgoldblock", Material.RAW_GOLD_BLOCK, true),
    GOLD_INGOT("Goldbarren", Material.GOLD_INGOT, false),
    GOLD_NUGGET("Goldklumpen", Material.GOLD_NUGGET, false),
    GOLD_ORE("Golderz", Material.GOLD_ORE, true),
    GOLD_ORE_DEEPSLATE("Tiefenschiefer-Golderz", Material.DEEPSLATE_GOLD_ORE, true),
    GOLD_RAW("Rohgold", Material.RAW_GOLD, false),
    GOLDEN_AXE("Goldaxt", Material.GOLDEN_AXE, false),
    GOLDEN_BOOTS("Goldstiefel", Material.GOLDEN_BOOTS, false),
    GOLDEN_CHESTPLATE("Goldharnisch", Material.GOLDEN_CHESTPLATE, false),
    GOLDEN_HELMET("Goldhelm", Material.GOLDEN_HELMET, false),
    GOLDEN_HOE("Goldhacke", Material.GOLDEN_HOE, false),
    GOLDEN_HORSE_ARMOR("Goldener Rossharnisch", Material.GOLDEN_HORSE_ARMOR, false),
    GOLDEN_LEGGINGS("Goldbeinschutz", Material.GOLDEN_LEGGINGS, false),
    GOLDEN_PICKAXE("Goldspitzhacke", Material.GOLDEN_PICKAXE, false),
    GOLDEN_SHOVEL("Goldschaufel", Material.GOLDEN_SHOVEL, false),
    GOLDEN_SWORD("Goldschwert", Material.GOLDEN_SWORD, false),
    GRANITE("Granit", Material.GRANITE, true),
    GRANITE_SLAB("Granitstufe", Material.GRANITE_SLAB, true),
    GRANITE_STAIRS("Granittreppe", Material.GRANITE_STAIRS, true),
    GRANITE_WALL("Granitmauer", Material.GRANITE_WALL, true),
    GRASS("Niedriges Gras", Material.SHORT_GRASS, true),
    GRASS_BLOCK("Grasblock", Material.GRASS_BLOCK, true),
    GRASS_TALL("Hohes Gras", Material.TALL_GRASS, true),
    GRAVEL("Kies", Material.GRAVEL, true),
    GRINDSTONE("Schleifstein", Material.GRINDSTONE, true),
    GUNPOWDER("Schwarzpulver", Material.GUNPOWDER, false),
    HANGING_ROOTS("Hängende Wurzeln", Material.HANGING_ROOTS, false),
    HAY_BALE("Strohballen", Material.HAY_BLOCK, true),
    HEAD_CREEPER("Creeperkopf", Material.CREEPER_HEAD, true),
    HEAD_PIGLIN("Piglinkopf", Material.PIGLIN_HEAD, true),
    HEAD_SKELETON("", Material.SKELETON_SKULL, true),
    HEAD_WITHER_SKELETON("Wither-Skelettschädel", Material.WITHER_SKELETON_SKULL, true),
    HEAD_ZOMBIE("Zombiekopf", Material.ZOMBIE_HEAD, true),
    HEART_OF_THE_SEA("Herz des Meeres", Material.HEART_OF_THE_SEA, false),
    HEAVY_WEIGHTED_PRESSURE_PLATE("Grobwägeplatte", Material.HEAVY_WEIGHTED_PRESSURE_PLATE, true),
    HONEY_BLOCK("Honigblock", Material.HONEY_BLOCK, true),
    HONEY_BOTTLE("Honigflasche", Material.HONEY_BOTTLE, false),
    HONEYCOMB("Honigwabe", Material.HONEYCOMB, false),
    HONEYCOMB_BLOCK("Honigwabenblock", Material.HONEYCOMB_BLOCK, true),
    HOPPER("Trichter", Material.HOPPER, true),
    ICE("Eis", Material.ICE, true),
    ICE_BLUE("Blaueis", Material.BLUE_ICE, true),
    ICE_PACKED("Packeis", Material.PACKED_ICE, true),
    INK_SAC("Tintenbeutel", Material.INK_SAC, false),
    INK_SAC_GLOW("Leuchttintenbeutel", Material.GLOW_INK_SAC, false),
    IRON_AXE("Eisenaxt", Material.IRON_AXE, false),
    IRON_BARS("Eisengitter", Material.IRON_BARS, false),
    IRON_BLOCK("Eisenblock", Material.IRON_BLOCK, true),
    IRON_BLOCK_RAW("Roheisenblock", Material.RAW_IRON_BLOCK, true),
    IRON_BOOTS("Eisenstiefel", Material.IRON_BOOTS, false),
    IRON_CHESTPLATE("Eisenharnisch", Material.IRON_CHESTPLATE, false),
    IRON_DOOR("Eisentür", Material.IRON_DOOR, false),
    IRON_HELMET("Eisenhelm", Material.IRON_HELMET, false),
    IRON_HOE("Eisenhacke", Material.IRON_HOE, false),
    IRON_HORSE_ARMOR("Eiserner Rossharnisch", Material.IRON_HORSE_ARMOR, false),
    IRON_INGOT("Eisenbarren", Material.IRON_INGOT, false),
    IRON_LEGGINGS("Eisenbeinschutz", Material.IRON_LEGGINGS, false),
    IRON_NUGGET("Eisenklumpen", Material.IRON_NUGGET, false),
    IRON_ORE("Eisenerz", Material.IRON_ORE, true),
    IRON_ORE_DEEPSLATE("Tiefenschiefer-Eisenerz", Material.DEEPSLATE_IRON_ORE, true),
    IRON_PICKAXE("Eisenspitzhacke", Material.IRON_PICKAXE, false),
    IRON_RAW("Roheisen", Material.RAW_IRON, false),
    IRON_SHOVEL("Eisenschaufel", Material.IRON_SHOVEL, false),
    IRON_SWORD("Eisenschwert", Material.IRON_SWORD, false),
    IRON_TRAPDOOR("Eisenfalltür", Material.IRON_TRAPDOOR, true),
    ITEM_FRAME("Rahmen", Material.ITEM_FRAME, false),
    JACK_O_LANTERN("Kürbislaterne", Material.JACK_O_LANTERN, true),
    JUKEBOX("Plattenspieler", Material.JUKEBOX, true),
    JUNGLE_BOAT("Tropenholzboot", Material.JUNGLE_BOAT, false),
    JUNGLE_BUTTON("Tropenholzknopf", Material.JUNGLE_BUTTON, true),
    JUNGLE_CHEST_BOAT("Tropenholztruhenboot", Material.JUNGLE_CHEST_BOAT, false),
    JUNGLE_DOOR("Tropenholztür", Material.JUNGLE_DOOR, false),
    JUNGLE_FENCE("Tropenholzzaun", Material.JUNGLE_FENCE, true),
    JUNGLE_FENCE_GATE("Tropenholzzauntor", Material.JUNGLE_FENCE_GATE, true),
    JUNGLE_HANGING_SIGN("Tropenholzhängeschild", Material.JUNGLE_HANGING_SIGN, false),
    JUNGLE_LEAVES("Tropenbaumlaub", Material.JUNGLE_LEAVES, true),
    JUNGLE_LOG("Tropenbaumstamm", Material.JUNGLE_LOG, true),
    JUNGLE_LOG_STRIPPED("Entrindeter Tropenbaumstamm", Material.STRIPPED_JUNGLE_LOG, true),
    JUNGLE_PLANKS("Tropenholzbretter", Material.JUNGLE_PLANKS, true),
    JUNGLE_PRESSURE_PLATE("Tropenholzdruckplatte", Material.JUNGLE_PRESSURE_PLATE, true),
    JUNGLE_SAPLING("Tropenbaumsetzling", Material.JUNGLE_SAPLING, false),
    JUNGLE_SIGN("Tropenholzschild", Material.JUNGLE_SIGN, false),
    JUNGLE_SLAB("Tropenholzstufe", Material.JUNGLE_SLAB, true),
    JUNGLE_STAIRS("Tropenholztreppe", Material.JUNGLE_STAIRS, true),
    JUNGLE_TRAPDOOR("Tropenholzfalltür", Material.JUNGLE_TRAPDOOR, true),
    JUNGLE_WOOD("Tropenholz", Material.JUNGLE_WOOD, true),
    JUNGLE_WOOD_STRIPPED("Entrindetes Tropenholz", Material.STRIPPED_JUNGLE_WOOD, true),
    KELP("Seetang", Material.KELP, false),
    LADDER("Leiter", Material.LADDER, false),
    LANTERN("Laterne", Material.LANTERN, false),
    LAPIS("Lapislazuli", Material.LAPIS_LAZULI, false),
    LAPIS_BLOCK("Lapislazuliblock", Material.LAPIS_BLOCK, true),
    LAPIS_ORE("Lapislazulierz", Material.LAPIS_ORE, true),
    LAPIS_ORE_DEEPSLATE("Tiefenschiefer-Lapislazulierz", Material.DEEPSLATE_LAPIS_ORE, true),
    LEAD("Leine", Material.LEAD, false),
    LEATHER("Leder", Material.LEATHER, false),
    LEATHER_BOOTS("Lederstiefel", Material.LEATHER_BOOTS, true),
    LEATHER_CHESTPLATE("Lederjacke", Material.LEATHER_CHESTPLATE, true),
    LEATHER_HELMET("Lederkappe", Material.LEATHER_HELMET, true),
    LEATHER_HORSE_ARMOR("Lederner Rossharnisch", Material.LEATHER_HORSE_ARMOR, true),
    LEATHER_LEGGINGS("Lederhose", Material.LEATHER_LEGGINGS, true),
    LECTERN("Lesepult", Material.LECTERN, true),
    LEVER("Hebel", Material.LEVER, false),
    LIGHT_WEIGHTED_PRESSURE_PLATE("Feinwägeplatte", Material.LIGHT_WEIGHTED_PRESSURE_PLATE, true),
    LIGHTNING_ROD("Blitzableiter", Material.LIGHTNING_ROD, true),
    LILAC("Flieder", Material.LILAC, false),
    LILY_OF_THE_VALLEY("Maiglöckchen", Material.LILY_OF_THE_VALLEY, false),
    LILY_PAD("Seerosenblatt", Material.LILY_PAD, true),
    LODESTONE("Leitstein", Material.LODESTONE, true),
    LOOM("Webstuhl", Material.LOOM, true),
    MAGMA_BLOCK("Magmablock", Material.MAGMA_BLOCK, true),
    MAGMA_CREAM("Magmacreme", Material.MAGMA_CREAM, false),
    MANGROVE_BOAT("Mangrovenholzboot", Material.MANGROVE_BOAT, false),
    MANGROVE_BUTTON("Mangrovenholzknopf", Material.MANGROVE_BUTTON, true),
    MANGROVE_CHEST_BOAT("Mangrovenholztruhenboot", Material.MANGROVE_CHEST_BOAT, false),
    MANGROVE_DOOR("Mangrovenholztür", Material.MANGROVE_DOOR, false),
    MANGROVE_FENCE("Mangrovenholzzaun", Material.MANGROVE_FENCE, true),
    MANGROVE_FENCE_GATE("Mangrovenholzzauntor", Material.MANGROVE_FENCE_GATE, true),
    MANGROVE_HANGING_SIGN("Mangrovenholzhängeschild", Material.MANGROVE_HANGING_SIGN, false),
    MANGROVE_LEAVES("Mangrovenlaub", Material.MANGROVE_LEAVES, true),
    MANGROVE_LOG("Mangrovenstamm", Material.MANGROVE_LOG, true),
    MANGROVE_LOG_STRIPPED("Entrindeter Mangrovenstamm", Material.STRIPPED_MANGROVE_LOG, true),
    MANGROVE_PLANKS("Mangrovenholzbretter", Material.MANGROVE_PLANKS, true),
    MANGROVE_PRESSURE_PLATE("Mangrovenholzdruckplatte", Material.MANGROVE_PRESSURE_PLATE, true),
    MANGROVE_PROPAGULE("Mangroven-Keimling", Material.MANGROVE_PROPAGULE, false),
    MANGROVE_ROOTS("Mangrovenwurzeln", Material.MANGROVE_ROOTS, true),
    MANGROVE_SIGN("Mangrovenholzschild", Material.MANGROVE_SIGN, false),
    MANGROVE_SLAB("Mangrovenholzstufe", Material.MANGROVE_SLAB, true),
    MANGROVE_STAIRS("Mangrovenholztreppe", Material.MANGROVE_STAIRS, true),
    MANGROVE_TRAPDOOR("Mangrovenholzfalltür", Material.MANGROVE_TRAPDOOR, true),
    MANGROVE_WOOD("Mangrovenholz", Material.MANGROVE_WOOD, true),
    MANGROVE_WOOD_STRIPPED("Entrindetes Mangrovenholz", Material.STRIPPED_MANGROVE_WOOD, true),
    MAP_BURIED_TREASURE("Schatzkarte", Material.FILLED_MAP, true, CustomMatcher.translation("filled_map.buried_treasure")),
    MAP_EMPTY("Leere Karte", Material.MAP, false),
    MAP_OCEAN_EXPLORER("Ozean-Entdeckerkarte", Material.FILLED_MAP, true, CustomMatcher.translation("filled_map.monument")),
    MAP_WOODLAND_EXPLORER("Wald-Entdeckerkarte", Material.FILLED_MAP, true, CustomMatcher.translation("filled_map.mansion")),
    MELON_BLOCK("Melone", Material.MELON, true),
    MELON_SEEDS("Melonenkerne", Material.MELON_SEEDS, false),
    MELON_SLICE("Melonenscheibe", Material.MELON_SLICE, false),
    MINECART("Lore", Material.MINECART, false),
    MINECART_CHEST("Güterlore", Material.CHEST_MINECART, false),
    MINECART_FURNACE("Ofenlore", Material.FURNACE_MINECART, false),
    MINECART_HOPPER("Trichterlore", Material.HOPPER_MINECART, false),
    MINECART_TNT("TNT-Lore", Material.TNT_MINECART, false),
    MOSS_BLOCK("Moosblock", Material.MOSS_BLOCK, true),
    MOSS_CARPET("Moosteppich", Material.MOSS_CARPET, true),
    MOSSY_COBBLESTONE("Bemooster Bruchstein", Material.MOSSY_COBBLESTONE, true),
    MOSSY_COBBLESTONE_SLAB("Bemooste Bruchsteinstufe", Material.MOSSY_COBBLESTONE_SLAB, true),
    MOSSY_COBBLESTONE_STAIRS("Bemooste Bruchsteintreppe", Material.MOSSY_COBBLESTONE_STAIRS, true),
    MOSSY_COBBLESTONE_WALL("Bemooste Bruchsteinmauer", Material.MOSSY_COBBLESTONE_WALL, true),
    MOSSY_STONE_BRICK_SLAB("Bemooste Steinziegelstufe", Material.MOSSY_STONE_BRICK_SLAB, true),
    MOSSY_STONE_BRICK_STAIRS("Bemooste Steinziegeltreppe", Material.MOSSY_STONE_BRICK_STAIRS, true),
    MOSSY_STONE_BRICK_WALL("Bemooste Steinziegelmauer", Material.MOSSY_STONE_BRICK_WALL, true),
    MOSSY_STONE_BRICKS("Bemooste Steinziegel", Material.MOSSY_STONE_BRICKS, true),
    MUD("Schlamm", Material.MUD, true),
    MUD_BRICK_SLAB("Schlammziegelstufe", Material.MUD_BRICK_SLAB, true),
    MUD_BRICK_STAIRS("Schlammziegeltreppe", Material.MUD_BRICK_STAIRS, true),
    MUD_BRICK_WALL("Schlammziegelmauer", Material.MUD_BRICK_WALL, true),
    MUD_BRICKS("Schlammziegel", Material.MUD_BRICKS, true),
    MUD_PACKED("Fester Schlamm", Material.PACKED_MUD, true),
    MUDDY_MANGROVE_ROOTS("Schlammige Mangrovenwurzeln", Material.MUDDY_MANGROVE_ROOTS, true),
    MUSHROOM_BLOCK_BROWN("Brauner Pilzblock", Material.BROWN_MUSHROOM_BLOCK, true),
    MUSHROOM_BLOCK_RED("", Material.RED_MUSHROOM_BLOCK, true),
    MUSHROOM_BROWN("Brauner Pilz", Material.BROWN_MUSHROOM, false),
    MUSHROOM_RED("", Material.RED_MUSHROOM, false),
    MUSHROOM_STEM("Pilzstiel", Material.MUSHROOM_STEM, true),
    MUSHROOM_STEW("Pilzsuppe", Material.MUSHROOM_STEW, false),
    MUTTON("Rohes Hammelfleisch", Material.MUTTON, false),
    MUTTON_COOKED("Gebratenes Hammelfleisch", Material.COOKED_MUTTON, false),
    MYCELIUM("Myzel", Material.MYCELIUM, true),
    NAME_TAG("Namensschild", Material.NAME_TAG, false),
    NAUTILUS_SHELL("Nautilusschale", Material.NAUTILUS_SHELL, false),
    NETHER_BRICK("Netherziegel", Material.NETHER_BRICK, false),
    NETHER_BRICK_FENCE("Netherziegelzaun", Material.NETHER_BRICK_FENCE, true),
    NETHER_BRICK_SLAB("Netherziegelstufe", Material.NETHER_BRICK_SLAB, true),
    NETHER_BRICK_STAIRS("Netherziegeltreppe", Material.NETHER_BRICK_STAIRS, true),
    NETHER_BRICK_STAIRS_RED("", Material.RED_NETHER_BRICK_STAIRS, true),
    NETHER_BRICK_WALL("Netherziegelmauer", Material.NETHER_BRICK_WALL, true),
    NETHER_BRICK_WALL_RED("", Material.RED_NETHER_BRICK_WALL, true),
    NETHER_BRICKS("Netherziegel", Material.NETHER_BRICKS, true),
    NETHER_BRICKS_RED("", Material.RED_NETHER_BRICKS, true),
    NETHER_GOLD_ORE("Nethergolderz", Material.NETHER_GOLD_ORE, true),
    NETHER_QUARTZ_ORE("Netherquarzerz", Material.NETHER_QUARTZ_ORE, true),
    NETHER_SPROUTS("Nethersprossen", Material.NETHER_SPROUTS, false),
    NETHER_STAR("Netherstern", Material.NETHER_STAR, false),
    NETHER_WART("Netherwarze", Material.NETHER_WART, false),
    NETHER_WART_BLOCK("Netherwarzenblock", Material.NETHER_WART_BLOCK, true),
    NETHERITE_AXE("Netheritaxt", Material.NETHERITE_AXE, false),
    NETHERITE_BLOCK("Netheritblock", Material.NETHERITE_BLOCK, true),
    NETHERITE_BOOTS("Netheritstiefel", Material.NETHERITE_BOOTS, false),
    NETHERITE_CHESTPLATE("Netheritharnisch", Material.NETHERITE_CHESTPLATE, false),
    NETHERITE_HELMET("Netherithelm", Material.NETHERITE_HELMET, false),
    NETHERITE_HOE("Netherithacke", Material.NETHERITE_HOE, false),
    NETHERITE_INGOT("Netheritbarren", Material.NETHERITE_INGOT, false),
    NETHERITE_LEGGINGS("Netheritbeinschutz", Material.NETHERITE_LEGGINGS, false),
    NETHERITE_PICKAXE("Netheritspitzhacke", Material.NETHERITE_PICKAXE, false),
    NETHERITE_SCRAP("Netheritplatten", Material.NETHERITE_SCRAP, false),
    NETHERITE_SHOVEL("Netheritschaufel", Material.NETHERITE_SHOVEL, false),
    NETHERITE_SWORD("Netheritschwert", Material.NETHERITE_SWORD, false),
    NETHERRACK("Netherrack", Material.NETHERRACK, true),
    NOTE_BLOCK("Notenblock", Material.NOTE_BLOCK, true),
    OAK_BOAT("Eichenholzboot", Material.OAK_BOAT, false),
    OAK_BUTTON("Eichenholzknopf", Material.OAK_BUTTON, true),
    OAK_CHEST_BOAT("Eichenholztruhenboot", Material.OAK_CHEST_BOAT, false),
    OAK_DOOR("Eichenholztür", Material.OAK_DOOR, false),
    OAK_FENCE("Eichenholzzaun", Material.OAK_FENCE, true),
    OAK_FENCE_GATE("Eichenholzzauntor", Material.OAK_FENCE_GATE, true),
    OAK_HANGING_SIGN("Eichenholzhängeschild", Material.OAK_HANGING_SIGN, false),
    OAK_LEAVES("Eichenlaub", Material.OAK_LEAVES, true),
    OAK_LOG("Eichenstamm", Material.OAK_LOG, true),
    OAK_LOG_STRIPPED("Entrindeter Eichenstamm", Material.STRIPPED_OAK_LOG, true),
    OAK_PLANKS("Eichenholzbretter", Material.OAK_PLANKS, true),
    OAK_PRESSURE_PLATE("Eichenholzdruckplatte", Material.OAK_PRESSURE_PLATE, true),
    OAK_SAPLING("Eichensetzling", Material.OAK_SAPLING, false),
    OAK_SIGN("Eichenholzschild", Material.OAK_SIGN, false),
    OAK_SLAB("Eichenholzstufe", Material.OAK_SLAB, true),
    OAK_STAIRS("Eichenholztreppe", Material.OAK_STAIRS, true),
    OAK_TRAPDOOR("Eichenholzfalltür", Material.OAK_TRAPDOOR, true),
    OAK_WOOD("Eichenholz", Material.OAK_WOOD, true),
    OAK_WOOD_STRIPPED("Entrindetes Eichenholz", Material.STRIPPED_OAK_WOOD, true),
    OBSERVER("Beobachter", Material.OBSERVER, true),
    OBSIDIAN("Obsidian", Material.OBSIDIAN, true),
    ORCHID("Blaue Orchidee", Material.BLUE_ORCHID, false),
    OXEYE_DAISY("Margerite", Material.OXEYE_DAISY, false),
    PAINTING("Gemälde", Material.PAINTING, false),
    PAPER("Papier", Material.PAPER, false),
    PEONY("Pfingstrose", Material.PEONY, false),
    PETALS("Rosa Blütenblätter", Material.PINK_PETALS, false),
    PHANTOM_MEMBRANE("Phantomhaut", Material.PHANTOM_MEMBRANE, false),
    PISTON("Kolben", Material.PISTON, true),
    PITCHER_PLANT("Kannenpflanze", Material.PITCHER_PLANT, false),
    PITCHER_POD("Kannenpflanzenkapsel", Material.PITCHER_POD, false),
    PODZOL("Podsol", Material.PODZOL, true),
    POINTED_DRIPSTONE("Spitzer Tropfstein", Material.POINTED_DRIPSTONE, false),
    POLISHED_ANDESITE("Polierter Andesit", Material.POLISHED_ANDESITE, true),
    POLISHED_ANDESITE_SLAB("Polierte Andesitstufe", Material.POLISHED_ANDESITE_SLAB, true),
    POLISHED_ANDESITE_STAIRS("Polierte Andesittreppe", Material.POLISHED_ANDESITE_STAIRS, true),
    POLISHED_BASALT("Polierter Basalt", Material.POLISHED_BASALT, true),
    POLISHED_BLACKSTONE("Polierter Schwarzstein", Material.POLISHED_BLACKSTONE, true),
    POLISHED_BLACKSTONE_BRICK_SLAB("Polierte Schwarzsteinziegelstufe", Material.POLISHED_BLACKSTONE_BRICK_SLAB, true),
    POLISHED_BLACKSTONE_BRICK_STAIRS("Polierte Schwarzsteinziegeltreppe", Material.POLISHED_BLACKSTONE_BRICK_STAIRS, true),
    POLISHED_BLACKSTONE_BRICK_WALL("Polierte Schwarzsteinziegelmauer", Material.POLISHED_BLACKSTONE_BRICK_WALL, true),
    POLISHED_BLACKSTONE_BRICKS("Polierte Schwarzsteinziegel", Material.POLISHED_BLACKSTONE_BRICKS, true),
    POLISHED_BLACKSTONE_BUTTON("Polierter Schwarzsteinknopf", Material.POLISHED_BLACKSTONE_BUTTON, true),
    POLISHED_BLACKSTONE_PRESSURE_PLATE("Polierte Schwarzsteindruckplatte", Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, true),
    POLISHED_BLACKSTONE_SLAB("Polierte Schwarzsteinstufe", Material.POLISHED_BLACKSTONE_SLAB, true),
    POLISHED_BLACKSTONE_STAIRS("Polierte Schwarzsteintreppe", Material.POLISHED_BLACKSTONE_STAIRS, true),
    POLISHED_BLACKSTONE_WALL("Polierte Schwarzsteinmauer", Material.POLISHED_BLACKSTONE_WALL, true),
    POLISHED_DEEPSLATE("Polierter Tiefenschiefer", Material.POLISHED_DEEPSLATE, true),
    POLISHED_DEEPSLATE_SLAB("Polierte Tiefenschieferstufe", Material.POLISHED_DEEPSLATE_SLAB, true),
    POLISHED_DEEPSLATE_STAIRS("Polierte Tiefenschiefertreppe", Material.POLISHED_DEEPSLATE_STAIRS, true),
    POLISHED_DEEPSLATE_WALL("Polierte Tiefenschiefermauer", Material.POLISHED_DEEPSLATE_WALL, true),
    POLISHED_DIORITE("Polierter Diorit", Material.POLISHED_DIORITE, true),
    POLISHED_DIORITE_SLAB("Polierte Dioritstufe", Material.POLISHED_DIORITE_SLAB, true),
    POLISHED_DIORITE_STAIRS("Polierte Diorittreppe", Material.POLISHED_DIORITE_STAIRS, true),
    POLISHED_GRANITE("Polierter Granit", Material.POLISHED_GRANITE, true),
    POLISHED_GRANITE_SLAB("Polierte Granitstufe", Material.POLISHED_GRANITE_SLAB, true),
    POLISHED_GRANITE_STAIRS("Polierte Granittreppe", Material.POLISHED_GRANITE_STAIRS, true),
    POPPED_CHORUS_FRUIT("Geplatzte Chorusfrucht", Material.POPPED_CHORUS_FRUIT, false),
    POPPY("Mohn", Material.POPPY, false),
    PORKCHOP("Rohes Schweinefleisch", Material.PORKCHOP, false),
    PORKCHOP_COOKED("Gebratenes Schweinefleisch", Material.COOKED_PORKCHOP, false),
    POTATO("Kartoffel", Material.POTATO, false),
    POTATO_BAKED("Ofenkartoffel", Material.BAKED_POTATO, false),
    POTATO_POISONOUS("Giftige Kartoffel", Material.POISONOUS_POTATO, false),
    POTION_AWKWARD("", Material.POTION, true, CustomMatcher.potion(PotionType.AWKWARD)),
    POTION_FIRE_RESISTANCE("", Material.POTION, true, CustomMatcher.potion(PotionType.FIRE_RESISTANCE)),
    POTION_FIRE_RESISTANCE_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_FIRE_RESISTANCE)),
    POTION_HARMING("", Material.POTION, true, CustomMatcher.potion(PotionType.INSTANT_DAMAGE)),
    POTION_HARMING_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_HARMING)),
    POTION_HEALING("", Material.POTION, true, CustomMatcher.potion(PotionType.INSTANT_HEAL)),
    POTION_HEALING_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_HEALING)),
    POTION_INVISIBILITY("", Material.POTION, true, CustomMatcher.potion(PotionType.INVISIBILITY)),
    POTION_INVISIBILITY_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_INVISIBILITY)),
    POTION_LEAPING("", Material.POTION, true, CustomMatcher.potion(PotionType.JUMP)),
    POTION_LEAPING_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_LEAPING)),
    POTION_LEAPING_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_LEAPING)),
    POTION_MUNDANE("", Material.POTION, true, CustomMatcher.potion(PotionType.MUNDANE)),
    POTION_NIGHT_VISION("", Material.POTION, true, CustomMatcher.potion(PotionType.NIGHT_VISION)),
    POTION_NIGHT_VISION_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_NIGHT_VISION)),
    POTION_POISON("", Material.POTION, true, CustomMatcher.potion(PotionType.POISON)),
    POTION_POISON_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_POISON)),
    POTION_POISON_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_POISON)),
    POTION_REGENERATION("", Material.POTION, true, CustomMatcher.potion(PotionType.REGEN)),
    POTION_REGENERATION_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_REGENERATION)),
    POTION_REGENERATION_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_REGENERATION)),
    POTION_SLOW_FALLING("", Material.POTION, true, CustomMatcher.potion(PotionType.SLOW_FALLING)),
    POTION_SLOW_FALLING_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_SLOW_FALLING)),
    POTION_SLOWNESS("", Material.POTION, true, CustomMatcher.potion(PotionType.SLOWNESS)),
    POTION_SLOWNESS_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_SLOWNESS)),
    POTION_SLOWNESS_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_SLOWNESS)),
    POTION_STRENGTH("", Material.POTION, true, CustomMatcher.potion(PotionType.STRENGTH)),
    POTION_STRENGTH_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_STRENGTH)),
    POTION_STRENGTH_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_STRENGTH)),
    POTION_SWIFTNESS("", Material.POTION, true, CustomMatcher.potion(PotionType.SPEED)),
    POTION_SWIFTNESS_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_SWIFTNESS)),
    POTION_SWIFTNESS_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_SWIFTNESS)),
    POTION_THICK("", Material.POTION, true, CustomMatcher.potion(PotionType.THICK)),
    POTION_TURTLE_MASTER("", Material.POTION, true, CustomMatcher.potion(PotionType.TURTLE_MASTER)),
    POTION_TURTLE_MASTER_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_TURTLE_MASTER)),
    POTION_TURTLE_MASTER_STRONG("", Material.POTION, true, CustomMatcher.potion(PotionType.STRONG_TURTLE_MASTER)),
    POTION_WATER_BOTTLE("", Material.POTION, true, CustomMatcher.potion(PotionType.WATER)),
    POTION_WATER_BREATHING("", Material.POTION, true, CustomMatcher.potion(PotionType.WATER_BREATHING)),
    POTION_WATER_BREATHING_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_WATER_BREATHING)),
    POTION_WEAKNESS("", Material.POTION, true, CustomMatcher.potion(PotionType.WEAKNESS)),
    POTION_WEAKNESS_LONG("", Material.POTION, true, CustomMatcher.potion(PotionType.LONG_WEAKNESS)),
    PRISMARINE("Prismarin", Material.PRISMARINE, true),
    PRISMARINE_BRICK_SLAB("Prismarinziegelstufe", Material.PRISMARINE_BRICK_SLAB, true),
    PRISMARINE_BRICK_STAIRS("Prismarinziegeltreppe", Material.PRISMARINE_BRICK_STAIRS, true),
    PRISMARINE_BRICKS("Prismarinziegel", Material.PRISMARINE_BRICKS, true),
    PRISMARINE_CRYSTALS("Prismarinkristall", Material.PRISMARINE_CRYSTALS, false),
    PRISMARINE_SHARD("Prismarinscherbe", Material.PRISMARINE_SHARD, false),
    PRISMARINE_SLAB("Prismarinstufe", Material.PRISMARINE_SLAB, true),
    PRISMARINE_STAIRS("Prismarintreppe", Material.PRISMARINE_STAIRS, true),
    PRISMARINE_WALL("Prismarinmauer", Material.PRISMARINE_WALL, true),
    PUFFERFISH("Kugelfisch", Material.PUFFERFISH, false),
    PUMPKIN("Kürbis", Material.PUMPKIN, true),
    PUMPKIN_PIE("Kürbiskuchen", Material.PUMPKIN_PIE, false),
    PUMPKIN_SEEDS("Kürbiskerne", Material.PUMPKIN_SEEDS, false),
    PURPUR_BLOCK("Purpurblock", Material.PURPUR_BLOCK, true),
    PURPUR_PILLAR("Purpursäule", Material.PURPUR_PILLAR, true),
    PURPUR_SLAB("Purpurstufe", Material.PURPUR_SLAB, true),
    PURPUR_STAIRS("Purpurtreppe", Material.PURPUR_STAIRS, true),
    QUARTZ("Netherquarz", Material.QUARTZ, false),
    QUARTZ_BLOCK("Quarzblock", Material.QUARTZ_BLOCK, true),
    QUARTZ_BRICKS("Quarzziegel", Material.QUARTZ_BRICKS, true),
    QUARTZ_PILLAR("Quarzsäule", Material.QUARTZ_PILLAR, true),
    QUARTZ_SLAB("Quarzstufe", Material.QUARTZ_SLAB, true),
    QUARTZ_STAIRS("Quarztreppe", Material.QUARTZ_STAIRS, true),
    RABBIT("Rohes Kaninchen", Material.RABBIT, false),
    RABBIT_COOKED("Gebratenes Kaninchen", Material.COOKED_RABBIT, false),
    RABBIT_FOOT("Hasenpfote", Material.RABBIT_FOOT, false),
    RABBIT_HIDE("Kaninchenfell", Material.RABBIT_HIDE, false),
    RABBIT_STEW("Kaninchenragout", Material.RABBIT_STEW, false),
    RAIL("Schiene", Material.RAIL, false),
    RAIL_ACTIVATOR("Aktivierungsschiene", Material.ACTIVATOR_RAIL, false),
    RAIL_DETECTOR("Sensorschiene", Material.DETECTOR_RAIL, false),
    RAIL_POWERED("Antriebsschiene", Material.POWERED_RAIL, false),
    RECOVERY_COMPASS("Bergungskompass", Material.RECOVERY_COMPASS, false),
    RED_NETHER_BRICK_SLAB("", Material.RED_NETHER_BRICK_SLAB, true),
    REDSTONE("", Material.REDSTONE, false),
    REDSTONE_BLOCK("Redstoneblock", Material.REDSTONE_BLOCK, true),
    REDSTONE_LAMP("", Material.REDSTONE_LAMP, true),
    REDSTONE_ORE("", Material.REDSTONE_ORE, true),
    REDSTONE_ORE_DEEPSLATE("Tiefenschiefer-Redstone-Erz", Material.DEEPSLATE_REDSTONE_ORE, true),
    REDSTONE_TORCH("", Material.REDSTONE_TORCH, false),
    REPEATER("", Material.REPEATER, false),
    RESPAWN_ANCHOR("", Material.RESPAWN_ANCHOR, true),
    ROOTED_DIRT("", Material.ROOTED_DIRT, true),
    ROSE_BUSH("", Material.ROSE_BUSH, false),
    ROTTEN_FLESH("", Material.ROTTEN_FLESH, false),
    SADDLE("", Material.SADDLE, false),
    SALMON("", Material.SALMON, false),
    SALMON_COOKED("Gebratener Lachs", Material.COOKED_SALMON, false),
    SAND("", Material.SAND, true),
    SAND_RED("", Material.RED_SAND, true),
    SANDSTONE("", Material.SANDSTONE, true),
    SANDSTONE_RED("", Material.RED_SANDSTONE, true),
    SANDSTONE_SLAB("", Material.SANDSTONE_SLAB, true),
    SANDSTONE_SLAB_RED("", Material.RED_SANDSTONE_SLAB, true),
    SANDSTONE_STAIRS("", Material.SANDSTONE_STAIRS, true),
    SANDSTONE_STAIRS_RED("", Material.RED_SANDSTONE_STAIRS, true),
    SANDSTONE_WALL("", Material.SANDSTONE_WALL, true),
    SANDSTONE_WALL_RED("", Material.RED_SANDSTONE_WALL, true),
    SCAFFOLDING("", Material.SCAFFOLDING, true),
    SCULK("", Material.SCULK, true),
    SCULK_CATALYST("", Material.SCULK_CATALYST, true),
    SCULK_SENSOR("", Material.SCULK_SENSOR, true),
    SCULK_SHRIEKER("", Material.SCULK_SHRIEKER, true),
    SCULK_VEIN("", Material.SCULK_VEIN, true),
    SCUTE("", Material.SCUTE, false),
    SEA_LANTERN("", Material.SEA_LANTERN, true),
    SEA_PICKLE("", Material.SEA_PICKLE, false),
    SEAGRASS("", Material.SEAGRASS, false),
    SHEARS("", Material.SHEARS, false),
    SHERD_ANGLER("Angler-Töpferscherbe", Material.ANGLER_POTTERY_SHERD, false),
    SHERD_ARCHER("Schützen-Töpferscherbe", Material.ARCHER_POTTERY_SHERD, false),
    SHERD_ARMS_UP("Gebärden-Töpferscherbe", Material.ARMS_UP_POTTERY_SHERD, false),
    SHERD_BLADE("Klingen-Töpferscherbe", Material.BLADE_POTTERY_SHERD, false),
    SHERD_BREWER("Brauer-Töpferscherbe", Material.BREWER_POTTERY_SHERD, false),
    SHERD_BURN("Flammen-Töpferscherbe", Material.BURN_POTTERY_SHERD, false),
    SHERD_DANGER("Gefahren-Töpferscherbe", Material.DANGER_POTTERY_SHERD, false),
    SHERD_EXPLORER("Entdecker-Töpferscherbe", Material.EXPLORER_POTTERY_SHERD, false),
    SHERD_FRIEND("Freundes-Töpferscheibe", Material.FRIEND_POTTERY_SHERD, false),
    SHERD_HEART("Herz-Töpferscherbe", Material.HEART_POTTERY_SHERD, false),
    SHERD_HEARTBREAKER("Herzschmerz-Töpferscherbe", Material.HEARTBREAK_POTTERY_SHERD, false),
    SHERD_HOWL("Geheul-Töpferscherbe", Material.HOWL_POTTERY_SHERD, false),
    SHERD_MINER("Bergarbeiter-Töpferscherbe", Material.MINER_POTTERY_SHERD, false),
    SHERD_MOURNER("Wimmerer-Töpferscherbe", Material.MOURNER_POTTERY_SHERD, false),
    SHERD_PLENTY("Reichtums-Töpferscherbe", Material.PLENTY_POTTERY_SHERD, false),
    SHERD_PRIZE("Juwelen-Töpferscherbe", Material.PRIZE_POTTERY_SHERD, false),
    SHERD_SHEAF("", Material.SHEAF_POTTERY_SHERD, false),
    SHERD_SHELTER("", Material.SHELTER_POTTERY_SHERD, false),
    SHERD_SKULL("", Material.SKULL_POTTERY_SHERD, false),
    SHERD_SNORT("Schnaub - Töpferscherbe", Material.SNORT_POTTERY_SHERD, false),
    SHIELD("", Material.SHIELD, true),
    SHROOMLIGHT("", Material.SHROOMLIGHT, true),
    SHULKER_BOX("", Material.SHULKER_BOX, true),
    SHULKER_BOX_BLACK("Schwarze Shulker-Kiste", Material.BLACK_SHULKER_BOX, true),
    SHULKER_BOX_BLUE("Blaue Shulker-Kiste", Material.BLUE_SHULKER_BOX, true),
    SHULKER_BOX_BROWN("Braune Shulker-Kiste", Material.BROWN_SHULKER_BOX, true),
    SHULKER_BOX_CYAN("Türkise Shulker-Kiste", Material.CYAN_SHULKER_BOX, true),
    SHULKER_BOX_GRAY("Graue Shulker-Kiste", Material.GRAY_SHULKER_BOX, true),
    SHULKER_BOX_GREEN("Grüne Shulker-Kiste", Material.GREEN_SHULKER_BOX, true),
    SHULKER_BOX_LIGHT_BLUE("Hellblaue Shulker-Kiste", Material.LIGHT_BLUE_SHULKER_BOX, true),
    SHULKER_BOX_LIGHT_GRAY("Hellgraue Shulker-Kiste", Material.LIGHT_GRAY_SHULKER_BOX, true),
    SHULKER_BOX_LIME("Hellgrüne Shulker-Kiste", Material.LIME_SHULKER_BOX, true),
    SHULKER_BOX_MAGENTA("Magenta Shulker-Kiste", Material.MAGENTA_SHULKER_BOX, true),
    SHULKER_BOX_ORANGE("Orange Shulker-Kiste", Material.ORANGE_SHULKER_BOX, true),
    SHULKER_BOX_PINK("Rosa Shulker-Kiste", Material.PINK_SHULKER_BOX, true),
    SHULKER_BOX_PURPLE("Violette Shulker-Kiste", Material.PURPLE_SHULKER_BOX, true),
    SHULKER_BOX_RED("", Material.RED_SHULKER_BOX, true),
    SHULKER_BOX_WHITE("Weiße Shulker-Kiste", Material.WHITE_SHULKER_BOX, true),
    SHULKER_BOX_YELLOW("Gelbe Shulker-Kiste", Material.YELLOW_SHULKER_BOX, true),
    SHULKER_SHELL("", Material.SHULKER_SHELL, false),
    SLIME_BALL("", Material.SLIME_BALL, false),
    SLIME_BLOCK("", Material.SLIME_BLOCK, true),
    SMITHING_TABLE("", Material.SMITHING_TABLE, true),
    SMOKER("", Material.SMOKER, true),
    SMOOTH_BASALT("", Material.SMOOTH_BASALT, true),
    SMOOTH_QUARTZ("", Material.SMOOTH_QUARTZ, true),
    SMOOTH_QUARTZ_SLAB("", Material.SMOOTH_QUARTZ_SLAB, true),
    SMOOTH_QUARTZ_STAIRS("", Material.SMOOTH_QUARTZ_STAIRS, true),
    SMOOTH_RED_SANDSTONE("", Material.SMOOTH_RED_SANDSTONE, true),
    SMOOTH_RED_SANDSTONE_SLAB("", Material.SMOOTH_RED_SANDSTONE_SLAB, true),
    SMOOTH_RED_SANDSTONE_STAIRS("", Material.SMOOTH_RED_SANDSTONE_STAIRS, true),
    SMOOTH_SANDSTONE("", Material.SMOOTH_SANDSTONE, true),
    SMOOTH_SANDSTONE_SLAB("", Material.SMOOTH_SANDSTONE_SLAB, true),
    SMOOTH_SANDSTONE_STAIRS("", Material.SMOOTH_SANDSTONE_STAIRS, true),
    SMOOTH_STONE("", Material.SMOOTH_STONE, true),
    SMOOTH_STONE_SLAB("", Material.SMOOTH_STONE_SLAB, true),
    SNIFFER_EGG("", Material.SNIFFER_EGG, false),
    SNOW("Schnee", Material.SNOW, true),
    SNOW_BLOCK("Schneeblock", Material.SNOW_BLOCK, true),
    SNOWBALL("Schneeball", Material.SNOWBALL, false),
    SOUL_CAMPFIRE("Seelenlagerfeuer", Material.SOUL_CAMPFIRE, false),
    SOUL_LANTERN("Seelenlaterne", Material.SOUL_LANTERN, false),
    SOUL_SAND("Seelensand", Material.SOUL_SAND, true),
    SOUL_SOIL("Seelenerde", Material.SOUL_SOIL, true),
    SOUL_TORCH("Seelenfackel", Material.SOUL_TORCH, false),
    SPECTRAL_ARROW("Spektralpfeil", Material.SPECTRAL_ARROW, false),
    SPIDER_EYE("Spinnenauge", Material.SPIDER_EYE, false),
    SPONGE("Schwamm", Material.SPONGE, true),
    SPONGE_WET("Nasser Schwamm", Material.WET_SPONGE, true),
    SPORE_BLOSSOM("Sporenblüte", Material.SPORE_BLOSSOM, true),
    SPRUCE_BOAT("Fichtenholzboot", Material.SPRUCE_BOAT, false),
    SPRUCE_BUTTON("Fichtenholzknopf", Material.SPRUCE_BUTTON, true),
    SPRUCE_CHEST_BOAT("Fichtenholztruhenboot", Material.SPRUCE_CHEST_BOAT, false),
    SPRUCE_DOOR("Fichtenholztür", Material.SPRUCE_DOOR, false),
    SPRUCE_FENCE("Fichtenholzzaun", Material.SPRUCE_FENCE, true),
    SPRUCE_FENCE_GATE("Fichtenholzzauntor", Material.SPRUCE_FENCE_GATE, true),
    SPRUCE_HANGING_SIGN("Fichtenholzhängeschild", Material.SPRUCE_HANGING_SIGN, false),
    SPRUCE_LEAVES("Fichtennadeln", Material.SPRUCE_LEAVES, true),
    SPRUCE_LOG("Fichtenstamm", Material.SPRUCE_LOG, true),
    SPRUCE_LOG_STRIPPED("Entrindeter Fichtenstamm", Material.STRIPPED_SPRUCE_LOG, true),
    SPRUCE_PLANKS("Fichtenholzbretter", Material.SPRUCE_PLANKS, true),
    SPRUCE_PRESSURE_PLATE("Fichtenholzdruckplatte", Material.SPRUCE_PRESSURE_PLATE, true),
    SPRUCE_SAPLING("Fichtensetzling", Material.SPRUCE_SAPLING, false),
    SPRUCE_SIGN("Fichtenholzschild", Material.SPRUCE_SIGN, false),
    SPRUCE_SLAB("Fichtenholzstufe", Material.SPRUCE_SLAB, true),
    SPRUCE_STAIRS("Fichtenholztreppe", Material.SPRUCE_STAIRS, true),
    SPRUCE_TRAPDOOR("Fichtenholztreppe", Material.SPRUCE_TRAPDOOR, true),
    SPRUCE_WOOD("Fichtenholz", Material.SPRUCE_WOOD, true),
    SPRUCE_WOOD_STRIPPED("Entrindetes Fichtenholz", Material.STRIPPED_SPRUCE_WOOD, true),
    SPYGLASS("Fernrohr", Material.SPYGLASS, false),
    STAINED_GLASS_BLACK("Schwarzes Glas", Material.BLACK_STAINED_GLASS, true),
    STAINED_GLASS_BLUE("Blaues Glas", Material.BLUE_STAINED_GLASS, true),
    STAINED_GLASS_BROWN("Braunes Glas", Material.BROWN_STAINED_GLASS, true),
    STAINED_GLASS_CYAN("Türkises Glas", Material.CYAN_STAINED_GLASS, true),
    STAINED_GLASS_GRAY("Graues Glas", Material.GRAY_STAINED_GLASS, true),
    STAINED_GLASS_GREEN("Grünes Glas", Material.GREEN_STAINED_GLASS, true),
    STAINED_GLASS_LIGHT_BLUE("Hellblaues Glas", Material.LIGHT_BLUE_STAINED_GLASS, true),
    STAINED_GLASS_LIGHT_GRAY("Hellgraues Glas", Material.LIGHT_GRAY_STAINED_GLASS, true),
    STAINED_GLASS_LIME("Hellgrünes Glas", Material.LIME_STAINED_GLASS, true),
    STAINED_GLASS_MAGENTA("Magenta Glas", Material.MAGENTA_STAINED_GLASS, true),
    STAINED_GLASS_ORANGE("Oranges Glas", Material.ORANGE_STAINED_GLASS, true),
    STAINED_GLASS_PANE_BLACK("Schwarze Glasscheibe", Material.BLACK_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_BLUE("Blaue Glasscheibe", Material.BLUE_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_BROWN("Braune Glasscheibe", Material.BROWN_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_CYAN("Türkise Glasscheibe", Material.CYAN_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_GRAY("Graue Glasscheibe", Material.GRAY_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_GREEN("Grüne Glasscheibe", Material.GREEN_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_LIGHT_BLUE("Hellblaue Glasscheibe", Material.LIGHT_BLUE_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_LIGHT_GRAY("Hellgraue Glasscheibe", Material.LIGHT_GRAY_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_LIME("Hellgrüne Glasscheibe", Material.LIME_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_MAGNETA("Magenta Glasscheibe", Material.MAGENTA_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_ORANGE("Orange Glasscheibe", Material.ORANGE_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_PINK("Rosa Glasscheibe", Material.PINK_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_PURPLE("Violette Glasscheibe", Material.PURPLE_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_RED("", Material.RED_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_WHITE("Weiße Glasscheibe", Material.WHITE_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PANE_YELLOW("Gelbe Glasscheibe", Material.YELLOW_STAINED_GLASS_PANE, false),
    STAINED_GLASS_PINK("Rosa Glas", Material.PINK_STAINED_GLASS, true),
    STAINED_GLASS_PURPLE("Violettes Glas", Material.PURPLE_STAINED_GLASS, true),
    STAINED_GLASS_RED("", Material.RED_STAINED_GLASS, true),
    STAINED_GLASS_WHITE("Weißes Glas", Material.WHITE_STAINED_GLASS, true),
    STAINED_GLASS_YELLOW("Gelbes Glas", Material.YELLOW_STAINED_GLASS, true),
    STICK("Stock", Material.STICK, false),
    STICKY_PISTON("Klebriger Kolben", Material.STICKY_PISTON, true),
    STONE("Stein", Material.STONE, true),
    STONE_AXE("Steinaxt", Material.STONE_AXE, false),
    STONE_BRICK_SLAB("Steinziegelstufe", Material.STONE_BRICK_SLAB, true),
    STONE_BRICK_STAIRS("Steinziegeltreppe", Material.STONE_BRICK_STAIRS, true),
    STONE_BRICK_WALL("Steinziegelmauer", Material.STONE_BRICK_WALL, true),
    STONE_BRICKS("Steinziegel", Material.STONE_BRICKS, true),
    STONE_BUTTON("Steinknopf", Material.STONE_BUTTON, true),
    STONE_HOE("Steinhacke", Material.STONE_HOE, false),
    STONE_PICKAXE("Steinspithacke", Material.STONE_PICKAXE, false),
    STONE_PRESSURE_PLATE("Steindruckplatte", Material.STONE_PRESSURE_PLATE, true),
    STONE_SHOVEL("Steinschaufel", Material.STONE_SHOVEL, false),
    STONE_SLAB("Steinstufe", Material.STONE_SLAB, true),
    STONE_STAIRS("Steintreppe", Material.STONE_STAIRS, true),
    STONE_SWORD("Steinschwert", Material.STONE_SWORD, false),
    STONECUTTER("Steinsäge", Material.STONECUTTER, true),
    STRING("Faden", Material.STRING, false),
    STRIPPED_BAMBOO_BLOCK("Geschälter Bambusblock", Material.STRIPPED_BAMBOO_BLOCK, true),
    SUGAR("Zucker", Material.SUGAR, false),
    SUGAR_CANE("Zuckerrohr", Material.SUGAR_CANE, false),
    SUNFLOWER("Sonnenblume", Material.SUNFLOWER, false),
    SUSPICIOUS_STEW("Seltsame Suppe", Material.SUSPICIOUS_STEW, false),
    SWEET_BERRIES("Süßbeeren", Material.SWEET_BERRIES, false),
    TARGET("Zeilblock", Material.TARGET, true),
    TEMPLATE_COAST("Schmiedevorlage-Küste", Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_DUNE("Schmiedevorlage-Düne", Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_EYE("Schmiedevorlage-Augen", Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_HOST("Schmiedevorlage-Gastwirt", Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_NETHERITE_UPGRADE("Schmiedevorlage-Netheritaufwertung", Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE, false),
    TEMPLATE_RAISER("Schmiedevorlage-Aufzieher", Material.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_RIB("", Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_SENTRY("", Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_SHAPER("", Material.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_SILENCE("", Material.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_SNOUT("Schmiedevorlage - Schnauzen", Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_SPIRE("Schmiedevorlage - Turmspitzen", Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_TIDE("Schmiedevorlage - Gezeiten", Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_VEX("Schmiedevorlage - Plagegeister", Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_WARD("Schmiedevorlage - Warthof", Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_WAYFINDER("Schmiedevorlage - Wegfinder", Material.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TEMPLATE_WILD("Schmiedevorlage - Wildnis", Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE, false),
    TERRACOTTA("Keramik", Material.TERRACOTTA, true),
    TERRACOTTA_BLACK("Schwarze Keramik", Material.BLACK_TERRACOTTA, true),
    TERRACOTTA_BLUE("Blaue Keramik", Material.BLUE_TERRACOTTA, true),
    TERRACOTTA_BROWN("Braune Keramik", Material.BROWN_TERRACOTTA, true),
    TERRACOTTA_CYAN("Türkise Keramik", Material.CYAN_TERRACOTTA, true),
    TERRACOTTA_GLAZED_BLACK("Schwarze glasierte Keramik", Material.BLACK_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_BLUE("Blaue glasierte Keramik", Material.BLUE_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_BROWN("Braune glasierte Keramik", Material.BROWN_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_CYAN("Türkise glasierte Keramik", Material.CYAN_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_GRAY("Graue glasierte Keramik", Material.GRAY_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_GREEN("Grüne glasierte Keramik", Material.GREEN_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_LIGHT_BLUE("Hellblaue glasierte Keramik", Material.LIGHT_BLUE_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_LIGHT_GRAY("Hellgrau glasierte Keramik", Material.LIGHT_GRAY_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_LIME("Hellgrüne glasierte Keramik", Material.LIME_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_MAGENTA("Magenta glasierte Keramik", Material.MAGENTA_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_ORANGE("Orange glasierte Keramik", Material.ORANGE_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_PINK("Rosa glasierte Keramik", Material.PINK_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_PURPLE("Violett glasierte Keramik", Material.PURPLE_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_RED("", Material.RED_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_WHITE("Weiße glasierte Keramik", Material.WHITE_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GLAZED_YELLOW("Gelbe glasierte Keramik", Material.YELLOW_GLAZED_TERRACOTTA, true),
    TERRACOTTA_GRAY("Graue Keramik", Material.GRAY_TERRACOTTA, true),
    TERRACOTTA_GREEN("Grüne Keramik", Material.GREEN_TERRACOTTA, true),
    TERRACOTTA_LIGHT_BLUE("Hellblaue Keramik", Material.LIGHT_BLUE_TERRACOTTA, true),
    TERRACOTTA_LIGHT_GRAY("Hellgraue Keramik", Material.LIGHT_GRAY_TERRACOTTA, true),
    TERRACOTTA_LIME("Hellgrüne Keramik", Material.LIME_TERRACOTTA, true),
    TERRACOTTA_MAGENTA("Magenta Keramik", Material.MAGENTA_TERRACOTTA, true),
    TERRACOTTA_ORANGE("Orange Keramik", Material.ORANGE_TERRACOTTA, true),
    TERRACOTTA_PINK("Rosa Keramik", Material.PINK_TERRACOTTA, true),
    TERRACOTTA_PURPLE("Violette Keramik", Material.PURPLE_TERRACOTTA, true),
    TERRACOTTA_RED("", Material.RED_TERRACOTTA, true),
    TERRACOTTA_WHITE("Weiße Keramik", Material.WHITE_TERRACOTTA, true),
    TERRACOTTA_YELLOW("Gelbe Keramik", Material.YELLOW_TERRACOTTA, true),
    TINTED_GLASS("Getöntes Glas", Material.TINTED_GLASS, true),
    TIPPED_ARROW("Getränkter Pfeil", Material.TIPPED_ARROW, true),
    TNT("TNT", Material.TNT, true),
    TORCH("Fackel", Material.TORCH, false),
    TORCHFLOWER("Fackellilie", Material.TORCHFLOWER, false),
    TORCHFLOWER_SEEDS("Fackelliliensamen", Material.TORCHFLOWER_SEEDS, false),
    TOTEM_OF_UNDYING("Totem der Unsterblichkeit", Material.TOTEM_OF_UNDYING, false),
    TRAPPED_CHEST("Redstone-Truhe", Material.TRAPPED_CHEST, true),
    TRIDENT("Dreizack", Material.TRIDENT, false),
    TRIPWIRE_HOOK("Haken", Material.TRIPWIRE_HOOK, false),
    TROPICAL_FISH("Tropenfisch", Material.TROPICAL_FISH, false),
    TUFF("Tuffstein", Material.TUFF, true),
    TULIP_ORANGE("Orange Tulpe", Material.ORANGE_TULIP, false),
    TULIP_PINK("Rosa Tulpe", Material.PINK_TULIP, false),
    TULIP_RED("", Material.RED_TULIP, false),
    TULIP_WHITE("Weißte Tulpe", Material.WHITE_TULIP, false),
    TURTLE_EGG("Schildkröten-Spawn-Ei", Material.TURTLE_EGG, false),
    TURTLE_HELMET("Schildkrötenpanzer", Material.TURTLE_HELMET, false),
    VINE("Ranken", Material.VINE, true),
    VINE_TWISTING("Zwirbelranken", Material.TWISTING_VINES, false),
    VINE_WEEPING("Trauerranken", Material.WEEPING_VINES, false),
    WARPED_BUTTON("Wirrknopf", Material.WARPED_BUTTON, true),
    WARPED_DOOR("Wirrtür", Material.WARPED_DOOR, false),
    WARPED_FENCE("Wirrzaun", Material.WARPED_FENCE, true),
    WARPED_FENCE_GATE("Wirrzauntor", Material.WARPED_FENCE_GATE, true),
    WARPED_FUNGUS("Wirrpilz", Material.WARPED_FUNGUS, false),
    WARPED_FUNGUS_ON_A_STICK("Wirrplizrute", Material.WARPED_FUNGUS_ON_A_STICK, false),
    WARPED_HANGING_SIGN("Wirrhängeschild", Material.WARPED_HANGING_SIGN, false),
    WARPED_HYPHAE("Wirrhyphen", Material.WARPED_HYPHAE, true),
    WARPED_NYLIUM("Wirr-Nezel", Material.WARPED_NYLIUM, true),
    WARPED_PLANKS("Wirrbretter", Material.WARPED_PLANKS, true),
    WARPED_PRESSURE_PLATE("Wirrdruckplatte", Material.WARPED_PRESSURE_PLATE, true),
    WARPED_ROOTS("Wirrwurzeln", Material.WARPED_ROOTS, false),
    WARPED_SIGN("Wirrschild", Material.WARPED_SIGN, false),
    WARPED_SLAB("Wirrstufe", Material.WARPED_SLAB, true),
    WARPED_STAIRS("Wirrtreppe", Material.WARPED_STAIRS, true),
    WARPED_STEM("Wirrstiel", Material.WARPED_STEM, true),
    WARPED_STEM_STRIPPED("Geschälter Wirrstiel", Material.STRIPPED_WARPED_STEM, true),
    WARPED_TRAPDOOR("Wirrfalltür", Material.WARPED_TRAPDOOR, true),
    WARPED_WART_BLOCK("Wirrwarzenblock", Material.WARPED_WART_BLOCK, true),
    WARRPED_HYPHAE_STRIPPED("Geschälte Wirrhyphen", Material.STRIPPED_WARPED_HYPHAE, true),
    WHEAT("Weizen", Material.WHEAT, false),
    WHEAT_SEEDS("Weizenkörner", Material.WHEAT_SEEDS, false),
    WHITE_CANDLE("Weiße Kerze", Material.WHITE_CANDLE, false),
    WITHER_ROSE("Wither-Rose", Material.WITHER_ROSE, false),
    WOODEN_AXE("Holzaxt", Material.WOODEN_AXE, false),
    WOODEN_HOE("Holzhacke", Material.WOODEN_HOE, false),
    WOODEN_PICKAXE("Holzspitzhacke", Material.WOODEN_PICKAXE, false),
    WOODEN_SHOVEL("Holzschaufel", Material.WOODEN_SHOVEL, false),
    WOODEN_SWORD("Holzschwert", Material.WOODEN_SWORD, false),
    WOOL_BLACK("Schwarze Wolle", Material.BLACK_WOOL, true),
    WOOL_BLUE("Blaue Wolle", Material.BLUE_WOOL, true),
    WOOL_BROWN("Braune Wolle", Material.BROWN_WOOL, true),
    WOOL_CYAN("Türkise Wolle", Material.CYAN_WOOL, true),
    WOOL_GRAY("Graue Wolle", Material.GRAY_WOOL, true),
    WOOL_GREEN("Grüne Wolle", Material.GREEN_WOOL, true),
    WOOL_LIGHT_BLUE("Hellblaue Wolle", Material.LIGHT_BLUE_WOOL, true),
    WOOL_LIGHT_GRAY("Hellgraue Wolle", Material.LIGHT_GRAY_WOOL, true),
    WOOL_LIME("Hellgrüne Wolle", Material.LIME_WOOL, true),
    WOOL_MAGNETA("Magenta Wolle", Material.MAGENTA_WOOL, true),
    WOOL_ORANGE("Orange Wolle", Material.ORANGE_WOOL, true),
    WOOL_PINK("Rosa Wolle", Material.PINK_WOOL, true),
    WOOL_PURPLE("Violette Wolle", Material.PURPLE_WOOL, true),
    WOOL_RED("", Material.RED_WOOL, true),
    WOOL_WHITE("Weiße Wolle", Material.WHITE_WOOL, true),
    WOOL_YELLOW("Gelbe Wolle", Material.YELLOW_WOOL, true);

    @Getter private final String itemName;
    @Nullable private final CustomMatcher customMatcher;
    private final Material material;
    private final boolean customImage;

    AllItem(String name, Material material, boolean customImage) {
        this(name, material, customImage, null);
    }

    AllItem(String name, Material material, boolean customImage, @Nullable CustomMatcher customMatcher) {
        this.itemName = name;
        this.material = material;
        this.customImage = customImage;
        this.customMatcher = customMatcher;
    }

    public boolean matches(ItemStack itemStack) {
        if (itemStack == null) return false;
        boolean customMatch = this.customMatcher == null || this.customMatcher.matches(itemStack);
        return itemStack.getType() == material && customMatch;
    }

    public Component icon() {
        return ResourcePack.AllItems.itemIcon(this);
    }

}
