package me.noci.challenges.challenge.modifiers.allitem;

import lombok.Getter;
import me.noci.challenges.ResourcePack;
import net.kyori.adventure.text.Component;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.potion.PotionType;
import org.jetbrains.annotations.Nullable;

public enum AllItem {

    ACACIA_BOAT("Akazienboot", Material.ACACIA_BOAT),
    ACACIA_BUTTON("Akazienknopf", Material.ACACIA_BUTTON),
    ACACIA_CHEST_BOAT("Akazientruhenboot", Material.ACACIA_CHEST_BOAT),
    ACACIA_DOOR("Akazientür", Material.ACACIA_DOOR),
    ACACIA_FENCE("Akazienzaun", Material.ACACIA_FENCE),
    ACACIA_FENCE_GATE("Akazienzauntor", Material.ACACIA_FENCE_GATE),
    ACACIA_HANGING_SIGN("Akazienhängeschild", Material.ACACIA_HANGING_SIGN),
    ACACIA_LEAVES("Akazienlaub", Material.ACACIA_LEAVES),
    ACACIA_LOG("Akazienstamm", Material.ACACIA_LOG),
    ACACIA_LOG_STRIPPED("Entrindeter Akazienstamm", Material.STRIPPED_ACACIA_LOG),
    ACACIA_PLANKS("Akazienbretter", Material.ACACIA_PLANKS),
    ACACIA_PRESSURE_PLATE("Akaziendruckplatte", Material.ACACIA_PRESSURE_PLATE),
    ACACIA_SAPLING("Akaziensetzling", Material.ACACIA_SAPLING),
    ACACIA_SIGN("Akazienschild", Material.ACACIA_SIGN),
    ACACIA_SLAB("Akazienstufe", Material.ACACIA_SLAB),
    ACACIA_STAIRS("Akazientreppe", Material.ACACIA_STAIRS),
    ACACIA_TRAPDOOR("Akazienfalltür", Material.ACACIA_TRAPDOOR),
    ACACIA_WOOD("Akazienholz", Material.ACACIA_WOOD),
    ACACIA_WOOD_STRIPPED("Entrindetes Akazienholz", Material.STRIPPED_ACACIA_WOOD),
    ALLIUM("Zierlauch", Material.ALLIUM),
    AMETHYST_BLOCK("Amethystblock", Material.AMETHYST_BLOCK),
    AMETHYST_BUD_LARGE("Große Amethystknospe", Material.LARGE_AMETHYST_BUD),
    AMETHYST_BUD_MEDIUM("Mittlere Amethystknospe", Material.MEDIUM_AMETHYST_BUD),
    AMETHYST_BUD_SMALL("Kleine Amethystknospe", Material.SMALL_AMETHYST_BUD),
    AMETHYST_CLUSTER("Amethysthaufen", Material.AMETHYST_CLUSTER),
    AMETHYST_SHARD("Amethystscherbe", Material.AMETHYST_SHARD),
    ANCIENT_DEBRIS("Antiker Schrott", Material.ANCIENT_DEBRIS),
    ANDESITE("Andesit", Material.ANDESITE),
    ANDESITE_SLAB("Andesitstufe", Material.ANDESITE_SLAB),
    ANDESITE_STAIRS("Andesittreppe", Material.ANDESITE_STAIRS),
    ANDESITE_WALL("Andesitmauer", Material.ANDESITE_WALL),
    ANVIL("Amboss", Material.ANVIL),
    ANVIL_CHIPPED("Angeschlagener Amboss", Material.CHIPPED_ANVIL),
    ANVIL_DAMAGED("Beschädigter Amboss", Material.DAMAGED_ANVIL),
    APPLE("Apfel", Material.APPLE),
    APPLE_GOLDEN("Goldener Apfel", Material.GOLDEN_APPLE),
    APPLE_GOLDEN_ENCHANTED("Verzauberter goldener Apfel", Material.ENCHANTED_GOLDEN_APPLE),
    ARMADILLO_SCUTE("Gürteltier-Hornschild", Material.ARMADILLO_SCUTE),
    ARMOR_STAND("Rüstungsständer", Material.ARMOR_STAND),
    ARROW("Pfeil", Material.ARROW),
    AZALEA("Azalee", Material.AZALEA),
    AZALEA_LEAVES("Azaleenlaub", Material.AZALEA_LEAVES),
    AZURE_BLUET("Porzellansternchen", Material.AZURE_BLUET),
    BAMBOO("Bambus", Material.BAMBOO),
    BAMBOO_BLOCK("Bambusblock", Material.BAMBOO_BLOCK),
    BAMBOO_BUTTON("Bambusknopf", Material.BAMBOO_BUTTON),
    BAMBOO_CHEST_RAFT("Bambus-Truhenfloß", Material.BAMBOO_CHEST_RAFT),
    BAMBOO_DOOR("Bambustür", Material.BAMBOO_DOOR),
    BAMBOO_FENCE("Bambuszaun", Material.BAMBOO_FENCE),
    BAMBOO_FENCE_GATE("Bambuszauntor", Material.BAMBOO_FENCE_GATE),
    BAMBOO_HANGING_SIGN("Bambushängeschild", Material.BAMBOO_HANGING_SIGN),
    BAMBOO_MOSAIC("Bambusmosaik", Material.BAMBOO_MOSAIC),
    BAMBOO_MOSAIC_SLAB("Bambusmosaikstufe", Material.BAMBOO_MOSAIC_SLAB),
    BAMBOO_MOSAIC_STAIRS("Bambusmosaiktreppe", Material.BAMBOO_MOSAIC_STAIRS),
    BAMBOO_PLANKS("Bambusbretter", Material.BAMBOO_PLANKS),
    BAMBOO_PRESSURE_PLATE("Bambusdruckplatte", Material.BAMBOO_PRESSURE_PLATE),
    BAMBOO_RAFT("Bambusfloß", Material.BAMBOO_RAFT),
    BAMBOO_SIGN("Bambusschild", Material.BAMBOO_SIGN),
    BAMBOO_SLAB("Bambusstufe", Material.BAMBOO_SLAB),
    BAMBOO_STAIRS("Bambustreppe", Material.BAMBOO_STAIRS),
    BAMBOO_TRAPDOOR("Bambusfallltür", Material.BAMBOO_TRAPDOOR),
    BANNER_BLACK("Schwarzes Banner", Material.BLACK_BANNER),
    BANNER_BLUE("Blaues Banner", Material.BLUE_BANNER),
    BANNER_BROWN("Braunes Banner", Material.BROWN_BANNER),
    BANNER_CYAN("Türkises Banner", Material.CYAN_BANNER),
    BANNER_GRAY("Graues Banner", Material.GRAY_BANNER),
    BANNER_GREEN("Grünes Banner", Material.GREEN_BANNER),
    BANNER_LIGHT_BLUE("Hellblaues Banner", Material.LIGHT_BLUE_BANNER),
    BANNER_LIGHT_GRAY("Hellgraues Banner", Material.LIGHT_GRAY_BANNER),
    BANNER_LIME("Hellgrünes Banner", Material.LIME_BANNER),
    BANNER_MAGENTA("Magenta Banner", Material.MAGENTA_BANNER),
    BANNER_OMINOUS("Unheilvolles Banner", Material.WHITE_BANNER, CustomMatcher.translation("block.minecraft.ominous_banner")),
    BANNER_ORANGE("Oranges Banner", Material.ORANGE_BANNER),
    BANNER_PATTERN_CREPPER("Bannervorlage (Creeper)", Material.CREEPER_BANNER_PATTERN),
    BANNER_PATTERN_FLOWER("Bannervorlage (Blume)", Material.FLOWER_BANNER_PATTERN),
    BANNER_PATTERN_GLOBE("Bannervorlage (Globus)", Material.GLOBE_BANNER_PATTERN),
    BANNER_PATTERN_SKULL_CHARGE("Bannervorlage (Schädel)", Material.SKULL_BANNER_PATTERN),
    BANNER_PATTERN_SNOUT("Bannervorlage (Schnauze)", Material.PIGLIN_BANNER_PATTERN),
    BANNER_PATTERN_THING("Bannervorlage (Mojang-Logo)", Material.MOJANG_BANNER_PATTERN),
    BANNER_PINK("Rosa Banner", Material.PINK_BANNER),
    BANNER_PURPLE("Violettes Banner", Material.PURPLE_BANNER),
    BANNER_RED("Rotes Banner", Material.RED_BANNER),
    BANNER_WHITE("Weißes Banner", Material.WHITE_BANNER),
    BANNER_YELLOW("Gelbes Banner", Material.YELLOW_BANNER),
    BARREL("Fass", Material.BARREL),
    BASALT("Basalt", Material.BASALT),
    BEACON("Leuchtfeuer", Material.BEACON),
    BED_BLACK("Schwarzes Bett", Material.BLACK_BED),
    BED_BLUE("Blaues Bett", Material.BLUE_BED),
    BED_BROWN("Braunes Bett", Material.BROWN_BED),
    BED_CYAN("Türkises Bett", Material.CYAN_BED),
    BED_GRAY("Graues Bett", Material.GRAY_BED),
    BED_GREEN("Grünes Bett", Material.GREEN_BED),
    BED_LIGHT_BLUE("Hellblaues Bett", Material.LIGHT_BLUE_BED),
    BED_LIGHT_GRAY("Hellgraues Bett", Material.LIGHT_GRAY_BED),
    BED_LIME("Hellgrünes Bett", Material.LIME_BED),
    BED_MAGENTA("Magenta Bett", Material.MAGENTA_BED),
    BED_ORANGE("Oranges Bett", Material.ORANGE_BED),
    BED_PINK("Rosa Bett", Material.PINK_BED),
    BED_PURPLE("Violettes Bett", Material.PURPLE_BED),
    BED_RED("Rotes Bett", Material.RED_BED),
    BED_WHITE("Weißes Bett", Material.WHITE_BED),
    BED_YELLOW("Gelbes Bett", Material.YELLOW_BED),
    BEE_NEST("Bienennest", Material.BEE_NEST),
    BEEF("Rohes Rindfleisch", Material.BEEF),
    BEEF_COOKED("Steak", Material.COOKED_BEEF),
    BEEHIVE("Bienenstock", Material.BEEHIVE),
    BEETROOT("Rote Bete", Material.BEETROOT),
    BEETROOT_SEEDS("Rote Bete Samen", Material.BEETROOT_SEEDS),
    BEETROOT_SOUP("Borschtsch", Material.BEETROOT_SOUP),
    BELL("Glocke", Material.BELL),
    BIRCH_BOAT("Birkenboot", Material.BIRCH_BOAT),
    BIRCH_BUTTON("Birkenknopf", Material.BIRCH_BUTTON),
    BIRCH_CHEST_BOAT("Birkentruhenboot", Material.BIRCH_CHEST_BOAT),
    BIRCH_DOOR("Birkentür", Material.BIRCH_DOOR),
    BIRCH_FENCE("Birkenzaun", Material.BIRCH_FENCE),
    BIRCH_FENCE_GATE("Birkenzauntor", Material.BIRCH_FENCE_GATE),
    BIRCH_HANGING_SIGN("Birkenhängeschild", Material.BIRCH_HANGING_SIGN),
    BIRCH_LEAVES("Birkenlaub", Material.BIRCH_LEAVES),
    BIRCH_LOG("Birkenstamm", Material.BIRCH_LOG),
    BIRCH_LOG_STRIPPED("Entrindeter Birkenstamm", Material.STRIPPED_BIRCH_LOG),
    BIRCH_PLANKS("Birkenbretter", Material.BIRCH_PLANKS),
    BIRCH_PRESSURE_PLATE("Birkendruckplatte", Material.BIRCH_PRESSURE_PLATE),
    BIRCH_SAPLING("Birkensetzling", Material.BIRCH_SAPLING),
    BIRCH_SIGN("Birkenschild", Material.BIRCH_SIGN),
    BIRCH_SLAB("Birkenstufe", Material.BIRCH_SLAB),
    BIRCH_STAIRS("Birkentreppe", Material.BIRCH_STAIRS),
    BIRCH_TRAPDOOR("Birkenfalltür", Material.BIRCH_TRAPDOOR),
    BIRCH_WOOD("Birkenholz", Material.BIRCH_WOOD),
    BIRCH_WOOD_STRIPPED("Entrindetes Birkenholz", Material.STRIPPED_BIRCH_WOOD),
    BLACKSTONE("Schwarzstein", Material.BLACKSTONE),
    BLACKSTONE_SLAB("Schwarzsteinstufe", Material.BLACKSTONE_SLAB),
    BLACKSTONE_STAIRS("Schwarzsteintreppe", Material.BLACKSTONE_STAIRS),
    BLACKSTONE_WALL("Schwarzsteinmauer", Material.BLACKSTONE_WALL),
    BLAST_FURNACE("Schmelzofen", Material.BLAST_FURNACE),
    BLAZE_POWDER("Lohenstaub", Material.BLAZE_POWDER),
    BLAZE_ROD("Lohenrute", Material.BLAZE_ROD),
    BONE("Knochen", Material.BONE),
    BONE_BLOCK("Knochenblock", Material.BONE_BLOCK),
    BONE_MEAL("Knochenmehl", Material.BONE_MEAL),
    BOOK("Buch", Material.BOOK),
    BOOK_AND_QUIL("Buch und Feder", Material.WRITABLE_BOOK),
    BOOK_ENCHANTED("Verzaubertes Buch", Material.ENCHANTED_BOOK),
    BOOK_WRITTEN("Beschriebenes Buch", Material.WRITTEN_BOOK),
    BOOKSHELF("Bücherregal", Material.BOOKSHELF),
    BOW("Bogen", Material.BOW),
    BOWL("Schüssel", Material.BOWL),
    BREAD("Brot", Material.BREAD),
    BREWING_STAND("Braustand", Material.BREWING_STAND),
    BRICK("Ziegel", Material.BRICK),
    BRICK_SLAB("Ziegelstufe", Material.BRICK_SLAB),
    BRICK_STAIRS("Ziegeltreppe", Material.BRICK_STAIRS),
    BRICK_WALL("Ziegelsteinmauer", Material.BRICK_WALL),
    BRICKS("Ziegelsteine", Material.BRICKS),
    BRUSH("Pinsel", Material.BRUSH),
    BUCKET("Eimer", Material.BUCKET),
    BUCKET_AXOLOTL("Axolotleimer", Material.AXOLOTL_BUCKET),
    BUCKET_COD("Kabeljaueimer", Material.COD_BUCKET),
    BUCKET_LAVA("Lavaeimer", Material.LAVA_BUCKET),
    BUCKET_MILK("Milcheimer", Material.MILK_BUCKET),
    BUCKET_POWDER_SNOW("Pulverschneeeimer", Material.POWDER_SNOW_BUCKET),
    BUCKET_PUFFERFISH("Kugelfischeimer", Material.PUFFERFISH_BUCKET),
    BUCKET_SALMON("Lachseimer", Material.SALMON_BUCKET),
    BUCKET_TADPOLE("Kaulquappeneimer", Material.TADPOLE_BUCKET),
    BUCKET_TROPICAL_FISH("Tropenfischeimer", Material.TROPICAL_FISH_BUCKET),
    BUCKET_WATER("Wassereimer", Material.WATER_BUCKET),
    CACTUS("Kaktus", Material.CACTUS),
    CAKE("Kuchen", Material.CAKE),
    CALCITE("Kalzit", Material.CALCITE),
    CALIBRATED_SCULK_SENSOR("Kalibrierter Sculk-Sensor", Material.CALIBRATED_SCULK_SENSOR),
    CAMPFIRE("Lagerfeuer", Material.CAMPFIRE),
    CANDLE("Kerze", Material.CANDLE),
    CANDLE_BLACK("Schwarze Kerze", Material.BLACK_CANDLE),
    CANDLE_BLUE("Blaue Kerze", Material.BLUE_CANDLE),
    CANDLE_BROWN("Braune Kerze", Material.BROWN_CANDLE),
    CANDLE_CYAN("Türkise Kerze", Material.CYAN_CANDLE),
    CANDLE_GRAY("Graue Kerze", Material.GRAY_CANDLE),
    CANDLE_GREEN("Grüne Kerze", Material.GREEN_CANDLE),
    CANDLE_LIGHT_BLUE("Hellblaue Kerze", Material.LIGHT_BLUE_CANDLE),
    CANDLE_LIGHT_GRAY("Hellgraue Kerze", Material.LIGHT_GRAY_CANDLE),
    CANDLE_LIME("Hellgrüne Kerze", Material.LIME_CANDLE),
    CANDLE_MAGENTA("Magenta Kerze", Material.MAGENTA_CANDLE),
    CANDLE_ORANGE("Orange Kerze", Material.ORANGE_CANDLE),
    CANDLE_PINK("Rosa Kerze", Material.PINK_CANDLE),
    CANDLE_PURPLE("Violette Kerze", Material.PURPLE_CANDLE),
    CANDLE_RED("Rote Kerze", Material.RED_CANDLE),
    CANDLE_YELLOW("Gelbe Kerze", Material.YELLOW_CANDLE),
    CARPET_BLACK("Schwarzer Teppich", Material.BLACK_CARPET),
    CARPET_BLUE("Blauer Teppich", Material.BLUE_CARPET),
    CARPET_BROWN("Brauner Teppich", Material.BROWN_CARPET),
    CARPET_CYAN("Türkiser Teppich", Material.CYAN_CARPET),
    CARPET_GRAY("Grauer Teppich", Material.GRAY_CARPET),
    CARPET_GREEN("Grüner Teppich", Material.GREEN_CARPET),
    CARPET_LIGHT_BLUE("Hellblauer Teppich", Material.LIGHT_BLUE_CARPET),
    CARPET_LIGHT_GRAY("Hellgrauer Teppich", Material.LIGHT_GRAY_CARPET),
    CARPET_LIME("Hellgrüner Teppich", Material.LIME_CARPET),
    CARPET_MAGENTA("Magenta Teppich", Material.MAGENTA_CARPET),
    CARPET_ORANGE("Oranger Teppich", Material.ORANGE_CARPET),
    CARPET_PINK("Rosa Teppich", Material.PINK_CARPET),
    CARPET_PURPLE("Violetter Teppich", Material.PURPLE_CARPET),
    CARPET_RED("Roter Teppich", Material.RED_CARPET),
    CARPET_WHITE("Weißer Teppich", Material.WHITE_CARPET),
    CARPET_YELLOW("Gelber Teppich", Material.YELLOW_CARPET),
    CARROT("Karotte", Material.CARROT),
    CARROT_GOLDEN("Goldene Karotte", Material.GOLDEN_CARROT),
    CARROT_ON_A_STICK("Karottenrute", Material.CARROT_ON_A_STICK),
    CARTOGRAPHY_TABLE("Kartentisch", Material.CARTOGRAPHY_TABLE),
    CARVED_PUMPKIN("Geschnitzter Kürbis", Material.CARVED_PUMPKIN),
    CAULDRON("Kessel", Material.CAULDRON),
    CHAIN("Kette", Material.CHAIN),
    CHAINMAIL_BOOTS("Kettenstiefel", Material.CHAINMAIL_BOOTS),
    CHAINMAIL_CHESTPLATE("Kettenhemd", Material.CHAINMAIL_CHESTPLATE),
    CHAINMAIL_HELMET("Kettenhaube", Material.CHAINMAIL_HELMET),
    CHAINMAIL_LEGGINGS("Kettenhose", Material.CHAINMAIL_LEGGINGS),
    CHARCOAL("Holzkohle", Material.CHARCOAL),
    CHERRY_BOAT("Kirschholzboot", Material.CHERRY_BOAT),
    CHERRY_BUTTON("Kirschholzknopf", Material.CHERRY_BUTTON),
    CHERRY_CHEST_BOAT("Kirschholztruhenboot", Material.CHERRY_CHEST_BOAT),
    CHERRY_DOOR("Kirschholztür", Material.CHERRY_DOOR),
    CHERRY_FENCE("Kirschholzzaun", Material.CHERRY_FENCE),
    CHERRY_FENCE_GATE("Kirschholzzauntor", Material.CHERRY_FENCE_GATE),
    CHERRY_HANGING_SIGN("Kirschholzhängeschild", Material.CHERRY_HANGING_SIGN),
    CHERRY_LEAVES("Kirschlaub", Material.CHERRY_LEAVES),
    CHERRY_LOG("Kirschstamm", Material.CHERRY_LOG),
    CHERRY_LOG_STRIPPED("Entrindeter Kirschstamm", Material.STRIPPED_CHERRY_LOG),
    CHERRY_PLANKS("Kirschholzbretter", Material.CHERRY_PLANKS),
    CHERRY_PRESSURE_PLATE("Kirschholzdruckplatte", Material.CHERRY_PRESSURE_PLATE),
    CHERRY_SAPLING("Kirschsetzling", Material.CHERRY_SAPLING),
    CHERRY_SIGN("Kirschholzschild", Material.CHERRY_SIGN),
    CHERRY_SLAB("Kirschholzstufe", Material.CHERRY_SLAB),
    CHERRY_STAIRS("Kirschholztreppe", Material.CHERRY_STAIRS),
    CHERRY_TRAPDOOR("Kirschholzfalltür", Material.CHERRY_TRAPDOOR),
    CHERRY_WOOD("Kirschholz", Material.CHERRY_WOOD),
    CHERRY_WOOD_STRIPPED("Entrindetes Kirschholz", Material.STRIPPED_CHERRY_WOOD),
    CHEST("Truhe", Material.CHEST),
    CHICKEN("Rohes Hühnchen", Material.CHICKEN),
    CHICKEN_COOKED("Gebratenes Hühnchen", Material.COOKED_CHICKEN),
    CHISELED_BOOKSHELF("Gearbeitetes Bücherregal", Material.CHISELED_BOOKSHELF),
    CHISELED_DEEPSLATE("Gemeißelter Tiefenschiefer", Material.CHISELED_DEEPSLATE),
    CHISELED_NETHER_BRICKS("Gemeißelte Netherziegel", Material.CHISELED_NETHER_BRICKS),
    CHISELED_POLISHED_BLACKSTONE("Gemeißelter polierter Schwarzstein", Material.CHISELED_POLISHED_BLACKSTONE),
    CHISELED_QUARTZ_BLOCK("Gemeißelter Quarzblock", Material.CHISELED_QUARTZ_BLOCK),
    CHISELED_RED_SANDSTONE("Gemeißelter roter Sandstein", Material.CHISELED_RED_SANDSTONE),
    CHISELED_SANDSTONE("Gemeißelter Sandstein", Material.CHISELED_SANDSTONE),
    CHISELED_STONE_BRICKS("Gemeißelte Steinziegel", Material.CHISELED_STONE_BRICKS),
    CHORUS_FLOWER("Chorusblüte", Material.CHORUS_FLOWER),
    CHORUS_FRUIT("Chorusfrucht", Material.CHORUS_FRUIT),
    CLAY("Ton", Material.CLAY),
    CLAY_BALL("Tonklumpen", Material.CLAY_BALL),
    CLOCK("Uhr", Material.CLOCK),
    COAL("Kohle", Material.COAL),
    COAL_BLOCK("Kohleblock", Material.COAL_BLOCK),
    COAL_ORE("Steinkohle", Material.COAL_ORE),
    COAL_ORE_DEEPSLATE("Tiefenschiefer-Steinkohle", Material.DEEPSLATE_COAL_ORE),
    COARSE_DIRT("Grobe Erde", Material.COARSE_DIRT),
    COBBLED_DEEPSLATE("Bruchtiefenschiefer", Material.COBBLED_DEEPSLATE),
    COBBLED_DEEPSLATE_SLAB("Bruchtiefenschieferstufe", Material.COBBLED_DEEPSLATE_SLAB),
    COBBLED_DEEPSLATE_STAIRS("Bruchtiefenschiefertreppe", Material.COBBLED_DEEPSLATE_STAIRS),
    COBBLED_DEEPSLATE_WALL("Bruchtiefenschiefermauer", Material.COBBLED_DEEPSLATE_WALL),
    COBBLESTONE("Bruchstein", Material.COBBLESTONE),
    COBBLESTONE_SLAB("Bruchsteinstufe", Material.COBBLESTONE_SLAB),
    COBBLESTONE_STAIRS("Bruchsteintreppe", Material.COBBLESTONE_STAIRS),
    COBBLESTONE_WALL("Bruchsteinmauer", Material.COBBLESTONE_WALL),
    COBWEB("Spinnennetz", Material.COBWEB),
    COCOA_BEANS("Kakaobohnen", Material.COCOA_BEANS),
    COD("Roher Kabeljau", Material.COD),
    COD_COOKED("Gebratener Kabeljau", Material.COOKED_COD),
    COMPARATOR("Redstone-Komparator", Material.COMPARATOR),
    COMPASS("Kompass", Material.COMPASS),
    COMPOSTER("Komposter", Material.COMPOSTER),
    CONCRETE_BLACK("Schwarzer Beton", Material.BLACK_CONCRETE),
    CONCRETE_BLUE("Blauer Beton", Material.BLUE_CONCRETE),
    CONCRETE_BROWN("Brauner Beton", Material.BROWN_CONCRETE),
    CONCRETE_CYAN("Türkiser Beton", Material.CYAN_CONCRETE),
    CONCRETE_GRAY("Grauer Beton", Material.GRAY_CONCRETE),
    CONCRETE_GREEN("Grüner Beton", Material.GREEN_CONCRETE),
    CONCRETE_LIGHT_BLUE("Hellblauer Beton", Material.LIGHT_BLUE_CONCRETE),
    CONCRETE_LIGHT_GRAY("Hellgrauer Beton", Material.LIGHT_GRAY_CONCRETE),
    CONCRETE_LIME("Hellgrüner Beton", Material.LIME_CONCRETE),
    CONCRETE_MAGENTA("Magenta Beton", Material.MAGENTA_CONCRETE),
    CONCRETE_ORANGE("Oranger Beton", Material.ORANGE_CONCRETE),
    CONCRETE_PINK("Rosa Beton", Material.PINK_CONCRETE),
    CONCRETE_POWDER_BLACK("Schwarzer Trockenbeton", Material.BLACK_CONCRETE_POWDER),
    CONCRETE_POWDER_BLUE("Blauer Trockenbeton", Material.BLUE_CONCRETE_POWDER),
    CONCRETE_POWDER_BROWN("Brauner Trockenbeton", Material.BROWN_CONCRETE_POWDER),
    CONCRETE_POWDER_CYAN("Türkiser Trockenbeton", Material.CYAN_CONCRETE_POWDER),
    CONCRETE_POWDER_GRAY("Grauer Trockenbeton", Material.GRAY_CONCRETE_POWDER),
    CONCRETE_POWDER_GREEN("Grüner Trockenbeton", Material.GREEN_CONCRETE_POWDER),
    CONCRETE_POWDER_LIGHT_BLUE("Hellblauer Trockenbeton", Material.LIGHT_BLUE_CONCRETE_POWDER),
    CONCRETE_POWDER_LIGHT_GRAY("Hellgrauer Trockenbeton", Material.LIGHT_GRAY_CONCRETE_POWDER),
    CONCRETE_POWDER_LIME("Hellgrüner Trockenbeton", Material.LIME_CONCRETE_POWDER),
    CONCRETE_POWDER_MAGENTA("Magenta Trockenbeton", Material.MAGENTA_CONCRETE_POWDER),
    CONCRETE_POWDER_ORANGE("Oranger Trockenbeton", Material.ORANGE_CONCRETE_POWDER),
    CONCRETE_POWDER_PINK("Rosa Trockenbeton", Material.PINK_CONCRETE_POWDER),
    CONCRETE_POWDER_PURPLE("Violetter Trockenbeton", Material.PURPLE_CONCRETE_POWDER),
    CONCRETE_POWDER_RED("Roter Trockenbeton", Material.RED_CONCRETE_POWDER),
    CONCRETE_POWDER_WHITE("Weißer Trockenbeton", Material.WHITE_CONCRETE_POWDER),
    CONCRETE_POWDER_YELLOW("Gelber Trockenbeton", Material.YELLOW_CONCRETE_POWDER),
    CONCRETE_PURPLE("Violetter Beton", Material.PURPLE_CONCRETE),
    CONCRETE_RED("Roter Beton", Material.RED_CONCRETE),
    CONCRETE_WHITE("Weißer Beton", Material.WHITE_CONCRETE),
    CONCRETE_YELLOW("Gelber Beton", Material.YELLOW_CONCRETE),
    CONDUIT("Aquisator", Material.CONDUIT),
    COOKIE("Keks", Material.COOKIE),
    COPPER_BLOCK("Kupferblock", Material.COPPER_BLOCK),
    COPPER_BLOCK_RAW("Rohkupferblock", Material.RAW_COPPER_BLOCK),
    COPPER_BLOCK_WAXED("Gewachster Kupferblock", Material.WAXED_COPPER_BLOCK),
    COPPER_CUT("Geschnittener Kupferblock", Material.CUT_COPPER),
    COPPER_CUT_EXPOSED("Angelaufener geschnittener Kupferblock", Material.EXPOSED_CUT_COPPER),
    COPPER_CUT_EXPOSED_WAXED("Gewachster angelaufener geschnittener Kupferblock", Material.WAXED_EXPOSED_CUT_COPPER),
    COPPER_CUT_SLAB("Geschnittene Kupferstufe", Material.CUT_COPPER_SLAB),
    COPPER_CUT_SLAB_EXPOSED("Angelaufene geschnittene Kupferstufe", Material.EXPOSED_CUT_COPPER_SLAB),
    COPPER_CUT_SLAB_EXPOSED_WAXED("Gewachste angelaufene geschnittene Kupferstufe", Material.WAXED_EXPOSED_CUT_COPPER_SLAB),
    COPPER_CUT_SLAB_WAXED("Gewachste geschnittene Kupferstufe", Material.WAXED_CUT_COPPER_SLAB),
    COPPER_CUT_SLAB_WEATHERED("Verwitterte geschnittene Kupferstufe", Material.WEATHERED_CUT_COPPER_SLAB),
    COPPER_CUT_SLAB_WEATHERED_WAXED("Gewachste verwitterte geschnittene Kupferstufe", Material.WAXED_WEATHERED_CUT_COPPER_SLAB),
    COPPER_CUT_STAIRS("Geschnittene Kupfertreppe", Material.CUT_COPPER_STAIRS),
    COPPER_CUT_STAIRS_EXPOSED("Angelaufene geschnittene Kupfertreppe", Material.EXPOSED_CUT_COPPER_STAIRS),
    COPPER_CUT_STAIRS_EXPOSED_WAXED("Gewachste angelaufene geschnittene Kupfertreppe", Material.WAXED_EXPOSED_CUT_COPPER_STAIRS),
    COPPER_CUT_STAIRS_WAXED("Gewachste geschnittene Kupfertreppe", Material.WAXED_CUT_COPPER_STAIRS),
    COPPER_CUT_STAIRS_WEATHERED("Verwitterte geschnittene Kupfertreppe", Material.WEATHERED_CUT_COPPER_STAIRS),
    COPPER_CUT_STAIRS_WEATHERED_WAXED("Gewachste verwitterte geschnittene Kupfertreppe", Material.WAXED_WEATHERED_CUT_COPPER_STAIRS),
    COPPER_CUT_WAXED("Gewachster geschnittener Kupferblock", Material.WAXED_CUT_COPPER),
    COPPER_CUT_WEATHERED("Verwitterter geschnittener Kupferblock", Material.WEATHERED_CUT_COPPER),
    COPPER_CUT_WEATHERED_WAXED("Gewachster verwitterter geschnittener Kupferblock", Material.WAXED_WEATHERED_CUT_COPPER),
    COPPER_EXPOSED("Angelaufener Kupferblock", Material.EXPOSED_COPPER),
    COPPER_EXPOSED_WAXED("Gewachster angelaufener Kupferblock", Material.WAXED_EXPOSED_COPPER),
    COPPER_INGOT("Kupferbarren", Material.COPPER_INGOT),
    COPPER_ORE("Kupfererz", Material.COPPER_ORE),
    COPPER_ORE_DEEPSLATE("Tiefenschiefer-Kupfererz", Material.DEEPSLATE_COPPER_ORE),
    COPPER_OXIDIZED("Oxidierter Kupferblock", Material.OXIDIZED_COPPER),
    COPPER_OXIDIZED_WAXED("Gewachster oxidierter Kupferblock", Material.WAXED_OXIDIZED_COPPER),
    COPPER_RAW("Rohkupfer", Material.RAW_COPPER),
    COPPER_WEATHERED("Verwitterter Kupferblock", Material.WEATHERED_COPPER),
    COPPER_WEATHERED_WAXED("Gewachster verwitterter Kupferblock", Material.WAXED_WEATHERED_COPPER),
    CORAL_BRAIN("Hirnkoralle", Material.BRAIN_CORAL),
    CORAL_BRAIN_BLOCK("Hirnkorallenblock", Material.BRAIN_CORAL_BLOCK),
    CORAL_BRAIN_BLOCK_DEAD("Abgestorbener Hirnkorallenblock", Material.DEAD_BRAIN_CORAL_BLOCK),
    CORAL_BRAIN_DEAD("Abgestorbene Hirnkoralle", Material.DEAD_BRAIN_CORAL),
    CORAL_BRAIN_FAN("Hirnkorallenfächer", Material.BRAIN_CORAL_FAN),
    CORAL_BRAIN_FAN_DEAD("Abgestorbener Hirnkorallenfächer", Material.DEAD_BRAIN_CORAL_FAN),
    CORAL_BUBBLE("Blasenkoralle", Material.BUBBLE_CORAL),
    CORAL_BUBBLE_BLOCK("Blasenkorallenblock", Material.BUBBLE_CORAL_BLOCK),
    CORAL_BUBBLE_BLOCK_DEAD("Abgestorbener Blasenkorallenblock", Material.DEAD_BUBBLE_CORAL_BLOCK),
    CORAL_BUBBLE_DEAD("Abgestorbene Blasenkoralle", Material.DEAD_BUBBLE_CORAL),
    CORAL_BUBBLE_FAN("Blasenkorallenfächer", Material.BUBBLE_CORAL_FAN),
    CORAL_BUBBLE_FAN_DEAD("Abgestorbener Blasenkorallenfächer", Material.DEAD_BUBBLE_CORAL_FAN),
    CORAL_FIRE("Feuerkoralle", Material.FIRE_CORAL),
    CORAL_FIRE_BLOCK("Feuerkorallenblock", Material.FIRE_CORAL_BLOCK),
    CORAL_FIRE_BLOCK_DEAD("Abgestorbener Feuerkorallenblock", Material.DEAD_FIRE_CORAL_BLOCK),
    CORAL_FIRE_DEAD("Abgestorbene Feuerkoralle", Material.DEAD_FIRE_CORAL),
    CORAL_FIRE_FAN("Feuerkorallenfächer", Material.FIRE_CORAL_FAN),
    CORAL_FIRE_FAN_DEAD("Abgestorbener Feuerkorallenfächer", Material.DEAD_FIRE_CORAL_FAN),
    CORAL_HORN("Geweihkoralle", Material.HORN_CORAL),
    CORAL_HORN_BLOCK("Geweihkorallenblock", Material.HORN_CORAL_BLOCK),
    CORAL_HORN_BLOCK_DEAD("Abgestorbener Geweihkorallenblock", Material.DEAD_HORN_CORAL_BLOCK),
    CORAL_HORN_DEAD("Abgestorbene Geweihkoralle", Material.DEAD_HORN_CORAL),
    CORAL_HORN_FAN("Geweihkorallenfächer", Material.HORN_CORAL_FAN),
    CORAL_HORN_FAN_DEAD("Abgestorbener Geweihkorallenfächer", Material.DEAD_HORN_CORAL_FAN),
    CORAL_TUBE("Orgelkoralle", Material.TUBE_CORAL),
    CORAL_TUBE_BLOCK("Orgelkorallenblock", Material.TUBE_CORAL_BLOCK),
    CORAL_TUBE_BLOCK_DEAD("Abgestorbener Orgelkorallenblock", Material.DEAD_TUBE_CORAL_BLOCK),
    CORAL_TUBE_DEAD("Abgestorbene Orgelkoralle", Material.DEAD_TUBE_CORAL),
    CORAL_TUBE_FAN("Orgelkorallenfächer", Material.TUBE_CORAL_FAN),
    CORAL_TUBE_FAN_DEAD("Abgestorbener Orgelkorallenfächer", Material.DEAD_TUBE_CORAL_FAN),
    CORNFLOWER("Kornblume", Material.CORNFLOWER),
    CRACKED_DEEPSLATE_BRICKS("Rissige Tiefenschieferziegel", Material.CRACKED_DEEPSLATE_BRICKS),
    CRACKED_DEEPSLATE_TILES("Rissige Tiefenschieferfliesen", Material.CRACKED_DEEPSLATE_TILES),
    CRACKED_NETHER_BRICKS("Rissige Netherziegel", Material.CRACKED_NETHER_BRICKS),
    CRACKED_POLISHED_BLACKSTONE_BRICKS("Rissige polierte Schwarzsteinziegel", Material.CRACKED_POLISHED_BLACKSTONE_BRICKS),
    CRACKED_STONE_BRICKS("Rissige Steinziegel", Material.CRACKED_STONE_BRICKS),
    CRAFTING_TABLE("Werkbank", Material.CRAFTING_TABLE),
    CRIMSON_BUTTON("Karmesinknopf", Material.CRIMSON_BUTTON),
    CRIMSON_DOOR("Karmesintür", Material.CRIMSON_DOOR),
    CRIMSON_FENCE("Karmesinzaun", Material.CRIMSON_FENCE),
    CRIMSON_FENCE_GATE("Karmesinzauntor", Material.CRIMSON_FENCE_GATE),
    CRIMSON_FUNGUS("Karmesinpilz", Material.CRIMSON_FUNGUS),
    CRIMSON_HANGING_SIGN("Karmesinhängeschild", Material.CRIMSON_HANGING_SIGN),
    CRIMSON_HYPHAE("Karmesinhyphen", Material.CRIMSON_HYPHAE),
    CRIMSON_HYPHAE_STRIPPED("Geschälte Karmesinhyphen", Material.STRIPPED_CRIMSON_HYPHAE),
    CRIMSON_NYLIUM("Karmesin-Nezel", Material.CRIMSON_NYLIUM),
    CRIMSON_PLANKS("Karmesinbretter", Material.CRIMSON_PLANKS),
    CRIMSON_PRESSURE_PLATE("Karmesindruckplatte", Material.CRIMSON_PRESSURE_PLATE),
    CRIMSON_ROOTS("Karmesinwurzeln", Material.CRIMSON_ROOTS),
    CRIMSON_SIGN("Karmesinschild", Material.CRIMSON_SIGN),
    CRIMSON_SLAB("Karmesinstufe", Material.CRIMSON_SLAB),
    CRIMSON_STAIRS("Karmesintreppe", Material.CRIMSON_STAIRS),
    CRIMSON_STEM("Karmesinstiel", Material.CRIMSON_STEM),
    CRIMSON_STEM_STRIPPED("Geschälter Karmesinstiel", Material.STRIPPED_CRIMSON_STEM),
    CRIMSON_TRAPDOOR("Karmesinfalltür", Material.CRIMSON_TRAPDOOR),
    CROSSBOW("Armbrust", Material.CROSSBOW),
    CRYING_OBSIDIAN("Weinender Obsidian", Material.CRYING_OBSIDIAN),
    CUPPER_CUT_OXIDIZED("Oxidierter geschnittener Kupferblock", Material.OXIDIZED_CUT_COPPER),
    CUPPER_CUT_OXIDIZED_WAXED("Gewachster oxidierter geschnittener Kupferblock", Material.WAXED_OXIDIZED_CUT_COPPER),
    CUPPER_CUT_SLAB_OXIDIZED("Oxidierte geschnittene Kupferstufe", Material.OXIDIZED_CUT_COPPER_SLAB),
    CUPPER_CUT_SLAB_OXIDIZED_WAXED("Gewachste oxidierte geschnittene Kupferstufe", Material.WAXED_OXIDIZED_CUT_COPPER_SLAB),
    CUPPER_CUT_STAIRS_OXIDIZED("Oxidierte geschnittene Kupfertreppe", Material.OXIDIZED_CUT_COPPER_STAIRS),
    CUPPER_CUT_STAIRS_OXIDIZED_WAXED("Gewachste oxidierte geschnittene Kupfertreppe", Material.WAXED_OXIDIZED_CUT_COPPER_STAIRS),
    CUT_RED_SANDSTONE("Geschnittener roter Sandstein", Material.CUT_RED_SANDSTONE),
    CUT_RED_SANDSTONE_SLAB("Geschnittene rote Sandsteinstufe", Material.CUT_RED_SANDSTONE_SLAB),
    CUT_SANDSTONE("Geschnittener Sandstein", Material.CUT_SANDSTONE),
    CUT_SANDSTONE_SLAB("Geschnittene Sandsteinstufe", Material.CUT_SANDSTONE_SLAB),
    DANDELION("Löwenzahn", Material.DANDELION),
    DARK_OAK_BOAT("Schwarzeichenboot", Material.DARK_OAK_BOAT),
    DARK_OAK_BUTTON("Schwarzeichenknopf", Material.DARK_OAK_BUTTON),
    DARK_OAK_CHEST_BOAT("Schwarzeichentruhenboot", Material.DARK_OAK_CHEST_BOAT),
    DARK_OAK_DOOR("Schwarzeichentür", Material.DARK_OAK_DOOR),
    DARK_OAK_FENCE("Schwarzeichenzaun", Material.DARK_OAK_FENCE),
    DARK_OAK_FENCE_GATE("Schwarzeichenzauntor", Material.DARK_OAK_FENCE_GATE),
    DARK_OAK_HANGING_SIGN("Schwarzeichenhängeschild", Material.DARK_OAK_HANGING_SIGN),
    DARK_OAK_LEAVES("Schwarzeichenlaub", Material.DARK_OAK_LEAVES),
    DARK_OAK_LOG("Schwarzeichenstamm", Material.DARK_OAK_LOG),
    DARK_OAK_LOG_STRIPPED("Entrindeter Schwarzeichenstamm", Material.STRIPPED_DARK_OAK_LOG),
    DARK_OAK_PLANKS("Schwarzeichenbretter", Material.DARK_OAK_PLANKS),
    DARK_OAK_PRESSURE_PLATE("Schwarzeichendruckplatte", Material.DARK_OAK_PRESSURE_PLATE),
    DARK_OAK_SAPLING("Schwarzeichensetzling", Material.DARK_OAK_SAPLING),
    DARK_OAK_SIGN("Schwarzeichenschild", Material.DARK_OAK_SIGN),
    DARK_OAK_SLAB("Schwarzeichenstufe", Material.DARK_OAK_SLAB),
    DARK_OAK_STAIRS("Schwarzeichentreppe", Material.DARK_OAK_STAIRS),
    DARK_OAK_TRAPDOOR("Schwarzeichenfalltür", Material.DARK_OAK_TRAPDOOR),
    DARK_OAK_WOOD("Schwarzeichenholz", Material.DARK_OAK_WOOD),
    DARK_OAK_WOOD_STRIPPED("Entrindetes Schwazeichenholz", Material.STRIPPED_DARK_OAK_WOOD),
    DARK_PRISMARINE("Dunkler Prismarin", Material.DARK_PRISMARINE),
    DARK_PRISMARINE_SLAB("Dunkle Prismarinstufe", Material.DARK_PRISMARINE_SLAB),
    DARK_PRISMARINE_STAIRS("Dunkle Prismarintreppe", Material.DARK_PRISMARINE_STAIRS),
    DAYLIGHT_DETECTOR("Tageslichtsensor", Material.DAYLIGHT_DETECTOR),
    DEAD_BUSH("Toter Busch", Material.DEAD_BUSH),
    DECORATED_POT("Verzierter Krug", Material.DECORATED_POT),
    DEEPSLATE("Tiefenschiefer", Material.DEEPSLATE),
    DEEPSLATE_BRICK_SLAB("Tiefenschieferziegelstufe", Material.DEEPSLATE_BRICK_SLAB),
    DEEPSLATE_BRICK_STAIRS("Tiefenschieferziegeltreppe", Material.DEEPSLATE_BRICK_STAIRS),
    DEEPSLATE_BRICK_WALL("Tiefenschieferziegelmauer", Material.DEEPSLATE_BRICK_WALL),
    DEEPSLATE_BRICKS("Tiefenschieferziegel", Material.DEEPSLATE_BRICKS),
    DEEPSLATE_TILE_SLAB("Tiefenschieferfliesenstufe", Material.DEEPSLATE_TILE_SLAB),
    DEEPSLATE_TILE_STAIRS("Tiefenschieferfliesentreppe", Material.DEEPSLATE_TILE_STAIRS),
    DEEPSLATE_TILE_WALL("Tiefenschieferfliesenmauer", Material.DEEPSLATE_TILE_WALL),
    DEEPSLATE_TILES("Tiefenschieferfliesen", Material.DEEPSLATE_TILES),
    DIAMOND("Diamant", Material.DIAMOND),
    DIAMOND_AXE("Diamantaxt", Material.DIAMOND_AXE),
    DIAMOND_BLOCK("Diamantblock", Material.DIAMOND_BLOCK),
    DIAMOND_BOOTS("Diamantstiefel", Material.DIAMOND_BOOTS),
    DIAMOND_CHESTPLATE("Diamantharnisch", Material.DIAMOND_CHESTPLATE),
    DIAMOND_HELMET("Diamanthelm", Material.DIAMOND_HELMET),
    DIAMOND_HOE("Diamanthacke", Material.DIAMOND_HOE),
    DIAMOND_HORSE_ARMOR("Diamantener Rossharnisch", Material.DIAMOND_HORSE_ARMOR),
    DIAMOND_LEGGINGS("Diamantbeinschutz", Material.DIAMOND_LEGGINGS),
    DIAMOND_ORE("Diamanterz", Material.DIAMOND_ORE),
    DIAMOND_ORE_DEEPSLATE("Tiefenschiefer-Diamanterz", Material.DEEPSLATE_DIAMOND_ORE),
    DIAMOND_PICKAXE("Diamantspitzhacke", Material.DIAMOND_PICKAXE),
    DIAMOND_SHOVEL("Diamantschaufel", Material.DIAMOND_SHOVEL),
    DIAMOND_SWORD("Diamantschwert", Material.DIAMOND_SWORD),
    DIORITE("Diorit", Material.DIORITE),
    DIORITE_SLAB("Dioritstufe", Material.DIORITE_SLAB),
    DIORITE_STAIRS("Diorittreppe", Material.DIORITE_STAIRS),
    DIORITE_WALL("Dioritmauer", Material.DIORITE_WALL),
    DIRT("Erde", Material.DIRT),
    DIRT_PATH("Trampelpfad", Material.DIRT_PATH),
    DISC_11("Schallplatte - 11", Material.MUSIC_DISC_11),
    DISC_13("Schallplatte - 13", Material.MUSIC_DISC_13),
    DISC_5("Schallplatte - Samuel Aberg - 5", Material.MUSIC_DISC_5),
    DISC_BLOCKS("Schallplatte - blocks", Material.MUSIC_DISC_BLOCKS),
    DISC_CAT("Schallplatte - cat", Material.MUSIC_DISC_CAT),
    DISC_CHIRP("Schallplatte - chirp", Material.MUSIC_DISC_CHIRP),
    DISC_FAR("Schallplatte - far", Material.MUSIC_DISC_FAR),
    DISC_FRAGMENT("Plattenbruchstück", Material.DISC_FRAGMENT_5),
    DISC_MALL("Schallplatte - mall", Material.MUSIC_DISC_MALL),
    DISC_MELLOHI("Schallplatte - mellohi", Material.MUSIC_DISC_MELLOHI),
    DISC_OTHERSIDE("Schallplatte - Lena Raine - otherside", Material.MUSIC_DISC_OTHERSIDE),
    DISC_PIGSTEP("Schallplatte - Lena Raine - Pigstep", Material.MUSIC_DISC_PIGSTEP),
    DISC_RELIC("Schallplatte - Aaron Cherof - Relic", Material.MUSIC_DISC_RELIC),
    DISC_STAL("Schallplatte - stal", Material.MUSIC_DISC_STAL),
    DISC_STRAD("Schallplatte - strad", Material.MUSIC_DISC_STRAD),
    DISC_WAIT("Schallplatte - wait", Material.MUSIC_DISC_WAIT),
    DISC_WARD("Schallplatte - ward", Material.MUSIC_DISC_WARD),
    DISPENSER("Werfer", Material.DISPENSER),
    DRAGON_BREATH("Drachenatem", Material.DRAGON_BREATH),
    DRAGON_EGG("Drachenei", Material.DRAGON_EGG),
    DRAGON_HEAD("Drachenkopf", Material.DRAGON_HEAD),
    DRIED_KELP("Getrockneter Seetang", Material.DRIED_KELP),
    DRIED_KELP_BLOCK("Getrockneter Seetangblock", Material.DRIED_KELP_BLOCK),
    DRIPLEAF_BIG("Großes Tropfblatt", Material.BIG_DRIPLEAF),
    DRIPLEAF_SMALL("Kleines Tropfblatt", Material.SMALL_DRIPLEAF),
    DRIPSTONE_BLOCK("Tropfsteinblock", Material.DRIPSTONE_BLOCK),
    DROPPER("Spender", Material.DROPPER),
    DYE_BLACK("Schwarzer Farbstoff", Material.BLACK_DYE),
    DYE_BLUE("Blauer Farbstoff", Material.BLUE_DYE),
    DYE_BROWN("Brauner Farbstoff", Material.BROWN_DYE),
    DYE_CYAN("Türkiser Farbstoff", Material.CYAN_DYE),
    DYE_GRAY("Grauer Farbstoff", Material.GRAY_DYE),
    DYE_GREEN("Grüner Farbstoff", Material.GREEN_DYE),
    DYE_LIGHT_BLUE("Hellblauer Farbstoff", Material.LIGHT_BLUE_DYE),
    DYE_LIGHT_GRAY("Hellgrauer Farbstoff", Material.LIGHT_GRAY_DYE),
    DYE_LIME("Hellgrüner Farbstoff", Material.LIME_DYE),
    DYE_MAGNETA("Magenta Farbstoff", Material.MAGENTA_DYE),
    DYE_ORANGE("Oranger Farbstoff", Material.ORANGE_DYE),
    DYE_PINK("Rosa Farbstoff", Material.PINK_DYE),
    DYE_PURPLE("Violetter Farbstoff", Material.PURPLE_DYE),
    DYE_RED("Roter Farbstoff", Material.RED_DYE),
    DYE_WHITE("Weißer Farbstoff", Material.WHITE_DYE),
    DYE_YELLOW("Gelber Farbstoff", Material.YELLOW_DYE),
    ECHO_SHARD("Echoscherbe", Material.ECHO_SHARD),
    EGG("Ei", Material.EGG),
    ELYTRA("Elytren", Material.ELYTRA),
    EMERALD("Smaragd", Material.EMERALD),
    EMERALD_BLOCK("Smaragdblock", Material.EMERALD_BLOCK),
    EMERALD_ORE("Smaragderz", Material.EMERALD_ORE),
    EMERALD_ORE_DEEPSLATE("Tiefenschiefer-Smaragderz", Material.DEEPSLATE_EMERALD_ORE),
    ENCHANTING_TABLE("Zaubertisch", Material.ENCHANTING_TABLE),
    END_CRYSTAL("Enderkristall", Material.END_CRYSTAL),
    END_ROD("Endstab", Material.END_ROD),
    END_STONE("Endstein", Material.END_STONE),
    END_STONE_BRICK_SLAB("Endsteinziegelstufe", Material.END_STONE_BRICK_SLAB),
    END_STONE_BRICK_STAIRS("Endsteinziegeltreppe", Material.END_STONE_BRICK_STAIRS),
    END_STONE_BRICK_WALL("Endsteinziegelmauer", Material.END_STONE_BRICK_WALL),
    END_STONE_BRICKS("Endsteinziegel", Material.END_STONE_BRICKS),
    ENDER_CHEST("Endertruhe", Material.ENDER_CHEST),
    ENDER_EYE("Enderauge", Material.ENDER_EYE),
    ENDER_PEARL("Enderperle", Material.ENDER_PEARL),
    EXPERIENCE_BOTTLE("Erfahrungsfläschchen", Material.EXPERIENCE_BOTTLE),
    FEATHER("Feder", Material.FEATHER),
    FERMENTED_SPIDER_EYE("Fermentiertes Spinnenauge", Material.FERMENTED_SPIDER_EYE),
    FERN("Farn", Material.FERN),
    FERN_LARGE("Großer Farn", Material.LARGE_FERN),
    FIRE_CHARGE("Feuerkugel", Material.FIRE_CHARGE),
    FIREWORK_ROCKET("Feuerwerksrakete", Material.FIREWORK_ROCKET),
    FIREWORK_STAR("Feuerwerksstern", Material.FIREWORK_STAR),
    FISHING_ROD("Angel", Material.FISHING_ROD),
    FLETCHING_TABLE("Bognertisch", Material.FLETCHING_TABLE),
    FLINT("Feuerstein", Material.FLINT),
    FLINT_AND_STEEL("Feuerzeug", Material.FLINT_AND_STEEL),
    FLOWER_POT("Blumentopf", Material.FLOWER_POT),
    FLOWERING_AZALEA("Blühende Azalee", Material.FLOWERING_AZALEA),
    FLOWERING_AZALEA_LEAVES("Blühendes Azaleenlaub", Material.FLOWERING_AZALEA_LEAVES),
    FROGLIGHT_OCHRE("Ockernes Froschlicht", Material.OCHRE_FROGLIGHT),
    FROGLIGHT_PEARLESCENT("Perlmutternes Froschlicht", Material.PEARLESCENT_FROGLIGHT),
    FROGLIGHT_VERDANT("Junggrünes Froschlicht", Material.VERDANT_FROGLIGHT),
    FURNACE("Ofen", Material.FURNACE),
    GHAST_TEAR("Ghast-Träne", Material.GHAST_TEAR),
    GILDED_BLACKSTONE("Golddurchzogener Schwarzstein", Material.GILDED_BLACKSTONE),
    GLASS("Glas", Material.GLASS),
    GLASS_BOTTLE("Glasflasche", Material.GLASS_BOTTLE),
    GLASS_PANE("Glasscheibe", Material.GLASS_PANE),
    GLISTERING_MELON_SLICE("Glitzernde Melonenscheibe", Material.GLISTERING_MELON_SLICE),
    GLOW_BERRIES("Leuchtbeeren", Material.GLOW_BERRIES),
    GLOW_ITEM_FRAME("Leuchtrahmen", Material.GLOW_ITEM_FRAME),
    GLOW_LICHEN("Leuchtflechte", Material.GLOW_LICHEN),
    GLOWSTONE("Leuchtstein", Material.GLOWSTONE),
    GLOWSTONE_DUST("Leuchtsteinstaub", Material.GLOWSTONE_DUST),
    GOAT_HORN("Bockshorn", Material.GOAT_HORN),
    GOLD_BLOCK("Goldblock", Material.GOLD_BLOCK),
    GOLD_BLOCK_RAW("Rohgoldblock", Material.RAW_GOLD_BLOCK),
    GOLD_INGOT("Goldbarren", Material.GOLD_INGOT),
    GOLD_NUGGET("Goldklumpen", Material.GOLD_NUGGET),
    GOLD_ORE("Golderz", Material.GOLD_ORE),
    GOLD_ORE_DEEPSLATE("Tiefenschiefer-Golderz", Material.DEEPSLATE_GOLD_ORE),
    GOLD_RAW("Rohgold", Material.RAW_GOLD),
    GOLDEN_AXE("Goldaxt", Material.GOLDEN_AXE),
    GOLDEN_BOOTS("Goldstiefel", Material.GOLDEN_BOOTS),
    GOLDEN_CHESTPLATE("Goldharnisch", Material.GOLDEN_CHESTPLATE),
    GOLDEN_HELMET("Goldhelm", Material.GOLDEN_HELMET),
    GOLDEN_HOE("Goldhacke", Material.GOLDEN_HOE),
    GOLDEN_HORSE_ARMOR("Goldener Rossharnisch", Material.GOLDEN_HORSE_ARMOR),
    GOLDEN_LEGGINGS("Goldbeinschutz", Material.GOLDEN_LEGGINGS),
    GOLDEN_PICKAXE("Goldspitzhacke", Material.GOLDEN_PICKAXE),
    GOLDEN_SHOVEL("Goldschaufel", Material.GOLDEN_SHOVEL),
    GOLDEN_SWORD("Goldschwert", Material.GOLDEN_SWORD),
    GRANITE("Granit", Material.GRANITE),
    GRANITE_SLAB("Granitstufe", Material.GRANITE_SLAB),
    GRANITE_STAIRS("Granittreppe", Material.GRANITE_STAIRS),
    GRANITE_WALL("Granitmauer", Material.GRANITE_WALL),
    GRASS("Niedriges Gras", Material.SHORT_GRASS),
    GRASS_BLOCK("Grasblock", Material.GRASS_BLOCK),
    GRASS_TALL("Hohes Gras", Material.TALL_GRASS),
    GRAVEL("Kies", Material.GRAVEL),
    GRINDSTONE("Schleifstein", Material.GRINDSTONE),
    GUNPOWDER("Schwarzpulver", Material.GUNPOWDER),
    HANGING_ROOTS("Hängende Wurzeln", Material.HANGING_ROOTS),
    HAY_BALE("Strohballen", Material.HAY_BLOCK),
    HEAD_CREEPER("Creeperkopf", Material.CREEPER_HEAD),
    HEAD_PIGLIN("Piglinkopf", Material.PIGLIN_HEAD),
    HEAD_SKELETON("Skelettschädel", Material.SKELETON_SKULL),
    HEAD_WITHER_SKELETON("Wither-Skelettschädel", Material.WITHER_SKELETON_SKULL),
    HEAD_ZOMBIE("Zombiekopf", Material.ZOMBIE_HEAD),
    HEART_OF_THE_SEA("Herz des Meeres", Material.HEART_OF_THE_SEA),
    HEAVY_WEIGHTED_PRESSURE_PLATE("Grobwägeplatte", Material.HEAVY_WEIGHTED_PRESSURE_PLATE),
    HONEY_BLOCK("Honigblock", Material.HONEY_BLOCK),
    HONEY_BOTTLE("Honigflasche", Material.HONEY_BOTTLE),
    HONEYCOMB("Honigwabe", Material.HONEYCOMB),
    HONEYCOMB_BLOCK("Honigwabenblock", Material.HONEYCOMB_BLOCK),
    HOPPER("Trichter", Material.HOPPER),
    ICE("Eis", Material.ICE),
    ICE_BLUE("Blaueis", Material.BLUE_ICE),
    ICE_PACKED("Packeis", Material.PACKED_ICE),
    INK_SAC("Tintenbeutel", Material.INK_SAC),
    INK_SAC_GLOW("Leuchttintenbeutel", Material.GLOW_INK_SAC),
    IRON_AXE("Eisenaxt", Material.IRON_AXE),
    IRON_BARS("Eisengitter", Material.IRON_BARS),
    IRON_BLOCK("Eisenblock", Material.IRON_BLOCK),
    IRON_BLOCK_RAW("Roheisenblock", Material.RAW_IRON_BLOCK),
    IRON_BOOTS("Eisenstiefel", Material.IRON_BOOTS),
    IRON_CHESTPLATE("Eisenharnisch", Material.IRON_CHESTPLATE),
    IRON_DOOR("Eisentür", Material.IRON_DOOR),
    IRON_HELMET("Eisenhelm", Material.IRON_HELMET),
    IRON_HOE("Eisenhacke", Material.IRON_HOE),
    IRON_HORSE_ARMOR("Eiserner Rossharnisch", Material.IRON_HORSE_ARMOR),
    IRON_INGOT("Eisenbarren", Material.IRON_INGOT),
    IRON_LEGGINGS("Eisenbeinschutz", Material.IRON_LEGGINGS),
    IRON_NUGGET("Eisenklumpen", Material.IRON_NUGGET),
    IRON_ORE("Eisenerz", Material.IRON_ORE),
    IRON_ORE_DEEPSLATE("Tiefenschiefer-Eisenerz", Material.DEEPSLATE_IRON_ORE),
    IRON_PICKAXE("Eisenspitzhacke", Material.IRON_PICKAXE),
    IRON_RAW("Roheisen", Material.RAW_IRON),
    IRON_SHOVEL("Eisenschaufel", Material.IRON_SHOVEL),
    IRON_SWORD("Eisenschwert", Material.IRON_SWORD),
    IRON_TRAPDOOR("Eisenfalltür", Material.IRON_TRAPDOOR),
    ITEM_FRAME("Rahmen", Material.ITEM_FRAME),
    JACK_O_LANTERN("Kürbislaterne", Material.JACK_O_LANTERN),
    JUKEBOX("Plattenspieler", Material.JUKEBOX),
    JUNGLE_BOAT("Tropenholzboot", Material.JUNGLE_BOAT),
    JUNGLE_BUTTON("Tropenholzknopf", Material.JUNGLE_BUTTON),
    JUNGLE_CHEST_BOAT("Tropenholztruhenboot", Material.JUNGLE_CHEST_BOAT),
    JUNGLE_DOOR("Tropenholztür", Material.JUNGLE_DOOR),
    JUNGLE_FENCE("Tropenholzzaun", Material.JUNGLE_FENCE),
    JUNGLE_FENCE_GATE("Tropenholzzauntor", Material.JUNGLE_FENCE_GATE),
    JUNGLE_HANGING_SIGN("Tropenholzhängeschild", Material.JUNGLE_HANGING_SIGN),
    JUNGLE_LEAVES("Tropenbaumlaub", Material.JUNGLE_LEAVES),
    JUNGLE_LOG("Tropenbaumstamm", Material.JUNGLE_LOG),
    JUNGLE_LOG_STRIPPED("Entrindeter Tropenbaumstamm", Material.STRIPPED_JUNGLE_LOG),
    JUNGLE_PLANKS("Tropenholzbretter", Material.JUNGLE_PLANKS),
    JUNGLE_PRESSURE_PLATE("Tropenholzdruckplatte", Material.JUNGLE_PRESSURE_PLATE),
    JUNGLE_SAPLING("Tropenbaumsetzling", Material.JUNGLE_SAPLING),
    JUNGLE_SIGN("Tropenholzschild", Material.JUNGLE_SIGN),
    JUNGLE_SLAB("Tropenholzstufe", Material.JUNGLE_SLAB),
    JUNGLE_STAIRS("Tropenholztreppe", Material.JUNGLE_STAIRS),
    JUNGLE_TRAPDOOR("Tropenholzfalltür", Material.JUNGLE_TRAPDOOR),
    JUNGLE_WOOD("Tropenholz", Material.JUNGLE_WOOD),
    JUNGLE_WOOD_STRIPPED("Entrindetes Tropenholz", Material.STRIPPED_JUNGLE_WOOD),
    KELP("Seetang", Material.KELP),
    LADDER("Leiter", Material.LADDER),
    LANTERN("Laterne", Material.LANTERN),
    LAPIS("Lapislazuli", Material.LAPIS_LAZULI),
    LAPIS_BLOCK("Lapislazuliblock", Material.LAPIS_BLOCK),
    LAPIS_ORE("Lapislazulierz", Material.LAPIS_ORE),
    LAPIS_ORE_DEEPSLATE("Tiefenschiefer-Lapislazulierz", Material.DEEPSLATE_LAPIS_ORE),
    LEAD("Leine", Material.LEAD),
    LEATHER("Leder", Material.LEATHER),
    LEATHER_BOOTS("Lederstiefel", Material.LEATHER_BOOTS),
    LEATHER_CHESTPLATE("Lederjacke", Material.LEATHER_CHESTPLATE),
    LEATHER_HELMET("Lederkappe", Material.LEATHER_HELMET),
    LEATHER_HORSE_ARMOR("Lederner Rossharnisch", Material.LEATHER_HORSE_ARMOR),
    LEATHER_LEGGINGS("Lederhose", Material.LEATHER_LEGGINGS),
    LECTERN("Lesepult", Material.LECTERN),
    LEVER("Hebel", Material.LEVER),
    LIGHT_WEIGHTED_PRESSURE_PLATE("Feinwägeplatte", Material.LIGHT_WEIGHTED_PRESSURE_PLATE),
    LIGHTNING_ROD("Blitzableiter", Material.LIGHTNING_ROD),
    LILAC("Flieder", Material.LILAC),
    LILY_OF_THE_VALLEY("Maiglöckchen", Material.LILY_OF_THE_VALLEY),
    LILY_PAD("Seerosenblatt", Material.LILY_PAD),
    LODESTONE("Leitstein", Material.LODESTONE),
    LOOM("Webstuhl", Material.LOOM),
    MAGMA_BLOCK("Magmablock", Material.MAGMA_BLOCK),
    MAGMA_CREAM("Magmacreme", Material.MAGMA_CREAM),
    MANGROVE_BOAT("Mangrovenholzboot", Material.MANGROVE_BOAT),
    MANGROVE_BUTTON("Mangrovenholzknopf", Material.MANGROVE_BUTTON),
    MANGROVE_CHEST_BOAT("Mangrovenholztruhenboot", Material.MANGROVE_CHEST_BOAT),
    MANGROVE_DOOR("Mangrovenholztür", Material.MANGROVE_DOOR),
    MANGROVE_FENCE("Mangrovenholzzaun", Material.MANGROVE_FENCE),
    MANGROVE_FENCE_GATE("Mangrovenholzzauntor", Material.MANGROVE_FENCE_GATE),
    MANGROVE_HANGING_SIGN("Mangrovenholzhängeschild", Material.MANGROVE_HANGING_SIGN),
    MANGROVE_LEAVES("Mangrovenlaub", Material.MANGROVE_LEAVES),
    MANGROVE_LOG("Mangrovenstamm", Material.MANGROVE_LOG),
    MANGROVE_LOG_STRIPPED("Entrindeter Mangrovenstamm", Material.STRIPPED_MANGROVE_LOG),
    MANGROVE_PLANKS("Mangrovenholzbretter", Material.MANGROVE_PLANKS),
    MANGROVE_PRESSURE_PLATE("Mangrovenholzdruckplatte", Material.MANGROVE_PRESSURE_PLATE),
    MANGROVE_PROPAGULE("Mangroven-Keimling", Material.MANGROVE_PROPAGULE),
    MANGROVE_ROOTS("Mangrovenwurzeln", Material.MANGROVE_ROOTS),
    MANGROVE_SIGN("Mangrovenholzschild", Material.MANGROVE_SIGN),
    MANGROVE_SLAB("Mangrovenholzstufe", Material.MANGROVE_SLAB),
    MANGROVE_STAIRS("Mangrovenholztreppe", Material.MANGROVE_STAIRS),
    MANGROVE_TRAPDOOR("Mangrovenholzfalltür", Material.MANGROVE_TRAPDOOR),
    MANGROVE_WOOD("Mangrovenholz", Material.MANGROVE_WOOD),
    MANGROVE_WOOD_STRIPPED("Entrindetes Mangrovenholz", Material.STRIPPED_MANGROVE_WOOD),
    MAP_BURIED_TREASURE("Schatzkarte", Material.FILLED_MAP, CustomMatcher.translation("filled_map.buried_treasure")),
    MAP_EMPTY("Leere Karte", Material.MAP),
    MAP_OCEAN_EXPLORER("Ozean-Entdeckerkarte", Material.FILLED_MAP, CustomMatcher.translation("filled_map.monument")),
    MAP_WOODLAND_EXPLORER("Wald-Entdeckerkarte", Material.FILLED_MAP, CustomMatcher.translation("filled_map.mansion")),
    MELON_BLOCK("Melone", Material.MELON),
    MELON_SEEDS("Melonenkerne", Material.MELON_SEEDS),
    MELON_SLICE("Melonenscheibe", Material.MELON_SLICE),
    MINECART("Lore", Material.MINECART),
    MINECART_CHEST("Güterlore", Material.CHEST_MINECART),
    MINECART_FURNACE("Ofenlore", Material.FURNACE_MINECART),
    MINECART_HOPPER("Trichterlore", Material.HOPPER_MINECART),
    MINECART_TNT("TNT-Lore", Material.TNT_MINECART),
    MOSS_BLOCK("Moosblock", Material.MOSS_BLOCK),
    MOSS_CARPET("Moosteppich", Material.MOSS_CARPET),
    MOSSY_COBBLESTONE("Bemooster Bruchstein", Material.MOSSY_COBBLESTONE),
    MOSSY_COBBLESTONE_SLAB("Bemooste Bruchsteinstufe", Material.MOSSY_COBBLESTONE_SLAB),
    MOSSY_COBBLESTONE_STAIRS("Bemooste Bruchsteintreppe", Material.MOSSY_COBBLESTONE_STAIRS),
    MOSSY_COBBLESTONE_WALL("Bemooste Bruchsteinmauer", Material.MOSSY_COBBLESTONE_WALL),
    MOSSY_STONE_BRICK_SLAB("Bemooste Steinziegelstufe", Material.MOSSY_STONE_BRICK_SLAB),
    MOSSY_STONE_BRICK_STAIRS("Bemooste Steinziegeltreppe", Material.MOSSY_STONE_BRICK_STAIRS),
    MOSSY_STONE_BRICK_WALL("Bemooste Steinziegelmauer", Material.MOSSY_STONE_BRICK_WALL),
    MOSSY_STONE_BRICKS("Bemooste Steinziegel", Material.MOSSY_STONE_BRICKS),
    MUD("Schlamm", Material.MUD),
    MUD_BRICK_SLAB("Schlammziegelstufe", Material.MUD_BRICK_SLAB),
    MUD_BRICK_STAIRS("Schlammziegeltreppe", Material.MUD_BRICK_STAIRS),
    MUD_BRICK_WALL("Schlammziegelmauer", Material.MUD_BRICK_WALL),
    MUD_BRICKS("Schlammziegel", Material.MUD_BRICKS),
    MUD_PACKED("Fester Schlamm", Material.PACKED_MUD),
    MUDDY_MANGROVE_ROOTS("Schlammige Mangrovenwurzeln", Material.MUDDY_MANGROVE_ROOTS),
    MUSHROOM_BLOCK_BROWN("Brauner Pilzblock", Material.BROWN_MUSHROOM_BLOCK),
    MUSHROOM_BLOCK_RED("Roter Pilzblock", Material.RED_MUSHROOM_BLOCK),
    MUSHROOM_BROWN("Brauner Pilz", Material.BROWN_MUSHROOM),
    MUSHROOM_RED("Roter Pilz", Material.RED_MUSHROOM),
    MUSHROOM_STEM("Pilzstiel", Material.MUSHROOM_STEM),
    MUSHROOM_STEW("Pilzsuppe", Material.MUSHROOM_STEW),
    MUTTON("Rohes Hammelfleisch", Material.MUTTON),
    MUTTON_COOKED("Gebratenes Hammelfleisch", Material.COOKED_MUTTON),
    MYCELIUM("Myzel", Material.MYCELIUM),
    NAME_TAG("Namensschild", Material.NAME_TAG),
    NAUTILUS_SHELL("Nautilusschale", Material.NAUTILUS_SHELL),
    NETHER_BRICK("Netherziegel", Material.NETHER_BRICK),
    NETHER_BRICK_FENCE("Netherziegelzaun", Material.NETHER_BRICK_FENCE),
    NETHER_BRICK_SLAB("Netherziegelstufe", Material.NETHER_BRICK_SLAB),
    NETHER_BRICK_STAIRS("Netherziegeltreppe", Material.NETHER_BRICK_STAIRS),
    NETHER_BRICK_STAIRS_RED("Rote Netherziegeltreppe", Material.RED_NETHER_BRICK_STAIRS),
    NETHER_BRICK_WALL("Netherziegelmauer", Material.NETHER_BRICK_WALL),
    NETHER_BRICK_WALL_RED("Rote Netherziegelmauer", Material.RED_NETHER_BRICK_WALL),
    NETHER_BRICKS("Netherziegel", Material.NETHER_BRICKS),
    NETHER_BRICKS_RED("Rote Netherziegel", Material.RED_NETHER_BRICKS),
    NETHER_GOLD_ORE("Nethergolderz", Material.NETHER_GOLD_ORE),
    NETHER_QUARTZ_ORE("Netherquarzerz", Material.NETHER_QUARTZ_ORE),
    NETHER_SPROUTS("Nethersprossen", Material.NETHER_SPROUTS),
    NETHER_STAR("Netherstern", Material.NETHER_STAR),
    NETHER_WART("Netherwarze", Material.NETHER_WART),
    NETHER_WART_BLOCK("Netherwarzenblock", Material.NETHER_WART_BLOCK),
    NETHERITE_AXE("Netheritaxt", Material.NETHERITE_AXE),
    NETHERITE_BLOCK("Netheritblock", Material.NETHERITE_BLOCK),
    NETHERITE_BOOTS("Netheritstiefel", Material.NETHERITE_BOOTS),
    NETHERITE_CHESTPLATE("Netheritharnisch", Material.NETHERITE_CHESTPLATE),
    NETHERITE_HELMET("Netherithelm", Material.NETHERITE_HELMET),
    NETHERITE_HOE("Netherithacke", Material.NETHERITE_HOE),
    NETHERITE_INGOT("Netheritbarren", Material.NETHERITE_INGOT),
    NETHERITE_LEGGINGS("Netheritbeinschutz", Material.NETHERITE_LEGGINGS),
    NETHERITE_PICKAXE("Netheritspitzhacke", Material.NETHERITE_PICKAXE),
    NETHERITE_SCRAP("Netheritplatten", Material.NETHERITE_SCRAP),
    NETHERITE_SHOVEL("Netheritschaufel", Material.NETHERITE_SHOVEL),
    NETHERITE_SWORD("Netheritschwert", Material.NETHERITE_SWORD),
    NETHERRACK("Netherrack", Material.NETHERRACK),
    NOTE_BLOCK("Notenblock", Material.NOTE_BLOCK),
    OAK_BOAT("Eichenholzboot", Material.OAK_BOAT),
    OAK_BUTTON("Eichenholzknopf", Material.OAK_BUTTON),
    OAK_CHEST_BOAT("Eichenholztruhenboot", Material.OAK_CHEST_BOAT),
    OAK_DOOR("Eichenholztür", Material.OAK_DOOR),
    OAK_FENCE("Eichenholzzaun", Material.OAK_FENCE),
    OAK_FENCE_GATE("Eichenholzzauntor", Material.OAK_FENCE_GATE),
    OAK_HANGING_SIGN("Eichenholzhängeschild", Material.OAK_HANGING_SIGN),
    OAK_LEAVES("Eichenlaub", Material.OAK_LEAVES),
    OAK_LOG("Eichenstamm", Material.OAK_LOG),
    OAK_LOG_STRIPPED("Entrindeter Eichenstamm", Material.STRIPPED_OAK_LOG),
    OAK_PLANKS("Eichenholzbretter", Material.OAK_PLANKS),
    OAK_PRESSURE_PLATE("Eichenholzdruckplatte", Material.OAK_PRESSURE_PLATE),
    OAK_SAPLING("Eichensetzling", Material.OAK_SAPLING),
    OAK_SIGN("Eichenholzschild", Material.OAK_SIGN),
    OAK_SLAB("Eichenholzstufe", Material.OAK_SLAB),
    OAK_STAIRS("Eichenholztreppe", Material.OAK_STAIRS),
    OAK_TRAPDOOR("Eichenholzfalltür", Material.OAK_TRAPDOOR),
    OAK_WOOD("Eichenholz", Material.OAK_WOOD),
    OAK_WOOD_STRIPPED("Entrindetes Eichenholz", Material.STRIPPED_OAK_WOOD),
    OBSERVER("Beobachter", Material.OBSERVER),
    OBSIDIAN("Obsidian", Material.OBSIDIAN),
    ORCHID("Blaue Orchidee", Material.BLUE_ORCHID),
    OXEYE_DAISY("Margerite", Material.OXEYE_DAISY),
    PAINTING("Gemälde", Material.PAINTING),
    PAPER("Papier", Material.PAPER),
    PEONY("Pfingstrose", Material.PEONY),
    PETALS("Rosa Blütenblätter", Material.PINK_PETALS),
    PHANTOM_MEMBRANE("Phantomhaut", Material.PHANTOM_MEMBRANE),
    PISTON("Kolben", Material.PISTON),
    PITCHER_PLANT("Kannenpflanze", Material.PITCHER_PLANT),
    PITCHER_POD("Kannenpflanzenkapsel", Material.PITCHER_POD),
    PODZOL("Podsol", Material.PODZOL),
    POINTED_DRIPSTONE("Spitzer Tropfstein", Material.POINTED_DRIPSTONE),
    POLISHED_ANDESITE("Polierter Andesit", Material.POLISHED_ANDESITE),
    POLISHED_ANDESITE_SLAB("Polierte Andesitstufe", Material.POLISHED_ANDESITE_SLAB),
    POLISHED_ANDESITE_STAIRS("Polierte Andesittreppe", Material.POLISHED_ANDESITE_STAIRS),
    POLISHED_BASALT("Polierter Basalt", Material.POLISHED_BASALT),
    POLISHED_BLACKSTONE("Polierter Schwarzstein", Material.POLISHED_BLACKSTONE),
    POLISHED_BLACKSTONE_BRICK_SLAB("Polierte Schwarzsteinziegelstufe", Material.POLISHED_BLACKSTONE_BRICK_SLAB),
    POLISHED_BLACKSTONE_BRICK_STAIRS("Polierte Schwarzsteinziegeltreppe", Material.POLISHED_BLACKSTONE_BRICK_STAIRS),
    POLISHED_BLACKSTONE_BRICK_WALL("Polierte Schwarzsteinziegelmauer", Material.POLISHED_BLACKSTONE_BRICK_WALL),
    POLISHED_BLACKSTONE_BRICKS("Polierte Schwarzsteinziegel", Material.POLISHED_BLACKSTONE_BRICKS),
    POLISHED_BLACKSTONE_BUTTON("Polierter Schwarzsteinknopf", Material.POLISHED_BLACKSTONE_BUTTON),
    POLISHED_BLACKSTONE_PRESSURE_PLATE("Polierte Schwarzsteindruckplatte", Material.POLISHED_BLACKSTONE_PRESSURE_PLATE),
    POLISHED_BLACKSTONE_SLAB("Polierte Schwarzsteinstufe", Material.POLISHED_BLACKSTONE_SLAB),
    POLISHED_BLACKSTONE_STAIRS("Polierte Schwarzsteintreppe", Material.POLISHED_BLACKSTONE_STAIRS),
    POLISHED_BLACKSTONE_WALL("Polierte Schwarzsteinmauer", Material.POLISHED_BLACKSTONE_WALL),
    POLISHED_DEEPSLATE("Polierter Tiefenschiefer", Material.POLISHED_DEEPSLATE),
    POLISHED_DEEPSLATE_SLAB("Polierte Tiefenschieferstufe", Material.POLISHED_DEEPSLATE_SLAB),
    POLISHED_DEEPSLATE_STAIRS("Polierte Tiefenschiefertreppe", Material.POLISHED_DEEPSLATE_STAIRS),
    POLISHED_DEEPSLATE_WALL("Polierte Tiefenschiefermauer", Material.POLISHED_DEEPSLATE_WALL),
    POLISHED_DIORITE("Polierter Diorit", Material.POLISHED_DIORITE),
    POLISHED_DIORITE_SLAB("Polierte Dioritstufe", Material.POLISHED_DIORITE_SLAB),
    POLISHED_DIORITE_STAIRS("Polierte Diorittreppe", Material.POLISHED_DIORITE_STAIRS),
    POLISHED_GRANITE("Polierter Granit", Material.POLISHED_GRANITE),
    POLISHED_GRANITE_SLAB("Polierte Granitstufe", Material.POLISHED_GRANITE_SLAB),
    POLISHED_GRANITE_STAIRS("Polierte Granittreppe", Material.POLISHED_GRANITE_STAIRS),
    POPPED_CHORUS_FRUIT("Geplatzte Chorusfrucht", Material.POPPED_CHORUS_FRUIT),
    POPPY("Mohn", Material.POPPY),
    PORKCHOP("Rohes Schweinefleisch", Material.PORKCHOP),
    PORKCHOP_COOKED("Gebratenes Schweinefleisch", Material.COOKED_PORKCHOP),
    POTATO("Kartoffel", Material.POTATO),
    POTATO_BAKED("Ofenkartoffel", Material.BAKED_POTATO),
    POTATO_POISONOUS("Giftige Kartoffel", Material.POISONOUS_POTATO),
    POTION_AWKWARD("Seltsamer Trank", Material.POTION, CustomMatcher.potion(PotionType.AWKWARD)),
    POTION_FIRE_RESISTANCE("Trank der Feuerresistenz", Material.POTION, CustomMatcher.potion(PotionType.FIRE_RESISTANCE)),
    POTION_FIRE_RESISTANCE_LONG("Trank der Feuerresistenz (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_FIRE_RESISTANCE)),
    POTION_HARMING("Trank des Schadens", Material.POTION, CustomMatcher.potion(PotionType.HARMING)),
    POTION_HARMING_STRONG("Trank des Schadens (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_HARMING)),
    POTION_HEALING("Trank der Heilung", Material.POTION, CustomMatcher.potion(PotionType.HEALING)),
    POTION_HEALING_STRONG("Trank der Heilung (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_HEALING)),
    POTION_INVISIBILITY("Trank der Unsichtbarkeit", Material.POTION, CustomMatcher.potion(PotionType.INVISIBILITY)),
    POTION_INVISIBILITY_LONG("Trank der Unsichtbarkeit (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_INVISIBILITY)),
    POTION_LEAPING("Trank der Sprungkraft", Material.POTION, CustomMatcher.potion(PotionType.LEAPING)),
    POTION_LEAPING_LONG("Trank der Sprungkraft (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_LEAPING)),
    POTION_LEAPING_STRONG("Trank der Sprungkraft (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_LEAPING)),
    POTION_MUNDANE("Gewöhnlicher Trank", Material.POTION, CustomMatcher.potion(PotionType.MUNDANE)),
    POTION_NIGHT_VISION("Trank der Nachtsicht", Material.POTION, CustomMatcher.potion(PotionType.NIGHT_VISION)),
    POTION_NIGHT_VISION_LONG("Trank der Nachtsicht (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_NIGHT_VISION)),
    POTION_POISON("Trank der Vergiftung", Material.POTION, CustomMatcher.potion(PotionType.POISON)),
    POTION_POISON_LONG("Trank der Vergiftung (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_POISON)),
    POTION_POISON_STRONG("Trank der Vergiftung (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_POISON)),
    POTION_REGENERATION("Trank der Regeneration", Material.POTION, CustomMatcher.potion(PotionType.REGENERATION)),
    POTION_REGENERATION_LONG("Trank der Regeneration (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_REGENERATION)),
    POTION_REGENERATION_STRONG("Trank der Regeneration (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_REGENERATION)),
    POTION_SLOW_FALLING("Trank des sanften Falls", Material.POTION, CustomMatcher.potion(PotionType.SLOW_FALLING)),
    POTION_SLOW_FALLING_LONG("Trank des sanften Falls (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_SLOW_FALLING)),
    POTION_SLOWNESS("Trank der Langsamkeit", Material.POTION, CustomMatcher.potion(PotionType.SLOWNESS)),
    POTION_SLOWNESS_LONG("Trank der Langsamkeit (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_SLOWNESS)),
    POTION_SLOWNESS_STRONG("Trank der Langsamkeit (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_SLOWNESS)),
    POTION_STRENGTH("Trank der Stärke", Material.POTION, CustomMatcher.potion(PotionType.STRENGTH)),
    POTION_STRENGTH_LONG(" Trank der Stärke (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_STRENGTH)),
    POTION_STRENGTH_STRONG("Trank der Stärke (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_STRENGTH)),
    POTION_SWIFTNESS("Trank der Schnelligkeit", Material.POTION, CustomMatcher.potion(PotionType.SWIFTNESS)),
    POTION_SWIFTNESS_LONG("Trank der Schnelligkeit (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_SWIFTNESS)),
    POTION_SWIFTNESS_STRONG("Trank der Schnelligkeit (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_SWIFTNESS)),
    POTION_THICK("Dickflüssiger Trank", Material.POTION, CustomMatcher.potion(PotionType.THICK)),
    POTION_TURTLE_MASTER("Trank des Schildkrötenmeisters", Material.POTION, CustomMatcher.potion(PotionType.TURTLE_MASTER)),
    POTION_TURTLE_MASTER_LONG("Trank des Schildkrötenmeisters (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_TURTLE_MASTER)),
    POTION_TURTLE_MASTER_STRONG("Trank des Schildkrötenmeisters (II)", Material.POTION, CustomMatcher.potion(PotionType.STRONG_TURTLE_MASTER)),
    POTION_WATER_BOTTLE("Wasserflasche", Material.POTION, CustomMatcher.potion(PotionType.WATER)),
    POTION_WATER_BREATHING("Trank der Unterwasseratmung", Material.POTION, CustomMatcher.potion(PotionType.WATER_BREATHING)),
    POTION_WATER_BREATHING_LONG("Trank der Unterwasseratmung (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_WATER_BREATHING)),
    POTION_WEAKNESS("Trank der Schwäche", Material.POTION, CustomMatcher.potion(PotionType.WEAKNESS)),
    POTION_WEAKNESS_LONG("Trank der Schwäche (+)", Material.POTION, CustomMatcher.potion(PotionType.LONG_WEAKNESS)),
    PRISMARINE("Prismarin", Material.PRISMARINE),
    PRISMARINE_BRICK_SLAB("Prismarinziegelstufe", Material.PRISMARINE_BRICK_SLAB),
    PRISMARINE_BRICK_STAIRS("Prismarinziegeltreppe", Material.PRISMARINE_BRICK_STAIRS),
    PRISMARINE_BRICKS("Prismarinziegel", Material.PRISMARINE_BRICKS),
    PRISMARINE_CRYSTALS("Prismarinkristall", Material.PRISMARINE_CRYSTALS),
    PRISMARINE_SHARD("Prismarinscherbe", Material.PRISMARINE_SHARD),
    PRISMARINE_SLAB("Prismarinstufe", Material.PRISMARINE_SLAB),
    PRISMARINE_STAIRS("Prismarintreppe", Material.PRISMARINE_STAIRS),
    PRISMARINE_WALL("Prismarinmauer", Material.PRISMARINE_WALL),
    PUFFERFISH("Kugelfisch", Material.PUFFERFISH),
    PUMPKIN("Kürbis", Material.PUMPKIN),
    PUMPKIN_PIE("Kürbiskuchen", Material.PUMPKIN_PIE),
    PUMPKIN_SEEDS("Kürbiskerne", Material.PUMPKIN_SEEDS),
    PURPUR_BLOCK("Purpurblock", Material.PURPUR_BLOCK),
    PURPUR_PILLAR("Purpursäule", Material.PURPUR_PILLAR),
    PURPUR_SLAB("Purpurstufe", Material.PURPUR_SLAB),
    PURPUR_STAIRS("Purpurtreppe", Material.PURPUR_STAIRS),
    QUARTZ("Netherquarz", Material.QUARTZ),
    QUARTZ_BLOCK("Quarzblock", Material.QUARTZ_BLOCK),
    QUARTZ_BRICKS("Quarzziegel", Material.QUARTZ_BRICKS),
    QUARTZ_PILLAR("Quarzsäule", Material.QUARTZ_PILLAR),
    QUARTZ_SLAB("Quarzstufe", Material.QUARTZ_SLAB),
    QUARTZ_STAIRS("Quarztreppe", Material.QUARTZ_STAIRS),
    RABBIT("Rohes Kaninchen", Material.RABBIT),
    RABBIT_COOKED("Gebratenes Kaninchen", Material.COOKED_RABBIT),
    RABBIT_FOOT("Hasenpfote", Material.RABBIT_FOOT),
    RABBIT_HIDE("Kaninchenfell", Material.RABBIT_HIDE),
    RABBIT_STEW("Kaninchenragout", Material.RABBIT_STEW),
    RAIL("Schiene", Material.RAIL),
    RAIL_ACTIVATOR("Aktivierungsschiene", Material.ACTIVATOR_RAIL),
    RAIL_DETECTOR("Sensorschiene", Material.DETECTOR_RAIL),
    RAIL_POWERED("Antriebsschiene", Material.POWERED_RAIL),
    RECOVERY_COMPASS("Bergungskompass", Material.RECOVERY_COMPASS),
    RED_NETHER_BRICK_SLAB("Rote Netherziegelstufe", Material.RED_NETHER_BRICK_SLAB),
    REDSTONE("Redstone-Staub", Material.REDSTONE),
    REDSTONE_BLOCK("Redstoneblock", Material.REDSTONE_BLOCK),
    REDSTONE_LAMP("Redstone-Lampe", Material.REDSTONE_LAMP),
    REDSTONE_ORE("Redstone-Erz", Material.REDSTONE_ORE),
    REDSTONE_ORE_DEEPSLATE("Tiefenschiefer-Redstone-Erz", Material.DEEPSLATE_REDSTONE_ORE),
    REDSTONE_TORCH("Redstone-Fackel", Material.REDSTONE_TORCH),
    REPEATER("Redstone-Verstärker", Material.REPEATER),
    RESPAWN_ANCHOR("Seelenanker", Material.RESPAWN_ANCHOR),
    ROOTED_DIRT("Wurzelerde", Material.ROOTED_DIRT),
    ROSE_BUSH("Rosenstrauch", Material.ROSE_BUSH),
    ROTTEN_FLESH("Verrottetes Fleisch", Material.ROTTEN_FLESH),
    SADDLE("Sattel", Material.SADDLE),
    SALMON("Roher Lachs", Material.SALMON),
    SALMON_COOKED("Gebratener Lachs", Material.COOKED_SALMON),
    SAND("Sand", Material.SAND),
    SAND_RED("Roter Sand", Material.RED_SAND),
    SANDSTONE("Sandstein", Material.SANDSTONE),
    SANDSTONE_RED("Roter Sandstein", Material.RED_SANDSTONE),
    SANDSTONE_SLAB("Sandsteinstufe", Material.SANDSTONE_SLAB),
    SANDSTONE_SLAB_RED("Rote Sandsteinstufe", Material.RED_SANDSTONE_SLAB),
    SANDSTONE_STAIRS("Sandsteintreppe", Material.SANDSTONE_STAIRS),
    SANDSTONE_STAIRS_RED("Rote Sandsteintreppe", Material.RED_SANDSTONE_STAIRS),
    SANDSTONE_WALL("Sandsteinmauer", Material.SANDSTONE_WALL),
    SANDSTONE_WALL_RED("Rote Sandsteinmauer", Material.RED_SANDSTONE_WALL),
    SCAFFOLDING("Gerüst", Material.SCAFFOLDING),
    SCULK("Sculk", Material.SCULK),
    SCULK_CATALYST("Sculk-Katalysator", Material.SCULK_CATALYST),
    SCULK_SENSOR("Sculk-Sensor", Material.SCULK_SENSOR),
    SCULK_SHRIEKER("Sculk-Kreischer", Material.SCULK_SHRIEKER),
    SCULK_VEIN("Sculk-Ader", Material.SCULK_VEIN),
    SEA_LANTERN("Seelaterne", Material.SEA_LANTERN),
    SEA_PICKLE("Meeresgurke", Material.SEA_PICKLE),
    SEAGRASS("Seegras", Material.SEAGRASS),
    SHEARS("Schere", Material.SHEARS),
    SHERD_ANGLER("Angler-Töpferscherbe", Material.ANGLER_POTTERY_SHERD),
    SHERD_ARCHER("Schützen-Töpferscherbe", Material.ARCHER_POTTERY_SHERD),
    SHERD_ARMS_UP("Gebärden-Töpferscherbe", Material.ARMS_UP_POTTERY_SHERD),
    SHERD_BLADE("Klingen-Töpferscherbe", Material.BLADE_POTTERY_SHERD),
    SHERD_BREWER("Brauer-Töpferscherbe", Material.BREWER_POTTERY_SHERD),
    SHERD_BURN("Flammen-Töpferscherbe", Material.BURN_POTTERY_SHERD),
    SHERD_DANGER("Gefahren-Töpferscherbe", Material.DANGER_POTTERY_SHERD),
    SHERD_EXPLORER("Entdecker-Töpferscherbe", Material.EXPLORER_POTTERY_SHERD),
    SHERD_FRIEND("Freundes-Töpferscheibe", Material.FRIEND_POTTERY_SHERD),
    SHERD_HEART("Herz-Töpferscherbe", Material.HEART_POTTERY_SHERD),
    SHERD_HEARTBREAKER("Herzschmerz-Töpferscherbe", Material.HEARTBREAK_POTTERY_SHERD),
    SHERD_HOWL("Geheul-Töpferscherbe", Material.HOWL_POTTERY_SHERD),
    SHERD_MINER("Bergarbeiter-Töpferscherbe", Material.MINER_POTTERY_SHERD),
    SHERD_MOURNER("Wimmerer-Töpferscherbe", Material.MOURNER_POTTERY_SHERD),
    SHERD_PLENTY("Reichtums-Töpferscherbe", Material.PLENTY_POTTERY_SHERD),
    SHERD_PRIZE("Juwelen-Töpferscherbe", Material.PRIZE_POTTERY_SHERD),
    SHERD_SHEAF("Garben-Töpferscherbe", Material.SHEAF_POTTERY_SHERD),
    SHERD_SHELTER("Zufluchts-Töpferscherbe", Material.SHELTER_POTTERY_SHERD),
    SHERD_SKULL("Totenkopf-Töpferscherbe", Material.SKULL_POTTERY_SHERD),
    SHERD_SNORT("Schnaub-Töpferscherbe", Material.SNORT_POTTERY_SHERD),
    SHIELD("Schild", Material.SHIELD),
    SHROOMLIGHT("Pilzlicht", Material.SHROOMLIGHT),
    SHULKER_BOX("Shulker-Kiste", Material.SHULKER_BOX),
    SHULKER_BOX_BLACK("Schwarze Shulker-Kiste", Material.BLACK_SHULKER_BOX),
    SHULKER_BOX_BLUE("Blaue Shulker-Kiste", Material.BLUE_SHULKER_BOX),
    SHULKER_BOX_BROWN("Braune Shulker-Kiste", Material.BROWN_SHULKER_BOX),
    SHULKER_BOX_CYAN("Türkise Shulker-Kiste", Material.CYAN_SHULKER_BOX),
    SHULKER_BOX_GRAY("Graue Shulker-Kiste", Material.GRAY_SHULKER_BOX),
    SHULKER_BOX_GREEN("Grüne Shulker-Kiste", Material.GREEN_SHULKER_BOX),
    SHULKER_BOX_LIGHT_BLUE("Hellblaue Shulker-Kiste", Material.LIGHT_BLUE_SHULKER_BOX),
    SHULKER_BOX_LIGHT_GRAY("Hellgraue Shulker-Kiste", Material.LIGHT_GRAY_SHULKER_BOX),
    SHULKER_BOX_LIME("Hellgrüne Shulker-Kiste", Material.LIME_SHULKER_BOX),
    SHULKER_BOX_MAGENTA("Magenta Shulker-Kiste", Material.MAGENTA_SHULKER_BOX),
    SHULKER_BOX_ORANGE("Orange Shulker-Kiste", Material.ORANGE_SHULKER_BOX),
    SHULKER_BOX_PINK("Rosa Shulker-Kiste", Material.PINK_SHULKER_BOX),
    SHULKER_BOX_PURPLE("Violette Shulker-Kiste", Material.PURPLE_SHULKER_BOX),
    SHULKER_BOX_RED("Rote Shulker-Kiste", Material.RED_SHULKER_BOX),
    SHULKER_BOX_WHITE("Weiße Shulker-Kiste", Material.WHITE_SHULKER_BOX),
    SHULKER_BOX_YELLOW("Gelbe Shulker-Kiste", Material.YELLOW_SHULKER_BOX),
    SHULKER_SHELL("Shulker-Schale", Material.SHULKER_SHELL),
    SLIME_BALL("Schleimball", Material.SLIME_BALL),
    SLIME_BLOCK("Schleimblock", Material.SLIME_BLOCK),
    SMITHING_TABLE("Schmiedetisch", Material.SMITHING_TABLE),
    SMOKER("Räucherofen", Material.SMOKER),
    SMOOTH_BASALT("Glatter Basalt", Material.SMOOTH_BASALT),
    SMOOTH_QUARTZ("Glatter Quartzblock", Material.SMOOTH_QUARTZ),
    SMOOTH_QUARTZ_SLAB("Glatte Quarzstufe", Material.SMOOTH_QUARTZ_SLAB),
    SMOOTH_QUARTZ_STAIRS("Glatte Quartztreppe", Material.SMOOTH_QUARTZ_STAIRS),
    SMOOTH_RED_SANDSTONE("Glatter roter Sandstein", Material.SMOOTH_RED_SANDSTONE),
    SMOOTH_RED_SANDSTONE_SLAB("Glatte rote Sandsteinstufe", Material.SMOOTH_RED_SANDSTONE_SLAB),
    SMOOTH_RED_SANDSTONE_STAIRS("Glatte rote Sandsteintreppe", Material.SMOOTH_RED_SANDSTONE_STAIRS),
    SMOOTH_SANDSTONE("Glatter Sandstein", Material.SMOOTH_SANDSTONE),
    SMOOTH_SANDSTONE_SLAB("Glatte Sandsteinstufe", Material.SMOOTH_SANDSTONE_SLAB),
    SMOOTH_SANDSTONE_STAIRS("Glatte Sandsteintreppe", Material.SMOOTH_SANDSTONE_STAIRS),
    SMOOTH_STONE("Glatter Stein", Material.SMOOTH_STONE),
    SMOOTH_STONE_SLAB("Glatte Steinstufe", Material.SMOOTH_STONE_SLAB),
    SNIFFER_EGG("Schnüffler-Ei", Material.SNIFFER_EGG),
    SNOW("Schnee", Material.SNOW),
    SNOW_BLOCK("Schneeblock", Material.SNOW_BLOCK),
    SNOWBALL("Schneeball", Material.SNOWBALL),
    SOUL_CAMPFIRE("Seelenlagerfeuer", Material.SOUL_CAMPFIRE),
    SOUL_LANTERN("Seelenlaterne", Material.SOUL_LANTERN),
    SOUL_SAND("Seelensand", Material.SOUL_SAND),
    SOUL_SOIL("Seelenerde", Material.SOUL_SOIL),
    SOUL_TORCH("Seelenfackel", Material.SOUL_TORCH),
    SPECTRAL_ARROW("Spektralpfeil", Material.SPECTRAL_ARROW),
    SPIDER_EYE("Spinnenauge", Material.SPIDER_EYE),
    SPONGE("Schwamm", Material.SPONGE),
    SPONGE_WET("Nasser Schwamm", Material.WET_SPONGE),
    SPORE_BLOSSOM("Sporenblüte", Material.SPORE_BLOSSOM),
    SPRUCE_BOAT("Fichtenholzboot", Material.SPRUCE_BOAT),
    SPRUCE_BUTTON("Fichtenholzknopf", Material.SPRUCE_BUTTON),
    SPRUCE_CHEST_BOAT("Fichtenholztruhenboot", Material.SPRUCE_CHEST_BOAT),
    SPRUCE_DOOR("Fichtenholztür", Material.SPRUCE_DOOR),
    SPRUCE_FENCE("Fichtenholzzaun", Material.SPRUCE_FENCE),
    SPRUCE_FENCE_GATE("Fichtenholzzauntor", Material.SPRUCE_FENCE_GATE),
    SPRUCE_HANGING_SIGN("Fichtenholzhängeschild", Material.SPRUCE_HANGING_SIGN),
    SPRUCE_LEAVES("Fichtennadeln", Material.SPRUCE_LEAVES),
    SPRUCE_LOG("Fichtenstamm", Material.SPRUCE_LOG),
    SPRUCE_LOG_STRIPPED("Entrindeter Fichtenstamm", Material.STRIPPED_SPRUCE_LOG),
    SPRUCE_PLANKS("Fichtenholzbretter", Material.SPRUCE_PLANKS),
    SPRUCE_PRESSURE_PLATE("Fichtenholzdruckplatte", Material.SPRUCE_PRESSURE_PLATE),
    SPRUCE_SAPLING("Fichtensetzling", Material.SPRUCE_SAPLING),
    SPRUCE_SIGN("Fichtenholzschild", Material.SPRUCE_SIGN),
    SPRUCE_SLAB("Fichtenholzstufe", Material.SPRUCE_SLAB),
    SPRUCE_STAIRS("Fichtenholztreppe", Material.SPRUCE_STAIRS),
    SPRUCE_TRAPDOOR("Fichtenholztreppe", Material.SPRUCE_TRAPDOOR),
    SPRUCE_WOOD("Fichtenholz", Material.SPRUCE_WOOD),
    SPRUCE_WOOD_STRIPPED("Entrindetes Fichtenholz", Material.STRIPPED_SPRUCE_WOOD),
    SPYGLASS("Fernrohr", Material.SPYGLASS),
    STAINED_GLASS_BLACK("Schwarzes Glas", Material.BLACK_STAINED_GLASS),
    STAINED_GLASS_BLUE("Blaues Glas", Material.BLUE_STAINED_GLASS),
    STAINED_GLASS_BROWN("Braunes Glas", Material.BROWN_STAINED_GLASS),
    STAINED_GLASS_CYAN("Türkises Glas", Material.CYAN_STAINED_GLASS),
    STAINED_GLASS_GRAY("Graues Glas", Material.GRAY_STAINED_GLASS),
    STAINED_GLASS_GREEN("Grünes Glas", Material.GREEN_STAINED_GLASS),
    STAINED_GLASS_LIGHT_BLUE("Hellblaues Glas", Material.LIGHT_BLUE_STAINED_GLASS),
    STAINED_GLASS_LIGHT_GRAY("Hellgraues Glas", Material.LIGHT_GRAY_STAINED_GLASS),
    STAINED_GLASS_LIME("Hellgrünes Glas", Material.LIME_STAINED_GLASS),
    STAINED_GLASS_MAGENTA("Magenta Glas", Material.MAGENTA_STAINED_GLASS),
    STAINED_GLASS_ORANGE("Oranges Glas", Material.ORANGE_STAINED_GLASS),
    STAINED_GLASS_PANE_BLACK("Schwarze Glasscheibe", Material.BLACK_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_BLUE("Blaue Glasscheibe", Material.BLUE_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_BROWN("Braune Glasscheibe", Material.BROWN_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_CYAN("Türkise Glasscheibe", Material.CYAN_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_GRAY("Graue Glasscheibe", Material.GRAY_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_GREEN("Grüne Glasscheibe", Material.GREEN_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_LIGHT_BLUE("Hellblaue Glasscheibe", Material.LIGHT_BLUE_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_LIGHT_GRAY("Hellgraue Glasscheibe", Material.LIGHT_GRAY_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_LIME("Hellgrüne Glasscheibe", Material.LIME_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_MAGNETA("Magenta Glasscheibe", Material.MAGENTA_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_ORANGE("Orange Glasscheibe", Material.ORANGE_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_PINK("Rosa Glasscheibe", Material.PINK_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_PURPLE("Violette Glasscheibe", Material.PURPLE_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_RED("Rote Glasscheibe", Material.RED_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_WHITE("Weiße Glasscheibe", Material.WHITE_STAINED_GLASS_PANE),
    STAINED_GLASS_PANE_YELLOW("Gelbe Glasscheibe", Material.YELLOW_STAINED_GLASS_PANE),
    STAINED_GLASS_PINK("Rosa Glas", Material.PINK_STAINED_GLASS),
    STAINED_GLASS_PURPLE("Violettes Glas", Material.PURPLE_STAINED_GLASS),
    STAINED_GLASS_RED("Rotes Glas", Material.RED_STAINED_GLASS),
    STAINED_GLASS_WHITE("Weißes Glas", Material.WHITE_STAINED_GLASS),
    STAINED_GLASS_YELLOW("Gelbes Glas", Material.YELLOW_STAINED_GLASS),
    STICK("Stock", Material.STICK),
    STICKY_PISTON("Klebriger Kolben", Material.STICKY_PISTON),
    STONE("Stein", Material.STONE),
    STONE_AXE("Steinaxt", Material.STONE_AXE),
    STONE_BRICK_SLAB("Steinziegelstufe", Material.STONE_BRICK_SLAB),
    STONE_BRICK_STAIRS("Steinziegeltreppe", Material.STONE_BRICK_STAIRS),
    STONE_BRICK_WALL("Steinziegelmauer", Material.STONE_BRICK_WALL),
    STONE_BRICKS("Steinziegel", Material.STONE_BRICKS),
    STONE_BUTTON("Steinknopf", Material.STONE_BUTTON),
    STONE_HOE("Steinhacke", Material.STONE_HOE),
    STONE_PICKAXE("Steinspithacke", Material.STONE_PICKAXE),
    STONE_PRESSURE_PLATE("Steindruckplatte", Material.STONE_PRESSURE_PLATE),
    STONE_SHOVEL("Steinschaufel", Material.STONE_SHOVEL),
    STONE_SLAB("Steinstufe", Material.STONE_SLAB),
    STONE_STAIRS("Steintreppe", Material.STONE_STAIRS),
    STONE_SWORD("Steinschwert", Material.STONE_SWORD),
    STONECUTTER("Steinsäge", Material.STONECUTTER),
    STRING("Faden", Material.STRING),
    STRIPPED_BAMBOO_BLOCK("Geschälter Bambusblock", Material.STRIPPED_BAMBOO_BLOCK),
    SUGAR("Zucker", Material.SUGAR),
    SUGAR_CANE("Zuckerrohr", Material.SUGAR_CANE),
    SUNFLOWER("Sonnenblume", Material.SUNFLOWER),
    SUSPICIOUS_STEW("Seltsame Suppe", Material.SUSPICIOUS_STEW),
    SWEET_BERRIES("Süßbeeren", Material.SWEET_BERRIES),
    TARGET("Zeilblock", Material.TARGET),
    TEMPLATE_COAST("Schmiedevorlage-Küste", Material.COAST_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_DUNE("Schmiedevorlage-Düne", Material.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_EYE("Schmiedevorlage-Augen", Material.EYE_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_HOST("Schmiedevorlage-Gastwirt", Material.HOST_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_NETHERITE_UPGRADE("Schmiedevorlage-Netheritaufwertung", Material.NETHERITE_UPGRADE_SMITHING_TEMPLATE),
    TEMPLATE_RAISER("Schmiedevorlage-Aufzieher", Material.RAISER_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_RIB("Schmiedevorlage-Rippen", Material.RIB_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_SENTRY("Schmiedevorlage-Wachen", Material.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_SHAPER("Schmiedevorlage-Gestalter", Material.SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_SILENCE("Schmiedevorlage-Stille", Material.SILENCE_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_SNOUT("Schmiedevorlage-Schnauzen", Material.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_SPIRE("Schmiedevorlage-Turmspitzen", Material.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_TIDE("Schmiedevorlage-Gezeiten", Material.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_VEX("Schmiedevorlage-Plagegeister", Material.VEX_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_WARD("Schmiedevorlage-Warthof", Material.WARD_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_WAYFINDER("Schmiedevorlage-Wegfinder", Material.WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE),
    TEMPLATE_WILD("Schmiedevorlage-Wildnis", Material.WILD_ARMOR_TRIM_SMITHING_TEMPLATE),
    TERRACOTTA("Keramik", Material.TERRACOTTA),
    TERRACOTTA_BLACK("Schwarze Keramik", Material.BLACK_TERRACOTTA),
    TERRACOTTA_BLUE("Blaue Keramik", Material.BLUE_TERRACOTTA),
    TERRACOTTA_BROWN("Braune Keramik", Material.BROWN_TERRACOTTA),
    TERRACOTTA_CYAN("Türkise Keramik", Material.CYAN_TERRACOTTA),
    TERRACOTTA_GLAZED_BLACK("Schwarze glasierte Keramik", Material.BLACK_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_BLUE("Blaue glasierte Keramik", Material.BLUE_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_BROWN("Braune glasierte Keramik", Material.BROWN_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_CYAN("Türkise glasierte Keramik", Material.CYAN_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_GRAY("Graue glasierte Keramik", Material.GRAY_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_GREEN("Grüne glasierte Keramik", Material.GREEN_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_LIGHT_BLUE("Hellblaue glasierte Keramik", Material.LIGHT_BLUE_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_LIGHT_GRAY("Hellgrau glasierte Keramik", Material.LIGHT_GRAY_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_LIME("Hellgrüne glasierte Keramik", Material.LIME_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_MAGENTA("Magenta glasierte Keramik", Material.MAGENTA_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_ORANGE("Orange glasierte Keramik", Material.ORANGE_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_PINK("Rosa glasierte Keramik", Material.PINK_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_PURPLE("Violett glasierte Keramik", Material.PURPLE_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_RED("Rote glasierte Keramik", Material.RED_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_WHITE("Weiße glasierte Keramik", Material.WHITE_GLAZED_TERRACOTTA),
    TERRACOTTA_GLAZED_YELLOW("Gelbe glasierte Keramik", Material.YELLOW_GLAZED_TERRACOTTA),
    TERRACOTTA_GRAY("Graue Keramik", Material.GRAY_TERRACOTTA),
    TERRACOTTA_GREEN("Grüne Keramik", Material.GREEN_TERRACOTTA),
    TERRACOTTA_LIGHT_BLUE("Hellblaue Keramik", Material.LIGHT_BLUE_TERRACOTTA),
    TERRACOTTA_LIGHT_GRAY("Hellgraue Keramik", Material.LIGHT_GRAY_TERRACOTTA),
    TERRACOTTA_LIME("Hellgrüne Keramik", Material.LIME_TERRACOTTA),
    TERRACOTTA_MAGENTA("Magenta Keramik", Material.MAGENTA_TERRACOTTA),
    TERRACOTTA_ORANGE("Orange Keramik", Material.ORANGE_TERRACOTTA),
    TERRACOTTA_PINK("Rosa Keramik", Material.PINK_TERRACOTTA),
    TERRACOTTA_PURPLE("Violette Keramik", Material.PURPLE_TERRACOTTA),
    TERRACOTTA_RED("Rote Keramik", Material.RED_TERRACOTTA),
    TERRACOTTA_WHITE("Weiße Keramik", Material.WHITE_TERRACOTTA),
    TERRACOTTA_YELLOW("Gelbe Keramik", Material.YELLOW_TERRACOTTA),
    TINTED_GLASS("Getöntes Glas", Material.TINTED_GLASS),
    TIPPED_ARROW("Getränkter Pfeil", Material.TIPPED_ARROW),
    TNT("TNT", Material.TNT),
    TORCH("Fackel", Material.TORCH),
    TORCHFLOWER("Fackellilie", Material.TORCHFLOWER),
    TORCHFLOWER_SEEDS("Fackelliliensamen", Material.TORCHFLOWER_SEEDS),
    TOTEM_OF_UNDYING("Totem der Unsterblichkeit", Material.TOTEM_OF_UNDYING),
    TRAPPED_CHEST("Redstone-Truhe", Material.TRAPPED_CHEST),
    TRIDENT("Dreizack", Material.TRIDENT),
    TRIPWIRE_HOOK("Haken", Material.TRIPWIRE_HOOK),
    TROPICAL_FISH("Tropenfisch", Material.TROPICAL_FISH),
    TUFF("Tuffstein", Material.TUFF),
    TULIP_ORANGE("Orange Tulpe", Material.ORANGE_TULIP),
    TULIP_PINK("Rosa Tulpe", Material.PINK_TULIP),
    TULIP_RED("Rote Tulpe", Material.RED_TULIP),
    TULIP_WHITE("Weißte Tulpe", Material.WHITE_TULIP),
    TURTLE_EGG("Schildkröten-Spawn-Ei", Material.TURTLE_EGG),
    TURTLE_HELMET("Schildkrötenpanzer", Material.TURTLE_HELMET),
    TURTLE_SCUTE("Schildkrötenei", Material.TURTLE_SCUTE),
    VINE("Ranken", Material.VINE),
    VINE_TWISTING("Zwirbelranken", Material.TWISTING_VINES),
    VINE_WEEPING("Trauerranken", Material.WEEPING_VINES),
    WARPED_BUTTON("Wirrknopf", Material.WARPED_BUTTON),
    WARPED_DOOR("Wirrtür", Material.WARPED_DOOR),
    WARPED_FENCE("Wirrzaun", Material.WARPED_FENCE),
    WARPED_FENCE_GATE("Wirrzauntor", Material.WARPED_FENCE_GATE),
    WARPED_FUNGUS("Wirrpilz", Material.WARPED_FUNGUS),
    WARPED_FUNGUS_ON_A_STICK("Wirrplizrute", Material.WARPED_FUNGUS_ON_A_STICK),
    WARPED_HANGING_SIGN("Wirrhängeschild", Material.WARPED_HANGING_SIGN),
    WARPED_HYPHAE("Wirrhyphen", Material.WARPED_HYPHAE),
    WARPED_NYLIUM("Wirr-Nezel", Material.WARPED_NYLIUM),
    WARPED_PLANKS("Wirrbretter", Material.WARPED_PLANKS),
    WARPED_PRESSURE_PLATE("Wirrdruckplatte", Material.WARPED_PRESSURE_PLATE),
    WARPED_ROOTS("Wirrwurzeln", Material.WARPED_ROOTS),
    WARPED_SIGN("Wirrschild", Material.WARPED_SIGN),
    WARPED_SLAB("Wirrstufe", Material.WARPED_SLAB),
    WARPED_STAIRS("Wirrtreppe", Material.WARPED_STAIRS),
    WARPED_STEM("Wirrstiel", Material.WARPED_STEM),
    WARPED_STEM_STRIPPED("Geschälter Wirrstiel", Material.STRIPPED_WARPED_STEM),
    WARPED_TRAPDOOR("Wirrfalltür", Material.WARPED_TRAPDOOR),
    WARPED_WART_BLOCK("Wirrwarzenblock", Material.WARPED_WART_BLOCK),
    WARRPED_HYPHAE_STRIPPED("Geschälte Wirrhyphen", Material.STRIPPED_WARPED_HYPHAE),
    WHEAT("Weizen", Material.WHEAT),
    WHEAT_SEEDS("Weizenkörner", Material.WHEAT_SEEDS),
    WHITE_CANDLE("Weiße Kerze", Material.WHITE_CANDLE),
    WITHER_ROSE("Wither-Rose", Material.WITHER_ROSE),
    WOLF_ARMOR("Wolfspanzer", Material.WOLF_ARMOR),
    WOODEN_AXE("Holzaxt", Material.WOODEN_AXE),
    WOODEN_HOE("Holzhacke", Material.WOODEN_HOE),
    WOODEN_PICKAXE("Holzspitzhacke", Material.WOODEN_PICKAXE),
    WOODEN_SHOVEL("Holzschaufel", Material.WOODEN_SHOVEL),
    WOODEN_SWORD("Holzschwert", Material.WOODEN_SWORD),
    WOOL_BLACK("Schwarze Wolle", Material.BLACK_WOOL),
    WOOL_BLUE("Blaue Wolle", Material.BLUE_WOOL),
    WOOL_BROWN("Braune Wolle", Material.BROWN_WOOL),
    WOOL_CYAN("Türkise Wolle", Material.CYAN_WOOL),
    WOOL_GRAY("Graue Wolle", Material.GRAY_WOOL),
    WOOL_GREEN("Grüne Wolle", Material.GREEN_WOOL),
    WOOL_LIGHT_BLUE("Hellblaue Wolle", Material.LIGHT_BLUE_WOOL),
    WOOL_LIGHT_GRAY("Hellgraue Wolle", Material.LIGHT_GRAY_WOOL),
    WOOL_LIME("Hellgrüne Wolle", Material.LIME_WOOL),
    WOOL_MAGNETA("Magenta Wolle", Material.MAGENTA_WOOL),
    WOOL_ORANGE("Orange Wolle", Material.ORANGE_WOOL),
    WOOL_PINK("Rosa Wolle", Material.PINK_WOOL),
    WOOL_PURPLE("Violette Wolle", Material.PURPLE_WOOL),
    WOOL_RED("Rote Wolle", Material.RED_WOOL),
    WOOL_WHITE("Weiße Wolle", Material.WHITE_WOOL),
    WOOL_YELLOW("Gelbe Wolle", Material.YELLOW_WOOL);

    @Getter private final String itemName;
    @Getter private final Material material;
    @Nullable private final CustomMatcher customMatcher;

    AllItem(String name, Material material) {
        this(name, material, null);
    }

    AllItem(String name, Material material, @Nullable CustomMatcher customMatcher) {
        this.itemName = name;
        this.material = material;
        this.customMatcher = customMatcher;
    }

    public boolean matches(@Nullable ItemStack itemStack) {
        if (itemStack == null) return false;
        boolean customMatch = this.customMatcher == null || this.customMatcher.matches(itemStack);
        return itemStack.getType() == material && customMatch;
    }

    public Component icon() {
        return ResourcePack.AllItems.itemIcon(this);
    }

}
