[plugins]
shadow = "io.github.goooler.shadow:8.1.5"

[libraries]
paperlib = "io.papermc:paperlib:1.0.7"
paper = "io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT"
xseries = "com.github.cryptomorin:XSeries:9.5.0"
lombok = "org.projectlombok:lombok:1.18.24"