[versions]
paper = "1.20.6-R0.1-SNAPSHOT"

[plugins]
shadow = "io.github.goooler.shadow:8.1.7"
paperweight = "io.papermc.paperweight.userdev:1.7.1"

[libraries]
paperlib = "io.papermc:paperlib:1.0.7"
xseries = "com.github.cryptomorin:XSeries:11.2.0"
lombok = "org.projectlombok:lombok:1.18.30"
kyori-adventure = "net.kyori:adventure-api:4.16.0"